### ISSUE TITLE
MS Graph create subscription (change notification) in java when user is added to AAD

### ISSUE THREAD

**Issue by AnjanaCloud** [microsoftgraph/msgraph-sdk-java#1013]
My code is for implementing a subscription (change notification in java ). I think my issue is auth provider and notificationUrl.
Also , I am in confusion about how to give the POST call to "http://localhost:4200/1/myNotificationUrl" , how to handle the POST call. It will be a great help if someone can clear my doubts. Thanks in advance.
```

           try{

               final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                       .clientId(CLIENT_ID)
                       .clientSecret(CLIENT_SECRET)
                       .tenantId(TENANT)
                       .build();

               final GraphServiceClient graphClient =
                       GraphServiceClient
                               .builder()
                               .authenticationProvider(new IAuthenticationProvider() {
                                   @NotNull
                                   @Override
                                   public CompletableFuture<String> getAuthorizationTokenAsync(@NotNull URL url) {
                                       return null;
                                   }
                               })
                               .buildClient();

               Subscription subscription = new Subscription();
               subscription.changeType = "created";
               subscription.notificationUrl = "http://localhost:4200/1/myNotificationUrl";
               subscription.resource = "/users";
               subscription.expirationDateTime = OffsetDateTimeSerializer.deserialize("2022-03-20T18:23:45.9356913Z");
               subscription.clientState = "secretClientValue";
               //   subscription.latestSupportedTlsVersion = "v1_2";

               Subscription graphresult = graphClient.subscriptions()
                       .buildRequest()
                       .post(subscription);
           
               System.out.println("graphresult :"+graphresult );
           } catch (Exception e) {
               e.printStackTrace();
               logger.info("\nException : "+e);
           }
```

**Comment by AnjanaCloud** [comment]
```
graphClient.subscriptions()
                        .buildRequest()
                        .post(subscription);
```

```
[vert.x-worker-thread-29] 2022-02-23T04:08:12.514Z INFO User.java
graphClient - com.microsoft.graph.requests.GraphServiceClient@7ce460ee
subscription - com.microsoft.graph.models.Subscription@5eabe03c
Exception : com.microsoft.graph.core.ClientException: Error executing the request
```

**Comment by baywet** [comment]
Hi @AnjanaCloud ,
Thanks for reaching out. Have you seen the [java spring change notifications sample](https://github.com/microsoftgraph/java-spring-webhooks-sample) ? it walks you through using change notifications with Java.

**Comment by AnjanaCloud** [comment]
Hi @baywet I checked the link you have provided but it couldnt resolve my issue . Now am getting the following error. Can anyone please help because its affecting a client deliverable .
```

18:42:48.026 [ForkJoinPool.commonPool-worker-1] ERROR c.a.identity.ClientSecretCredential - Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]
: Could not initialize class reactor.netty.http.client.HttpClientSecure
com.microsoft.graph.core.ClientException: Error executing the request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:411)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:226)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:203)
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
        at com.microsoft.graph.requests.SubscriptionRequest.post(SubscriptionRequest.java:122)
        at com.microsoft.graph.requests.SubscriptionCollectionRequest.post(SubscriptionCollectionRequest.java:64)
        at com.imcs.rest.User.lambda$start$1(User.java:292)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:200)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:533)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
```
![Screenshot (303)](https://user-images.githubusercontent.com/99974138/155502669-e2b0f1dc-74f5-48fa-8ab8-be7fd30998ad.png)
![Screenshot (304)](https://user-images.githubusercontent.com/99974138/155502689-436ed13e-3b69-401a-8ab0-69d770cbe6de.png)

**Comment by baywet** [comment]
Thanks for sharing additional information. 
> [ForkJoinPool.commonPool-worker-1] ERROR c.a.identity.ClientSecretCredential - Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]
: Could not initialize class reactor.netty.http.client.HttpClientSecure

Leads me to think the error is located in the Azure Identity library and not in the Graph SDK itself. I can see that [you already have opened an issue over Azure Identity](https://github.com/Azure/azure-sdk-for-java/issues/27267).

This is something easy to confirm by commenting out your code and running

```Java
final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                       .clientId(CLIENT_ID)
                       .clientSecret(CLIENT_SECRET)
                       .tenantId(TENANT)
                       .build();

final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(clientSecretCredential);

tokenCredentialAuthProvider.getAuthorizationTokenAsync(new URL("https://graph.microsoft.com")).get();
```

**Comment by p-hakim** [comment]
Hi, i have the same probleme, did you fin a solution ?
