### ISSUE TITLE
Getting sockettimedout error when accessing graph API using Proxy

### ISSUE THREAD

**Issue by ponns94** [microsoftgraph/msgraph-sdk-java#1045]
I am using custom authentication provider ( Implemented based on nimbus ) and trying to access graph api using proxy. My code is

Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("host", port));
        final Authenticator proxyAuthenticator = new Authenticator() {
            @Nullable
            @Override
            public Request authenticate(@Nullable Route route, @Nonnull Response response) throws IOException {
                String credentials = Credentials.basic("username", "password");
                return response.request().newBuilder().header("Proxy-Authorization", credentials).build();
            }
        };

        HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor(new GraphAPILogger());
        loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

        OkHttpClient httpClient = HttpClients.createDefault(new BaseAuthenticationProvider(){
            @Nonnull
            public CompletableFuture<String> getAuthorizationTokenAsync(@Nonnull final URL requestUrl) {
                if(this.shouldAuthenticateRequestWithUrl(requestUrl)) {
                    return CompletableFuture.completedFuture(GraphUtil.getInstance().getAccessToken());
                } else {
                    return CompletableFuture.completedFuture(null);
                }
            }
        }).newBuilder().proxy(proxy).proxyAuthenticator(proxyAuthenticator).addNetworkInterceptor(loggingInterceptor).addInterceptor(loggingInterceptor).build();
        GraphServiceClient<Request> graphServiceClient = GraphServiceClient.builder().httpClient(httpClient).buildClient();
        User me = graphServiceClient.me().buildRequest().get();

### Expected behavior

I should get the user properties

### Actual behavior

INFO: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
Exception in thread "main" com.microsoft.graph.core.ClientException: Error executing the request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:411)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:226)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:203)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
	at com.microsoft.graph.requests.UserRequest.get(UserRequest.java:138)
	at com.manageengine.servicedesk.mail.core.Test.uploadAttachmentInSession(Test.java:139)
	at com.manageengine.servicedesk.mail.core.Test.main(Test.java:85)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:457)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:137)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:177)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408)
	... 6 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.InputStreamSource.read(JvmOkio.kt:90)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	... 38 more

### Steps to reproduce the behavior

Please let me know what am I missing here.

**Comment by ponns94** [comment]
Anyone to help on this ? @

**Comment by ramsessanchez** [comment]
Hi @ponns94 , apologies for the delay. Firstly, could you tell me more about the Graph SDK version you are using? Also, is it possible for you to use Azure Identity for authentication in your scenario?

**Comment by ponns94** [comment]
@ramsessanchez ,

Our application supports Gsuite too and we have implemented the token obtaining part using Nimbus already. So, didn't want to go with new library for that.

Also, in the dependency part of microsoft-graph-sdk, the APIs work fine without azure-core library and its dependencies. On viewing the source code, only TokenCredentialAuthProvider is using that library. If we weren't going to use that, we can ignore the azure-core dependency ?

**Comment by ramsessanchez** [comment]
@ponns94 Yes, you can remove the azure-core dependency since you are opting to not use azure identity for authentication. 
Also, I suspect there may be an issue in the chaining of several calls being made. Could you try retrieving the token/authenticating prior to creating the client, ie rather than nesting the calls. I suspect there may be an issue with the sequence of the calls since the rest of your code seems to be correctly written based on the documentation: 
https://docs.microsoft.com/en-us/graph/sdks/customize-client?tabs=java#configuring-the-http-proxy-for-the-client
