### ISSUE TITLE
No suitable driver found after add "implementation 'com.microsoft.graph:microsoft-graph:5.29.0'"  into build.gradle file.

### ISSUE THREAD

**Issue by thoujean** [microsoftgraph/msgraph-sdk-java#1112]
I has an android app use an AsyncTask get mysql data, use some code like:

    private class GetSalesDataAsyncTask extends AsyncTask<Date, Void, List<Map<String, Object>>> {

        @Override
        protected List<Map<String, Object>> doInBackground(Date... dates) {
            try (Connection conn = DriverManager.getConnection(DB_URI, DB_USER, DB_PASSWROD)) {
                final String sql = "select * from sales where shop = ? and date >= ? and date <= ?";
                List<Object> lst = new ArrayList<>();
                lst.add("F027");
                lst.addAll(Arrays.asList(dates));
                return SqlQueryUtils.query(conn, sql, lst);
            } catch (SQLException e) {
                Log.e(LOG_TAG, "doInBackground(Date... dates): ", e);
            }
            return null;
        }

it work well, but I add:
"implementation 'com.microsoft.graph:microsoft-graph:5.29.0'" into build.gradle file, above code throw SQLException:

    java.sql.SQLException: No suitable driver found for jdbc:mysql://xxx.xx.xx.xxx:3306/test
        at java.sql.DriverManager.getConnection(DriverManager.java:605)
        at java.sql.DriverManager.getConnection(DriverManager.java:218)
        at com.fairwood.hello3.SQLActivity$GetSalesDataAsyncTask.doInBackground(SQLActivity.java:84)
        at com.fairwood.hello3.SQLActivity$GetSalesDataAsyncTask.doInBackground(SQLActivity.java:74)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

I found DriverManager deleted "com.mysql.jdbc.Driver, com.mysql.fabric.jdbc.FabricMySQLDriver", I don't know why?

I use "implementation 'mysql:mysql-connector-java:5.1.34'" on build.gradle file, and switch Postgresql driver get some error.

how to fix it?

**Comment by thoujean** [comment]
I found the answer, add "merge '**/java.sql.Driver'" build.gradle packagingOptions.

**Comment by thoujean** [comment]
I found the answer.
