### ISSUE TITLE
Nested Attachments using graph SDK

### ISSUE THREAD

**Issue by mahendrabaghel** [microsoftgraph/msgraph-sdk-java#1114]
We have a use case to grab the attachments outside of nested attachments. I was reading online documentation and it says graph API supports a depth of 30 nested attachments. I don't see any documentation or function in SDK to accomplish that. There is an ongoing thread "https://github.com/microsoftgraph/msgraph-sdk-java/issues/21" and it's not resolved.

### Expected behavior

When attachments is another message. ItemAttachment object should return the body and/or any attachments embedded in it.

### Actual behavior

ItemAttachment supports none of the functionality to expand it further.

### Steps to reproduce the behavior
_appClient
                .me()
                .messages(messageId)
                .attachments()
                .buildRequest()
                .get();

**Comment by mahendrabaghel** [comment]
I followed the code provided on Microsoft site (https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=java).

Code:
Attachment attachment = graphClient.me().messages("AAMkADA1M-zAAA=").attachments("AAMkADA1M-CJKtzmnlcqVgqI=")
	.buildRequest()
	.expand("itemattachment/item")
	.get();

Error:
Jul 05, 2022 1:00:09 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[sendRequestInternal] - 408Graph service exception
Jul 05, 2022 1:00:09 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: Parsing OData Select and Expand failed: Could not find a property named 'itemattachment' on type 'microsoft.graph.attachment'.

GET https://graph.microsoft.com/v1.0/me/messages/******/attachments/********?%24expand=itemattachment%2Fitem
SdkVersion : graph-java/v5.28.0


400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
2022-07-05 13:00:17.536 ERROR [main] [gov.ussc.email.app.USSCApp] [listInbox] [gov.ussc.email.app.USSCApp.listInbox(USSCApp.java:258)] - Issue in the listInbox, please check the error message.
com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: Parsing OData Select and Expand failed: Could not find a property named 'itemattachment' on type 'microsoft.graph.attachment'.

GET https://graph.microsoft.com/v1.0/me/messages/******/attachments/********?%24expand=itemattachment%2Fitem
SdkVersion : graph-java/v5.28.0


400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:512) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:442) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335) ~[microsoft-graph-core-2.0.13.jar:?]
	at com.microsoft.graph.requests.AttachmentRequest.get(AttachmentRequest.java:72) ~[microsoft-graph-5.28.0.jar:?]
	at gov.ussc.email.utils.GraphUserNamePassword.getEmbeddedMessages(GraphUserNamePassword.java:221) ~[classes/:?]
	at gov.ussc.email.app.USSCApp.listInbox(USSCApp.java:226) [classes/:?]
	at gov.ussc.email.app.USSCApp.main(USSCApp.java:85) [classes/:?]
Error getting inbox
Error code: BadRequest
Error message: Parsing OData Select and Expand failed: Could not find a property named 'itemattachment' on type 'microsoft.graph.attachment'.

**Comment by mahendrabaghel** [comment]
There is a bug in the documentation. Following code will work, and I am not sure how to grab the embedded item->attachmentpage->attachment. Any help will be appreciated.

Attachment attachment = _appClient.me().messages(origMessageId).attachments(itemAttachmentId)
    			.buildRequest()
    			.expand("microsoft.graph.itemattachment/item")
    			.get();

**Comment by mahendrabaghel** [comment]
I figured it out. The online documentation from microsoft is misleading (the .expand(itemattachment/item will not work). I am using graph (5.28.0) and this is how the nested messages work. Create your graph client from the online sample applications.

Get the embedded attachment using GraphUserNamePassword.getEmbeddedMessages function:
Attachment attachment = _appClient.me().messages(origMessageId).attachments(itemAttachmentId)
.buildRequest()
.expand("microsoft.graph.itemattachment/item")
.get();

Get the item from the attachment, check if it's of type message, and the grab the attachments collection from the message.

Attachment childAttachment = GraphUserNamePassword.getEmbeddedMessages(message.id,
									iAttachment.id, i);
							if (childAttachment instanceof FileAttachment) {
								saveFileAttachment(message.id, i, childAttachment, dataAttachments);
							} else if (childAttachment instanceof ItemAttachment) {
								log.info("Got another itemAttachment" + childAttachment.id);
								ItemAttachment iChildAttachment = (ItemAttachment) childAttachment;
								OutlookItem oItem = iChildAttachment.item;
								if (oItem instanceof Message) {
									log.info("Got the message form ItemAttachment "+message.id);
									Message mItem = (Message) oItem;
									AttachmentCollectionPage embededAttachments = mItem.attachments;
									for (Attachment embededAttachment : embededAttachments.getCurrentPage()) {
										i++;
										if (embededAttachment instanceof FileAttachment) {
											log.info("Got the Embedded attachment "+embededAttachment.id);
											saveFileAttachment(message.id, i, embededAttachment, dataAttachments);
										}
									}
								}									
							}

**Comment by mahendrabaghel** [comment]
Microsoft needs to seriously invest on better documentation, especially for Java. You will find lot more JavaMail users struggling with new oAuth and Graph API's.
