### ISSUE TITLE
Proguard Issue with MS Graph SDK

### ISSUE THREAD

**Issue by shubhamgarg1** [microsoftgraph/msgraph-sdk-java#1341]
Hi, we are facing an issue in using AGP 7.4.0 in an Android Project with the SDK. This is not happening with AGP 7.2.2.
We are getting this error on our release build when we enable Obfuscation with Proguard on calling the `client.me().drive().buildRequest().get()` API

```
com.microsoft.graph.core.ClientException: Error during http request
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
                                                                                                    	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
                                                                                                    	at com.microsoft.graph.requests.extensions.DriveRequest.get(DriveRequest.java:59)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation$operate$2.invokeSuspend(CNOneDriveGetDriveIdOperation.kt:58)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation$operate$2.invoke(CNOneDriveGetDriveIdOperation.kt:0)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation$operate$2.invoke(CNOneDriveGetDriveIdOperation.kt:0)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation.operate(CNOneDriveGetDriveIdOperation.kt:57)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveFetchListOperation.provisionDriveIfApplicable(CNOneDriveFetchListOperation.kt:156)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveFetchListOperation.access$provisionDriveIfApplicable(CNOneDriveFetchListOperation.kt:50)
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveFetchListOperation$operate$2.invokeSuspend(CNOneDriveFetchListOperation.kt:79)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.graph.serializer.AdditionalDataManager.setAdditionalData(com.google.gson.JsonObject)' on a null object reference
                                                                                                    	at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:181)
                                                                                                    	at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:182)
                                                                                                    	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:103)
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:532)
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:448)
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220) 
                                                                                                    	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200) 
                                                                                                    	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345) 
                                                                                                    	at com.microsoft.graph.requests.extensions.DriveRequest.get(DriveRequest.java:59) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation$operate$2.invokeSuspend(CNOneDriveGetDriveIdOperation.kt:58) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation$operate$2.invoke(CNOneDriveGetDriveIdOperation.kt:0) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation$operate$2.invoke(CNOneDriveGetDriveIdOperation.kt:0) 
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) 
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166) 
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveGetDriveIdOperation.operate(CNOneDriveGetDriveIdOperation.kt:57) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveFetchListOperation.provisionDriveIfApplicable(CNOneDriveFetchListOperation.kt:156) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveFetchListOperation.access$provisionDriveIfApplicable(CNOneDriveFetchListOperation.kt:50) 
                                                                                                    	at com.adobe.libs.connectors.oneDrive.operations.CNOneDriveFetchListOperation$operate$2.invokeSuspend(CNOneDriveFetchListOperation.kt:79) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) 
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) 
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) 

```

We are using MS Graph SDK version of 2.10.0. Would updating to the latest version of MS Graph SDK help fix this issue?

**Comment by ramsessanchez** [comment]
Hi @shubhamgarg1 , I do believe upgrading to the latest version would be the ideal solution. We are currently on version 5+ so there would be little to no support for version 2 unfortunately. There will likely be quite a bit of refactoring though I anticipate this will be helpful in the long run as it will allow us to better support you should you run into issues later on. Let us know if you run into any issues while upgrading. Thanks for using the SDK.
