### ISSUE TITLE
UploadSession for LargeFileUpload throws com.microsoft.graph.core.ClientException: Error while executing the request  for files more than 20GB

### ISSUE THREAD

**Issue by pvn04** [microsoftgraph/msgraph-sdk-java#1388]
### Expected behavior

https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=java

### Actual behavior

Caused by: java.util.concurrent.ExecutionException: com.microsoft.graph.core.ClientException: Upload session failed.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_352]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_352]
        at com.microsoft.graph.tasks.LargeFileUploadTask.upload(LargeFileUploadTask.java:253) ~[microsoft-graph-core-2.0.0.jar:?]
        ... 16 more
Caused by: com.microsoft.graph.core.ClientException: Upload session failed.
        at com.microsoft.graph.tasks.LargeFileUploadRequest.upload(LargeFileUploadRequest.java:107) ~[microsoft-graph-core-2.0.0.jar:?]
        at com.microsoft.graph.tasks.LargeFileUploadTask.uploadAsync(LargeFileUploadTask.java:165) ~[microsoft-graph-core-2.0.0.jar:?]
        at com.microsoft.graph.tasks.LargeFileUploadTask.upload(LargeFileUploadTask.java:253) ~[microsoft-graph-core-2.0.0.jar:?]
        ... 16 more
Caused by: com.microsoft.graph.core.ClientException: Error code: invalidRequest
Error message: The Content-Range header is missing or malformed.

### Steps to reproduce the behavior
until 10 gb it works fine  
upload more than 20gb file using upload session 

Library used : microsoft-graph-core-2.0.0.jar

Code:

AdditionalDataManager additionalDataManager = driveItemUploadableProperties.additionalDataManager();
			additionalDataManager.put("@microsoft.graph.conflictBehavior", new JsonPrimitive("replace"));
		
			logger.debug(path+"...graph api file upload started fail if conflict happens... "+encodedFileName);
			DriveItemCreateUploadSessionParameterSet createUploadSessionParameterSet = new DriveItemCreateUploadSessionParameterSet();
			createUploadSessionParameterSet.item=driveItemUploadableProperties;
			UploadSession uploadSession = pbdrive1.root().itemWithPath(path + "/" + encodedFileName)
					.createUploadSession(createUploadSessionParameterSet).buildRequest().post();
			
			LargeFileUploadTask<DriveItem> largeFileUploadTask = new LargeFileUploadTask<DriveItem>(uploadSession,
					graphClient, inputStream, fileSize, DriveItem.class);

			// Do the upload
			largeFileUploadTask.upload(10 * 320 * 1024, null, callback);

**Comment by andrueastman** [comment]
Thanks for raising this @pvn04 

Any chance you can share logs from your callback function to identify if this fails consistently at a certain value? For some reason it looks like there is an issue with the Content-Range header.

```
Error message: The Content-Range header is missing or malformed.
```

**Comment by pvn04** [comment]
IProgressCallback callback = new IProgressCallback() {
				
				@Override
				public void progress(long current, long max) {
					// TODO Auto-generated method stub
					 logger.debug(
					            String.format("Uploaded %d bytes of %d total bytes", current, max)
					        );
				}
			};

This is the call back function i am using, but i am not getting any specific logs for it

**Comment by pvn04** [comment]
[ERROR] 06/04/2023 14:22:26 [c2cupload-$$0$$] [(GraphUploadServiceImpl:386)] Grpagh service exception:
com.microsoft.graph.core.ClientException: Error while executing the request
        at com.microsoft.graph.tasks.LargeFileUploadTask.upload(LargeFileUploadTask.java:257) ~[microsoft-graph-core-2.0.0.jar:?]
        at com.pg.service.impl.GraphUploadServiceImpl.uploadGraph(GraphUploadServiceImpl.java:370) ~[blukrypt-services-pcibus-2.2.jar:?]
        at com.pg.service.impl.GraphUploadServiceImpl.uploadToOneDriveUsingGraph(GraphUploadServiceImpl.java:1827) ~[blukrypt-services-pcibus-2.2.jar:?]
        at com.pg.odb.util.OneDriveUtil.uploadToOneDriveUsingGraph(OneDriveUtil.java:755) ~[blukrypt-services-pcibus-2.2.jar:?]
        at com.pg.service.impl.CloudSupportServiceImpl.uploadToOneDrive(CloudSupportServiceImpl.java:2772) ~[blukrypt-services-pcibus-2.2.jar:?]
        at com.pg.sync.service.impl.SyncDownloadServiceImpl.inplaceOnedriveUpload(SyncDownloadServiceImpl.java:4668) ~[blukrypt-services-pcibus-2.2.jar:?]
        at com.pg.sync.service.impl.SyncDownloadServiceImpl.lambda$inPlaceRestoreForOndriveFromCloud$7(SyncDownloadServiceImpl.java:4506) ~[blukrypt-services-pcibus-2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.util.concurrent.ExecutionException: com.microsoft.graph.core.ClientException: Upload session failed.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_352]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_352]
        at com.microsoft.graph.tasks.LargeFileUploadTask.upload(LargeFileUploadTask.java:253) ~[microsoft-graph-core-2.0.0.jar:?]
        ... 13 more
Caused by: com.microsoft.graph.core.ClientException: Upload session failed.
        at com.microsoft.graph.tasks.LargeFileUploadRequest.upload(LargeFileUploadRequest.java:107) ~[microsoft-graph-core-2.0.0.jar:?]
        at com.microsoft.graph.tasks.LargeFileUploadTask.uploadAsync(LargeFileUploadTask.java:165) ~[microsoft-graph-core-2.0.0.jar:?]
        at com.microsoft.graph.tasks.LargeFileUploadTask.upload(LargeFileUploadTask.java:253) ~[microsoft-graph-core-2.0.0.jar:?]
        ... 13 more
Caused by: com.microsoft.graph.core.ClientException: Error code: invalidRequest
Error message: The Content-Range header is missing or malformed.

 

PUT https://parablusys-my.sharepoint.com/personal/karthick_parablu_com/_api/v2.0/drives/b!mV6aoUUke0aEiXNMkCW52rNKqpvAwtRPsbBnAAjdP4W9E2zp97DtQ6wlewLNCqY1/items/01ADIG7EQCAYQ4TNGWCRAI5NMVGZE4HLUL/uploadSession?guid=%27fceab440-c413-4a69-9d60-e8cdc4f9d9e5%27&overwrite=True&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvcGFyYWJsdXN5cy1teS5zaGFyZXBvaW50LmNvbUBhNTMzMjljNi01ODJmLTQ4ZTUtYjI4Ni0xNWU2YmNjNjU4YjAiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjgwNzcwNzIyIiwiZXhwIjoiMTY4MDg1NzEyMiIsImVuZHBvaW50dXJsIjoiUFFhTnlzTXVJcWoybWIwVnZQNHA2K25PcjRwcHhZZEVBUlNVY1l1bVB2az0iLCJlbmRwb2ludHVybExlbmd0aCI6IjI4MiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiWmpVeE5XVTBOVGd0T1RnM05TMDBPV05rTFdJMU5qa3RZamc0WkRsallUQXdNemRoIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IllURTVZVFZsT1RrdE1qUTBOUzAwTmpkaUxUZzBPRGt0TnpNMFl6a3dNalZpT1dSaCIsImFwcF9kaXNwbGF5bmFtZSI6IlByb2QgLSBQYXJhYmx1IEluYyAtIFMtRXhjaGFuZ2UtT25lRHJpdmUgLSBELU9ENEIiLCJuYW1laWQiOiJhZGViNTMyYy05NzM5LTQ3ZjktYjNhZC1mYWJmM2FjOWE2ZDFAYTUzMzI5YzYtNTgyZi00OGU1LWIyODYtMTVlNmJjYzY1OGIwIiwicm9sZXMiOiJhbGxzaXRlcy53cml0ZSBncm91cC53cml0ZSBhbGxmaWxlcy53cml0ZSBhbGxzaXRlcy5mdWxsY29udHJvbCBhbGxwcm9maWxlcy5yZWFkIiwidHQiOiIxIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbCwiaXBhZGRyIjoiMjAuMTkwLjE0NS4xNzEifQ.UU9jZWZybWhScUtEdkNRNEludUxRc0FKN1lYR3N5T2lKZ2lQRTB5WWpudz0
SdkVersion : graph-java/v3.2.0
**Content-Range : bytes 2146304000-2149580799/214748[...]**

 


400 : Bad Request

**Comment by pvn04** [comment]
something to do with content range is not being set can you guys help us with setting the content range header

**Comment by ramsessanchez** [comment]
From the looks of it seems the total length is smaller than the content range bytes. Cannot be sure but it looks like you are uploading bytes 21463040000-2149580799/214748... which suggests the total length is less than the final length. I believe this was fixed in a later version of the largeFileUploadTask since it seems you are currently using 2.0.0. My suggestion is to upgrade the SDK version 5+ which will make use of a more recent java-core library. The alternative would be to manually import version 2.0.18 into your dependencies, 
"implementation 'com.microsoft.graph:microsoft-graph-core:2.0.16'"
this may be incompatible with v3.2.0 of the SDK however. I recommend trying to update the core library first and then update the SDK itself if necessary.
