### ISSUE TITLE
SDK parsing the SharePoint/OneDrive delta endpoint response JSON has suddenly started to fail

### ISSUE THREAD

**Issue by raniemi** [microsoftgraph/msgraph-sdk-java#1528]
### Expected behavior

For the `https://graph.microsoft.com/v1.0/sites/XXX/lists/YYY/drive/root/microsoft.graph.delta` to either return the data that the SDK expects or for the SDK to be updated to accommodate any recent changes to the JSON returned by the `graph.microsoft.com` server.

### Actual behavior

Sometime this morning (August 8, 2023 ~8:50 CST) all my servers that use the `https://graph.microsoft.com/v1.0/sites/XXX/lists/YYY/drive/root/microsoft.graph.delta` endpoint started to fail when the `msgraph-sdk-java` client was parsing the returned JSON from Microsoft Graph.  

Other interesting tidbits:

* This was observed for several different sharepoint.com sites and with several different user accounts.  
* The problem persists with versions `5.64.0` and `5.66.0` of the `msgraph-sdk-java`.
* It doesn't appear that any more details gets logged when the log level is set to `DEBUG`
* As far as I can tell with Charles proxy, the JSON "looks" fine (i.e. I was in a rush and I didn't see any values with empty strings). 
    * Is there a quick/dirty way for me to have the `msgraph-sdk-java` (as standalone) consume said JSON and isolate the problem area?  Alternatively, if the exception could also include the path in the JSON that is failing, that would make it easier for future issue submissions.

#### Exception (Truncated)

When calling the end point using the `msgraph-sdk-java` library:

```
com.microsoft.graph.core.ClientException: Error during http request
        at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:493)
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202)
        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:103)
        at com.microsoft.graph.http.BaseFunctionCollectionRequest.get(BaseFunctionCollectionRequest.java:79)
        at com.microsoft.graph.http.BaseFunctionCollectionRequest$get.call(Unknown Source)
...
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:228)
        at com.microsoft.graph.serializer.EdmNativeTypeSerializer.getPrimitiveValue(EdmNativeTypeSerializer.java:45)
        at com.microsoft.graph.serializer.EdmNativeTypeSerializer.deserialize(EdmNativeTypeSerializer.java:27)
        at com.microsoft.graph.serializer.GsonFactory.lambda$getGsonInstance$18(GsonFactory.java:209)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266)
        at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:292)
        at com.microsoft.graph.serializer.ODataTypeParametrizedIJsonBackedTypedAdapter.read(ODataTypeParametrizedIJsonBackedTypedAdapter.java:61)
        at com.microsoft.graph.serializer.ODataTypeParametrizedIJsonBackedTypedAdapter.read(ODataTypeParametrizedIJsonBackedTypedAdapter.java:22)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266)
        at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:292)
        at com.microsoft.graph.serializer.ODataTypeParametrizedIJsonBackedTypedAdapter.read(ODataTypeParametrizedIJsonBackedTypedAdapter.java:57)
        at com.microsoft.graph.serializer.ODataTypeParametrizedIJsonBackedTypedAdapter.read(ODataTypeParametrizedIJsonBackedTypedAdapter.java:22)
        at com.google.gson.Gson.fromJson(Gson.java:1058)
        at com.google.gson.Gson.fromJson(Gson.java:1129)
        at com.google.gson.Gson.fromJson(Gson.java:1101)
        at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:118)
        at com.microsoft.graph.serializer.ISerializer.deserializeObject(ISerializer.java:99)
        at com.microsoft.graph.serializer.CollectionResponseDeserializer.deserialize(CollectionResponseDeserializer.java:89)
        at com.microsoft.graph.serializer.GsonFactory.lambda$getGsonInstance$12(GsonFactory.java:191)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:1058)
        at com.google.gson.Gson.fromJson(Gson.java:1129)
        at com.google.gson.Gson.fromJson(Gson.java:1101)
        at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:118)
        at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:105)
        at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:536)
        at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:467)
        ... 158 common frames omitted
```

### Steps to reproduce the behavior

You should probably be able to reproduce it by using the [sample code](https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=java) from `learn.microsoft.com`

**Comment by rick-scio** [comment]
Just adding another data point, we noticed this occurring in our SDK invocations as well.

**Comment by raniemi** [comment]
I was away for a bit, but it looks like the endpoint started functioning properly again around August 9, 2023 at ~19:30 CST and ~19:50 CST (different sites, different server invocations).  I'll keep an eye on things this week.

**Comment by raniemi** [comment]
The endpoint is still continuing to function. Closing
