### ISSUE TITLE
Unable to acquire a token in Android SDK 33

### ISSUE THREAD

**Issue by abouquet** [microsoftgraph/msgraph-sdk-java#1540]
### Expected behavior
* Acquire a token successfuly

### Actual behavior
```
 Caused by: java.lang.ExceptionInInitializerError        	at com.azure.core.implementation.ReflectionUtils.getLookupToUse(ReflectionUtils.java:119)
                                                                                                    	at com.azure.core.util.ExpandableStringEnum.getDefaultConstructor(ExpandableStringEnum.java:88)
                                                                                                    	at com.azure.core.util.ExpandableStringEnum.$r8$lambda$SMtq8BJfA6t_qJk1WfhslLPTCwc(Unknown Source:0)
                                                                                                    	at com.azure.core.util.ExpandableStringEnum$$ExternalSyntheticLambda1.apply(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
                                                                                                    	at com.azure.core.util.ExpandableStringEnum.fromString(ExpandableStringEnum.java:68)
                                                                                                    	at com.azure.identity.implementation.RegionalAuthority.fromString(RegionalAuthority.java:287)
                                                                                                    	at com.azure.identity.implementation.RegionalAuthority.<clinit>(RegionalAuthority.java:19)
                                                                                                    	at com.azure.identity.implementation.RegionalAuthority.fromString(RegionalAuthority.java:287)
                                                                                                    	at com.azure.identity.implementation.IdentityClientOptions.<init>(IdentityClientOptions.java:93)
                                                                                                    	at com.azure.identity.CredentialBuilderBase.<init>(CredentialBuilderBase.java:35)
                                                                                                    	at com.azure.identity.AadCredentialBuilderBase.<init>(AadCredentialBuilderBase.java:21)
                                                                                                    	at com.azure.identity.ClientSecretCredentialBuilder.<init>(ClientSecretCredentialBuilder.java:70)
```

```
 Caused by: java.lang.RuntimeException: Unable to use package-private MethodHandles.Lookup constructor.
```

### Steps to reproduce the behavior

Use this code in an Android SDK 33 environnement (Compiled and targeted with Java 11)

```
class TokenManager {
    companion object {
        const val TENANT_ID: String = "<redacted>"
        const val CLIENT_ID: String = "<redacted>"
        const val CLIENT_SECRET: String = "<redacted>"
        @Throws(Exception::class)
        fun acquireToken(): TokenCredentialAuthProvider {
            val scopes: List<String> = mutableListOf("https://graph.microsoft.com/.default")

            val credential = ClientSecretCredentialBuilder()
                    .clientId(CLIENT_ID).tenantId(TENANT_ID).clientSecret(CLIENT_SECRET).build()
                    ?: throw java.lang.Exception("Unexpected error")
            return TokenCredentialAuthProvider(
                    scopes, credential)
        }
    }
}
```

Dependencies are declared with the following line on `app/build.gradle`

```groovy
    // https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph
    implementation ('com.microsoft.graph:microsoft-graph:5.68.0'){
        exclude group:'com.google.guava'
    }
    // https://mvnrepository.com/artifact/com.azure/azure-identity
    implementation ('com.azure:azure-identity:1.10.0') {
        // already imported in this project, duplicated classes otherwise
        exclude group:'net.java.dev.jna'
    }
```

**Comment by abouquet** [comment]
Ok, I just link this issue to https://github.com/Azure/azure-sdk-for-java/issues/35719 for other people.
There is a similar one here
