### ISSUE TITLE
Error : com.microsoft.graph.requests.MessageCollectionRequest

### ISSUE THREAD

**Issue by rajputashu** [microsoftgraph/msgraph-sdk-java#1563]
**_I am getting below error_**

```
com.microsoft.graph.core.ClientException: Could not find the required class
	at com.microsoft.graph.http.BaseCollectionRequestBuilder.buildRequest(BaseCollectionRequestBuilder.java:66)
	at com.microsoft.graph.http.BaseCollectionRequestBuilder.buildRequest(BaseCollectionRequestBuilder.java:51)
	at com.sisindia.salesmaxx.features.email.EmailDashboardViewModel$getInboxMails$1.invokeSuspend(EmailDashboardViewModel.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NoSuchMethodException: com.microsoft.graph.requests.MessageCollectionRequest.<init> [class java.lang.String, interface com.microsoft.graph.core.IBaseClient, interface java.util.List]
```

**PFB code snippet Android Kotlin (To get Mails of user)**

         val authProvider = IAuthenticationProvider {
            CompletableFuture.supplyAsync { preference.preAuthToken }
        }

        viewModelScope.launch(Dispatchers.IO + mailHandler) {
            val graphClient =
                GraphServiceClient.builder().authenticationProvider(authProvider).buildClient()
            val response = graphClient.me()
                .messages()
                **.buildRequest()**  // Getting error in this line
                .top(top)
                .skip(skipCount)
                .filter("isRead ne true")
                .select("subject,from,receivedDateTime,body,toRecipients")
                .orderBy("receivedDateTime DESC").get()

**Dependencies used in build.gradle** 
```
//Microsoft Authentication and GraphAPIs
    implementation 'com.microsoft.identity.client:msal:4.5.0'
//    implementation('com.microsoft.graph:microsoft-graph:5.59.0') {At time of development it was working fine, now its not working}
    implementation('com.microsoft.graph:microsoft-graph:5.70.0')
    implementation 'com.google.guava:guava:30.1.1-android'
```

In Debug build (getting response from graph SDK)
As soon as creating build for release or production above code causing problem

**Comment by ramsessanchez** [comment]
Hi @rajputashu , For the latest version of the graph-sdk we recommend using azure identity for authentication over msal. Would you mind removing the msal dependency and migrating over to azure identity if possible. Also, it seems that your filter parameter and orderby parameters could be conflicting and the error message may not be as clear. Check here: https://learn.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http#using-filter-and-orderby-in-the-same-query
