### ISSUE TITLE
NullPointerException decoding PlannerChecklistItem

### ISSUE THREAD

**Issue by klehmann** [microsoftgraph/msgraph-sdk-java#160]
We are trying to read MS Planner plans details and check list items via graph API and get a NullPointerException.

### Expected behavior
PlannerChecklistItem can be decoded properly.

### Actual behavior
Code throws NullPointerException.

### Steps to reproduce the behavior
Create an MS Planner plan and add a task with a checklist item.

Use getGroups to read all groups:

```java
	public static List<Group> getGroups(IGraphServiceClient graphAPI) {
		List<Group> allGroups = new ArrayList<>();
		
		IGroupCollectionRequest groupsReq = graphAPI.groups().buildRequest();
		IGroupCollectionPage currGroupPage;
		do {
			currGroupPage = groupsReq.get();
			
			List<Group> groupsInPage = currGroupPage.getCurrentPage();
			allGroups.addAll(groupsInPage);
			
			IGroupCollectionRequestBuilder nextPageReq = currGroupPage.getNextPage();
			if (nextPageReq==null) {
				break;
			}
			else {
				groupsReq = nextPageReq.buildRequest();
			}
		}
		while (true);
		
		return allGroups;
	}
```

Find the group corresponding to the plan and use getPlansForGroup to read the plan:

```java
	public static List<PlannerPlan> getPlansForGroup(IGraphServiceClient graphAPI, Group group) {
		List<PlannerPlan> allPlans = new ArrayList<>();
		
		IPlannerPlanCollectionRequest plansReq = graphAPI.groups(group.id).planner().plans().buildRequest();
		IPlannerPlanCollectionPage currPlanPage;
		do {
			currPlanPage = plansReq.get();
			List<PlannerPlan> plansForPage = currPlanPage.getCurrentPage();
			
			for (PlannerPlan currPlan : plansForPage) {
				allPlans.add(currPlan);
			}
		
			IPlannerPlanCollectionRequestBuilder nextPageReq = currPlanPage.getNextPage();
			if (nextPageReq==null) {
				break;
			}
			else {
				plansReq = nextPageReq.buildRequest();
			}
		}
		while (true);
		
		return allPlans;
	}
```

For the returned plan, call getTasksForPlan to get all the tasks:

```java
	public static List<PlannerTask> getTasksForPlan(IGraphServiceClient graphAPI, PlannerPlan plan) {
		List<PlannerTask> allTasks = new ArrayList<>();
		
		IPlannerTaskCollectionPage tasksPage = graphAPI.planner().plans(plan.id).tasks().buildRequest().get();
		do {
			List<PlannerTask> tasksInPage = tasksPage.getCurrentPage();
			allTasks.addAll(tasksInPage);
			
			IPlannerTaskCollectionRequestBuilder taskReqBuilder = tasksPage.getNextPage();
			if (taskReqBuilder==null) {
				break;
			}
			else {
				tasksPage = taskReqBuilder.buildRequest().get();
			}
		}
		while (true);
		
		return allTasks;
	}
```
Now try to read the task details:

```java

	public static PlannerTaskDetails getTaskDetails(IGraphServiceClient graphAPI, PlannerTask task) {
		PlannerTaskDetails details = graphAPI.planner().tasks(task.id).details().buildRequest().get();
		return details;
	}

```

This returns JSON data looks like this:

```json
{
	"references": {},
	"@odata.etag": "W/\"JzEtVGFza0RldGFpbHMgQEBAQEBAQEBAQEBAQEBAUCc=\"",
	"description": null,
	"checklist": {
		"42660": {
			"lastModifiedDateTime": "2018-10-28T14:29:37.7423391Z",
			"@odata.type": "#microsoft.graph.plannerChecklistItem",
			"orderHint": "8586608699726429822PK",
			"lastModifiedBy": {
				"user": {
					"displayName": null,
					"id": "f3a1dfe8-f2ef-4870-9642-413d468c571c"
				}
			},
			"title": "Ein Checklisteneintrag",
			"isChecked": false
		}
	},
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#planner/tasks('C6iIn6oJcEGcLX5XAiKeCZcAOv30')/details/$entity",
	"previewType": "automatic",
	"id": "C6iIn6oJcEGcLX5XAiKeCZcAOv30"
}
```

Deserialization to PlannerTaskDetails fails, because the JSON structure does not match the fields in PlannerChecklistItems. 

```
Caused by: java.lang.NullPointerException
	at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:147)
	at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:138)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:103)
```

The reason is that the deserializer tried to read a value for public com.microsoft.graph.models.extensions.IdentitySet com.microsoft.graph.models.generated.BasePlannerChecklistItem.lastModifiedBy in this rawJson value (where only key "42660" exists):

```json
{"42660":{"lastModifiedDateTime":"2018-10-28T14:29:37.7423391Z","@odata.type":"#microsoft.graph.plannerChecklistItem","orderHint":"8586608699726429822PK","lastModifiedBy":{"user":{"displayName":"","id":"f3a1dfe8-f2ef-4870-9642-413d468c571c"}},"title":"Ein Checklisteneintrag","isChecked":false}}
```

**Comment by klehmann** [comment]
Worked around the issue by using a custom serializer where I added null checks for rawJson.get(field.getName()) and outJson.get(field.getName()) like this:

```java
      // If the object is a valid Graph object, set its additional data
      else if (fieldObject != null && fieldObject instanceof IJsonBackedObject) {
          IJsonBackedObject serializedChild = (IJsonBackedObject) fieldObject;

          JsonElement rawJsonEl = rawJson.get(field.getName());
          if (rawJsonEl!=null) {
              setAdditionalData(serializedChild, rawJsonEl.getAsJsonObject());
              setChildAdditionalData((IJsonBackedObject) fieldObject,rawJsonEl.getAsJsonObject());
          }
      }
```

```java
	// If the object is a valid Graph object, add its additional data
	else if (fieldObject != null && fieldObject instanceof IJsonBackedObject) {
		IJsonBackedObject serializableChild = (IJsonBackedObject) fieldObject;
		AdditionalDataManager childAdditionalData = serializableChild.additionalDataManager();

		JsonElement outJsonEl = outJson.get(field.getName());
		if (outJsonEl!=null) {
			addAdditionalDataToJson(childAdditionalData, outJsonEl.getAsJsonObject());
		}
            		
       		// Serialize its children
       		outJson = getChildAdditionalData(serializableChild, outJson);
	} 
```

**Comment by J0s3f** [comment]
We have exactly the same NullPointerException when fetching ListItem from Drive

`            fileMetadata = graphClient.drives(driveId).items(item.id).listItem().buildRequest().get();`

**Comment by hg64** [comment]
Is there an update on this? We also have this problem:

DriveItem driveItem = graphServiceClient
    		.groups(groupId)
                .drive()
                .root()
                .itemWithPath(id + ".docx")
                .content()
                .buildRequest()
                .put(t_out.toByteArray());

**Comment by hg64** [comment]
getting the same error on most methods it seems.....

Caused by: java.lang.NullPointerException
at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:147)

when executing

graphServiceClient
        		.groups(groupId)
        		.drive()
                .root()
                .itemWithPath(p_filename)
        		.createLink("edit", "organization")
        		.buildRequest()
        		.post()
        		.link
        		.webUrl;

**Comment by hg64** [comment]
Thank you Deepak. Still getting the nullpointer on
"com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData("
but it seems that operations succeed anyway so not a big problem mostly.
However, we are pretty much stuck when we need to get details back from the
API - see the below example, this always ends up in the failure method. I
can see through the user interface that the SharedLink has been created but
because of the issue we cant get at it through the API? Could you suggest a
work around or have we done something wrong?

Thanks!

     IDriveItemCreateLinkRequest t_req =
    graphServiceClient
        .groups(groupId)
        .drive()
                .root()
                .itemWithPath(p_filename)
        .createLink("edit", "organization")
        .buildRequest();
    t_req.post(new ICallback<Permission>() {
                    @Override
                    public void success(final Permission result) {
                        String t_url = result.link.webUrl;
                        try {
                           p_response.sendRedirect(t_url);
                           } catch (IOException e) {
                           rq.logGeneralException(e);
                               }
                        }
@Override
public void failure(ClientException e) {
rq.logGeneralException(e);
    }
                    });


Hans Grefte
Product Manager iCasework
+44 (0) 020 3053 6103
+44 (0) 7870 988 881

http://www.usefulfeedback.com
<http://www.usefulfeedback.com/>
http://www.icasework.com
https://www.civica.com

**Comment by NakulSabharwal** [comment]
@hg64 Could you please give full error stack trace and also tell what is the visibility of group you are trying to access using 
`graphClient.groups(group.id).buildRequest().get().getRawObject();` or `graphClient.groups(group.id).buildRequest().get().visibility;`

**Comment by hg64** [comment]
Hi there

Even a get using " graphClient.groups(group.id).buildRequest().get().
getRawObject(); " returns an authorisation error - see below.. Basically I
cant get anything back from the api.

Cheers
Hans

04-Dec-2018 17:33:25.331 INFO [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logDebug Starting to send request,
URL
https://graph.microsoft.com/v1.0/groups/520559ee-2d6e-4b01-810d-b3f93afbaf67
04-Dec-2018 17:33:25.331 INFO [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logDebug Request Method GET
04-Dec-2018 17:33:25.435 INFO [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logDebug Response code 403,
Forbidden
04-Dec-2018 17:33:25.435 INFO [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logDebug Handling error response
04-Dec-2018 17:33:25.438 INFO [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logDebug Deserializing type
GraphErrorResponse
04-Dec-2018 17:33:25.439 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197Graph service exception Error code: Authorization_RequestDenied
04-Dec-2018 17:33:25.439 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197Error message: Insufficient privileges to complete the operation.
04-Dec-2018 17:33:25.439 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197
04-Dec-2018 17:33:25.440 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197GET
https://graph.microsoft.com/v1.0/groups/520559ee-2d6e-4b01-810d-b3f93afbaf67
04-Dec-2018 17:33:25.440 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197SdkVersion : graph-java-v1.0.1
04-Dec-2018 17:33:25.440 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]
04-Dec-2018 17:33:25.440 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197
04-Dec-2018 17:33:25.441 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197
04-Dec-2018 17:33:25.441 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197403 : Forbidden
04-Dec-2018 17:33:25.441 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197[...]
04-Dec-2018 17:33:25.441 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197
04-Dec-2018 17:33:25.442 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError DefaultHttpProvider[send]
- 197[Some information was truncated for brevity, enable debug logging for
more details]
04-Dec-2018 17:33:25.442 SEVERE [http-nio-8080-exec-10]
com.microsoft.graph.logger.DefaultLogger.logError Throwable detail:
com.microsoft.graph.http.GraphServiceException: Error code:
Authorization_RequestDenied
Error message: Insufficient privileges to complete the operation.
GET
https://graph.microsoft.com/v1.0/groups/520559ee-2d6e-4b01-810d-b3f93afbaf67
SdkVersion : graph-java-v1.0.1
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]

403 : Forbidden
[...]
[Some information was truncated for brevity, enable debug logging for more
details]
04-Dec-2018 17:33:25.442 SEVERE [http-nio-8080-exec-10]
org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for
servlet [servlets.run] in context with path [] threw exception
com.microsoft.graph.http.GraphServiceException: Error code:
Authorization_RequestDenied
Error message: Insufficient privileges to complete the operation.
GET
https://graph.microsoft.com/v1.0/groups/520559ee-2d6e-4b01-810d-b3f93afbaf67
SdkVersion : graph-java-v1.0.1
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]

403 : Forbidden
[...]
[Some information was truncated for brevity, enable debug logging for more
details]
at
com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:339)
at
com.microsoft.graph.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:376)
at
com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:309)
at
com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:197)
at
com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:177)
at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:277)
at
com.microsoft.graph.requests.generated.BaseGroupRequest.get(BaseGroupRequest.java:56)
at tools.GraphTools.setFileURL(GraphTools.java:142)
at tools.GraphTools.uploadLetter(GraphTools.java:60)
at servlets.run.service(run.java:270)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at utils.TranslationFilter.doFilter(TranslationFilter.java:115)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at utils.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:342)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at utils.BadInputFilter.doFilter(BadInputFilter.java:45)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at
org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1223)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
at
org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:542)
at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
at
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
at
org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
at
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)


Hans Grefte
Product Manager iCasework
+44 (0) 020 3053 6103
+44 (0) 7870 988 881

http://www.usefulfeedback.com
<http://www.usefulfeedback.com/>
http://www.icasework.com
https://www.civica.com

**Comment by NakulSabharwal** [comment]
@hg64 This seems to be problem of permissions( https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0 ). Could you follow these steps for troubleshooting- 

1. goto https://developer.microsoft.com/en-us/graph/graph-explorer#
2. Login with the account you are using to make api call
3. make a GET call to https://graph.microsoft.com/v1.0/groups/520559ee-2d6e-4b01-810d-b3f93afbaf67 and tells whats the result
4. goto modify permissions( top-left) and check if you have Group.ReadWrite.All permission granted or not.

**Comment by NakulSabharwal** [comment]
@hg64 Hi, if you are getting errors even after assigning required permission to your application using [Application registration portal](https://apps.dev.microsoft.com/?referrer=https://azure.microsoft.com/documentation/articles&deeplink=/appList) then please make a new issue and we will look into it. Thanks.

**Comment by hg64** [comment]
Hi there, noticed that my personal details are published publicly on this thread - please can you remove them asap? thks
