### ISSUE TITLE
 java.lang.IllegalStateException: null being thrown in deserialization when fetching file permissions

### ISSUE THREAD

**Issue by westleyMS** [microsoftgraph/msgraph-sdk-java#1674]
When getting permissions on files via the Graph SDK, we occasionally see this deserialization error-

c.m.c.p.s.creaters.AbstractCreator : Error during http request
    com.microsoft.graph.core.ClientException: Error during http request
    at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:483)
    at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:396)
    at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:222)
    at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:199)
    at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:102)
    at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
    at com.metricinsights.collector.plugin.sharepoint.MiGraphServiceClient.getListItemsFromPage(MiGraphServiceClient.java:856)
    at com.metricinsights.collector.plugin.sharepoint.MiGraphServiceClient.getItemsFromPage(MiGraphServiceClient.java:584)
    at com.metricinsights.collector.plugin.sharepoint.MiGraphServiceClient.getMiItemsForPermissions(MiGraphServiceClient.java:277)
    at com.metricinsights.collector.plugin.sharepoint.entities.MiList.getMiItemsForPermissions(MiList.java:55)
    at com.metricinsights.collector.plugin.sharepoint.readers.UserAccessSharepointMiReader.getItemsWithSpecificFields(UserAccessSharepointMiReader.java:33)
    at com.metricinsights.collector.plugin.sharepoint.readers.SharepointMiReader.getMiItems(SharepointMiReader.java:79)
    at com.metricinsights.collector.plugin.sharepoint.readers.PersonalAccessSharepointMiReader.readAll(PersonalAccessSharepointMiReader.java:27)
    at com.metricinsights.collector.plugin.sharepoint.SharepointClient.queryResponseForUsers(SharepointClient.java:312)
    at com.metricinsights.collector.plugin.sharepoint.SharepointClient.getDataFromSource(SharepointClient.java:157)
    at com.metricinsights.collector.plugin.sharepoint.SharepointPlugin.getDataFromSource(SharepointPlugin.java:90)
    at com.metricinsights.collector.plugin.sharepoint.SharepointPlugin.getDataFromSource(SharepointPlugin.java:26)
    at com.metricinsights.collector.plugin.pluginterface2.MIPlugin.getDataStream(MIPlugin.java:341)
    at com.metricinsights.collector.plugin.pluginterface2.RequestDispatcher.dispatch(RequestDispatcher.java:52)
    at com.metricinsights.datacollector.PluginJobExecutor.getDataCollectorResponse(PluginJobExecutor.java:50)
    at com.metricinsights.datacollector.LocalPluginJobExecutor.execute(LocalPluginJobExecutor.java:78)
    at com.metricinsights.datacollector.LocalPluginJobExecutor.lambda$executeAsync$0(LocalPluginJobExecutor.java:70)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
    at com.google.gson.Gson.fromJson(Gson.java:963)
    at com.google.gson.Gson.fromJson(Gson.java:1034)
    at com.google.gson.Gson.fromJson(Gson.java:1006)
    at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:101)
    at com.microsoft.graph.serializer.ISerializer.deserializeObject(ISerializer.java:99)
    at com.microsoft.graph.serializer.CollectionResponseSerializer.deserialize(CollectionResponseSerializer.java:97)
    at com.microsoft.graph.serializer.GsonFactory$13.deserialize(GsonFactory.java:242)
    at com.microsoft.graph.serializer.GsonFactory$13.deserialize(GsonFactory.java:237)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at com.google.gson.Gson.fromJson(Gson.java:963)
    at com.google.gson.Gson.fromJson(Gson.java:1034)
    at com.google.gson.Gson.fromJson(Gson.java:1006)
    at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:101)
    at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:88)
    at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:527)
    at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:455)
                ... 26 common frames omitted
Caused by: java.lang.IllegalStateException: null
    at com.google.gson.Gson$FutureTypeAdapter.read(Gson.java:1049)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
                ... 42 common frames omitted

We are using version 4.0.0 of the Java graph SDK and this error happens occasionally, and we haven't been able to see what is causing it.
We did find similar issues mentioned here-
[https://github.com/microsoftgraph/msgraph-sdk-java/issues/495](https://github.com/microsoftgraph/msgraph-sdk-java/issues/495)
[https://github.com/microsoftgraph/msgraph-sdk-java/issues/651](https://github.com/microsoftgraph/msgraph-sdk-java/issues/651)

These were built on older versions of the SDK, but the deserialization error seems to be very close to what we experienced.

### Expected behavior
Serialization works and the code doesn't throw the java.lang.IllegalStateException: null

### Actual behavior
Code throws java.lang.IllegalStateException: null

### Steps to reproduce the behavior
Running code that pulls the permissions for files via the Graph SDK, this reproduces sometimes (intermittent).

**Comment by baywet** [comment]
Hi @westleyMS 
Thanks for using the SDK and for reaching out.
V4 of the SDK is not supported anymore.
Please upgrade the the latest version (5.77 at the time of writing) and let us know if you still experience the same issue.

**Comment by westleyMS** [comment]
Already upgrading, but not sure if that will fix the issue. We wanted to know if this was something fixed in the newer version.

**Comment by baywet** [comment]
As you can see [at lot has changed between v4 and 5.77](https://github.com/microsoftgraph/msgraph-sdk-java/compare/4.0.0...v5.77.0) and the issues you've mentioned have been addressed. I'm not sure yet whether your specific scenario is a different issue or not.
