### ISSUE TITLE
Inconsistency when filtering teams and channels

### ISSUE THREAD

**Issue by denstren** [microsoftgraph/msgraph-sdk-java#1731]
### Expected behavior
I am filtering the displayName for both teams and channels and trying to use the same method/syntax for both.
From what I have read it appears when checking for equality using the eq operator filters are case sensitive.
I am using version 5.77.0 of the SDK.

### Actual behavior
But, after trial and error it doesn't appear that I can filter both the same way.

It appears the displayName of teams are not case sensitive when filtering using the eq operator.
And the displayName of channels are case sensitive when filtering using the eq operator.

### Steps to reproduce the behavior
When filtering the teams I get the same result whether or not I use lower or upper case values.
Both code snippets below match the actual team name of "MyTeam"
```
TeamCollectionPage joinedTeamsPage = graphClient.teams()
		.buildRequest()
		.select("id,displayName,description")
		.filter("displayName eq 'myteam'")
		.get();

TeamCollectionPage joinedTeamsPage = graphClient.teams()
		.buildRequest()
		.select("id,displayName,description")
		.filter("displayName eq 'MYTEAM'")
		.get();

```

But, when filtering the channels of the team neither of the following code snippets match the General channel.
```
ChannelCollectionPage channelsPage = graphClient.teams(teamId).channels()
		.buildRequest()
		.select("id,displayName,description")
		.filter("displayName eq 'general'")
		.get();

ChannelCollectionPage channelsPage = graphClient.teams(teamId).channels()
		.buildRequest()
		.select("id,displayName,description")
		.filter("displayName eq 'GENERAL'")
		.get();
```

I got it to work using the following code snippet using the tolower function.
```
ChannelCollectionPage channelsPage = graphClient.teams(teamId).channels()
		.buildRequest()
		.select("id,displayName,description")
		.filter("tolower(displayName) eq 'general'")
		.get();
```

But, if I try to do the same when filtering the teams.
```
TeamCollectionPage joinedTeamsPage = graphClient.teams()
		.buildRequest()
		.select("id,displayName,description")
		.filter("tolower(displayName) eq 'myteam'")
		.get();
```

I get the following error.

com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: Invalid expression caused by operator 'EqualsMatch'.

GET https://graph.microsoft.com/v1.0/teams?%24select=id%2CdisplayName%2Cdescription&%24filter=tolower%28displayName%29%20eq%20%27myteam%27
SdkVersion : graph-java/v5.77.0

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:510) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:442) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:103) ~[microsoft-graph-core-2.0.21.jar:na]
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78) ~[microsoft-graph-core-2.0.21.jar:na]

Should the teams be case sensitive like the channels?
Or is this the expected behavior?

Let me know if you have any questions.

Thanks,
Dennis

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
