### ISSUE TITLE
Sending a post request to update the 'Extension' of a contact generate an 'UnableToDeserializePostBody' error

### ISSUE THREAD

**Issue by Fradven** [microsoftgraph/msgraph-sdk-java#1736]
### Expected behavior
We're creating several contacts, and for each newly created contact we try to add an `Extension`. This extension only contains two fields to identify the Exchange contact in our database.

We need it in order to differentiate what comes from our application from the other contacts in order to periodically update their content based on what's encoded in our application.

We are basing our code on the  [official documentation](https://learn.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0) as it was recommended to us when we first asked for a solution in a [previous issue](https://github.com/microsoftgraph/msgraph-sdk-java/issues/1534).

### Actual behavior

Here is the stack trace:

```
janv. 04, 2024 11:28:04 AM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[sendRequestInternal] - 408Graph service exception
janv. 04, 2024 11:28:04 AM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: UnableToDeserializePostBody
Error message: were unable to deserialize 

POST https://graph.microsoft.com/v1.0/users/{userId}/contacts/{contactId}/extensions
SdkVersion : graph-java/v5.49.0
SdkVersion : graph-java/v5.49.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
11:28:04,772  WARN  [app.manager.MsGraphHelper] error posting contact extension
com.microsoft.graph.http.GraphServiceException: Error code: UnableToDeserializePostBody
Error message: were unable to deserialize 

POST https://graph.microsoft.com/v1.0/users/{userId}/contacts/{contactId}/extensions
SdkVersion : graph-java/v5.49.0
SdkVersion : graph-java/v5.49.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:512)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:442)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
	at com.microsoft.graph.requests.ExtensionRequest.post(ExtensionRequest.java:137)
	at com.microsoft.graph.requests.ExtensionCollectionRequest.post(ExtensionCollectionRequest.java:65)
[...]

janv. 04, 2024 11:28:04 AM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[sendRequestInternal] - 408Graph service exception
janv. 04, 2024 11:28:04 AM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: RequestBroker--ParseUri
Error message: Can not resolve the segment identifier '{CONTACT_EXTENSION_ID}' in query option.

GET https://graph.microsoft.com/v1.0/users/{userId}/contacts/{contactId}?%24select=assistantName%2Cbirthday%2CbusinessAddress%2CbusinessHomePage%2CbusinessPhones%2Ccategories%2CchangeKey%2Cchildren%2CcompanyName%2CcreatedDateTime%2Cdepartment%2CdisplayName%2CemailAddresses%2CfileAs%2Cgeneration%2CgivenName%2ChomeAddress%2ChomePhones%2Cid%2CimAddresses%2Cinitials%2CjobTitle%2ClastModifiedDateTime%2Cmanager%2CmiddleName%2CmobilePhone%2CnickName%2CofficeLocation%2CotherAddress%2CparentFolderId%2CpersonalNotes%2Cprofession%2CspouseName%2Csurname%2Ctitle%2CyomiCompanyName%2CyomiGivenName%2CyomiSurname%2C{extensionId}
SdkVersion : graph-java/v5.49.0


400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
11:28:04,834  ERROR [app.manager.MsGraphHelper] Mails Test error
com.microsoft.graph.http.GraphServiceException: Error code: RequestBroker--ParseUri
Error message: Can not resolve the segment identifier '{CONTACT_EXTENSION_ID}' in query option.

GET https://graph.microsoft.com/v1.0/users/{userId}/contacts/{contactId}?%24select=assistantName%2Cbirthday%2CbusinessAddress%2CbusinessHomePage%2CbusinessPhones%2Ccategories%2CchangeKey%2Cchildren%2CcompanyName%2CcreatedDateTime%2Cdepartment%2CdisplayName%2CemailAddresses%2CfileAs%2Cgeneration%2CgivenName%2ChomeAddress%2ChomePhones%2Cid%2CimAddresses%2Cinitials%2CjobTitle%2ClastModifiedDateTime%2Cmanager%2CmiddleName%2CmobilePhone%2CnickName%2CofficeLocation%2CotherAddress%2CparentFolderId%2CpersonalNotes%2Cprofession%2CspouseName%2Csurname%2Ctitle%2CyomiCompanyName%2CyomiGivenName%2CyomiSurname%2C{extensionId}
SdkVersion : graph-java/v5.49.0
```

### Steps to reproduce the behavior

Here's the code that we use to create the extension and then try to update the contact :

```
Contact contact = new Contact();
[...]
contact = graphClient.users(targetUser.id).contacts().buildRequest().post(contact);

Extension contactExtension = new Extension();
contactExtension.id = CONTACT_EXTENSION_ID;
contactExtension.additionalDataManager().put("tenant", new JsonPrimitive(dbHelper.getTenant()));
contactExtension.additionalDataManager().put("entityId", new JsonPrimitive(""+ecContact.getId()));

try
{
       graphClient.users(targetUser.id).contacts(contact.id).extensions().buildRequest().post(contactExtension);

} catch (GraphServiceException ex )
{
	logger.warn("error posting contact extension", ex);
}
```

**Comment by Fradven** [comment]
We manage to find a solution to this issue by delaying the execution of the post request:

```
ContactRequestBuilder cb = graphClient.users(targetUser.id).contacts(contact.id);
contactExtension = (OpenTypeExtension) cb.extensions().buildRequest().post(contactExtension);
```

It seems that there is a problem with the input stream
