### ISSUE TITLE
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 210082 path $.value[9]

### ISSUE THREAD

**Issue by denysobukh** [microsoftgraph/msgraph-sdk-java#1779]
Expected behavior
Respond with `MessageCollectionPage`

Actual behavior
exception:
```
Caused by: com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:493) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:103) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78) ~[microsoft-graph-core-2.0.19.jar!/:na]
    ... < cut client's code >
	... 11 common frames omitted
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 210082 path $.value[9]
	at com.google.gson.Gson.fromJson(Gson.java:1241) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar!/:na]
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:104) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:536) ~[microsoft-graph-core-2.0.19.jar!/:na]
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:467) ~[microsoft-graph-core-2.0.19.jar!/:na]
	... 29 common frames omitted
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 210082 path $.value[9]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:485) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:779) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.1.jar!/:na]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar!/:na]
	... 34 common frames omitted
```

lib versions:

```
        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>5.77.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.11.1</version>
        </dependency>
```

code snippet:

```
    private MessageCollectionPage firstPage() {
        try {
            return client.users(userId)
                    .messages()
                    .buildRequest(List.of(new QueryOption("$orderby", "lastModifiedDateTime")))
                    .get();
        } catch (Exception ex) {
			MsClientExceptionHandler.handleException(ex, String.format("Access denied to get messages for userId = %s", userId));
			return EMPTY_PAGE;
        }
        
    }
```

and Client is built by 

```
public class Ms365GraphClientProvider {

        private static final int MAX_IDLE_CONNECTIONS = 1;
        private static final long KEEP_ALIVE_DURATION_MINUTES = 3L;
        private static final Duration CONNECT_TIMEOUT_DURATION = Duration.ofSeconds(60);
        private static final Duration READ_TIMEOUT_DURATION = Duration.ofSeconds(120);
        private static final Duration CALL_TIMEOUT_DURATION = Duration.ofSeconds(240);
        private static final IShouldRetry DEFAULT_SHOULD_RETRY = (delay, executionCount, request, response) -> true;
        private static final int MAX_RETRIES = 10;
        private static final long DELAY = 5;
    
        public GraphServiceClient<Request> client(@NonNull SecretCredentials cred) {
            var httpClient = HttpClients.createDefault(new TokenCredentialAuthProvider(tokenCredential(cred)))
                    .newBuilder()
                    .connectionPool(new ConnectionPool(MAX_IDLE_CONNECTIONS, KEEP_ALIVE_DURATION_MINUTES, TimeUnit.MINUTES))
                    .connectTimeout(CONNECT_TIMEOUT_DURATION)
                    .callTimeout(CALL_TIMEOUT_DURATION)
                    .readTimeout(READ_TIMEOUT_DURATION)
                    .retryOnConnectionFailure(false)
                    .addInterceptor(buildRetryHandlerInterceptor())
                    .build();
    
            return GraphServiceClient
                    .builder()
                    .httpClient(httpClient)
                    .buildClient();
        }
    
        @NotNull
        private RetryHandler buildRetryHandlerInterceptor() {
            return new RetryHandler(new RetryOptions(DEFAULT_SHOULD_RETRY, MAX_RETRIES, DELAY));
        }
    
        private TokenCredential tokenCredential(SecretCredentials cred) {
    
            return new ClientCertificateISCredential(
                    cred.getTenant(),
                    cred.getClientId(),
                    (DecryptionServiceStatisticWrapper.decryptStatic(cred.getSecretKey()) + "\n" + cred.getPublicKey())
                            .getBytes(StandardCharsets.UTF_8));
        }
    }
```

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
