### ISSUE TITLE
PATCH of email drafts not working anymore in Graph v6.1

### ISSUE THREAD

**Issue by sa-obgit-backend** [microsoftgraph/msgraph-sdk-java#1803]
PATCH of email drafts not working. Because it fail at creating the message with

```java
com.microsoft.graph.models.odataerrors.ODataError: A null value was found for the property named 'toRecipients', which has the expected type 'Collection(microsoft.graph.recipient)[Nullable=True]'. The expected type 'Collection(microsoft.graph.recipient)[Nullable=True]' cannot be null but it can have null values.
	at com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36) ~[microsoft-graph-6.1.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:197) ~[microsoft-kiota-serialization-json-1.0.1.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672) ~[microsoft-kiota-http-okHttp-1.0.0.jar:na]
	at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26) ~[microsoft-kiota-abstractions-1.0.1.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671) ~[microsoft-kiota-http-okHttp-1.0.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:279) ~[microsoft-kiota-http-okHttp-1.0.0.jar:na]
	at com.microsoft.graph.users.item.messages.item.MessageItemRequestBuilder.patch(MessageItemRequestBuilder.java:201) ~[microsoft-graph-6.1.0.jar:na]
	at com.microsoft.graph.users.item.messages.item.MessageItemRequestBuilder.patch(MessageItemRequestBuilder.java:185) ~[microsoft-graph-6.1.0.jar:na]
	at de.baudc.connector.microsoft.graph.adapter.out.GraphEmailRepository.updateEmailDraft(GraphEmailRepository.java:79) ~[connector-microsoft-graph-4.0.0-SNAPSHOT.jar:na]
	at de.baudc.integrationtest.TestController.updateDraft(TestController.java:136) ~[main/:na]
```

The problem is that all email lists are "mandatory expected" but for a PATCH this is obvisiously not useful to deliver.

I think this is the same problem for:
- to
- cc
- bcc
- replyTo

### Expected behavior

null for the email lists is allowed (at least for PATCH), but better in general.
btw.: getting on the message object says NULLABLE so principally this is also an inconsistency

### Actual behavior

PATCH will fail if not all email lists are delivered

### Steps to reproduce the behavior

```java
Message messageBody = new Message();
messageBody.setSubject("updated subject");
Message message = this.graphRepository.getGraphServiceClient().users().byUserId("xxx@xxx").messages().byMessageId(graphId).patch(messageBody);
```

will fail with ODataError (as above). If you set empty lists then the fields will be cleared from the PATCH and the message can not be send anymore

**Comment by Ndiritu** [comment]
@sa-obgit-backend Thanks for reporting this.
I'm unable to reproduce this with the sample you shared. However,  I can reproduce this when `toRecipients` etc are set  `null` explicitly.

```java
var patchMessage = new Message();
patchMessage.setSubject("ANOTHER SUBJECT!");
patchMessage.setToRecipients(null); // throws error

patchMessage.setToRecipients(new ArrayList<>()); // works
```

Are you setting the value to `null` as in the first example?

**Comment by Ndiritu** [comment]
@baywet looks like we set all properties of models to be nullable by default during generation. From the OpenAPI schema I see that `toRecipients` is not nullable. Should this be change we make in Kiota?

**Comment by baywet** [comment]
aaah, this a long debate. Short answer no: because the same model is used for all CRUD, and in a read scenario, you can this field is not always selected, therefore it can be null.
If we wanted to "fix" that aspect, we'd need the metadata conversion process to emit different models based on the operation. Something we've been talking about but that's beyond the scope of this discussion I'd argue.

**Comment by Ndiritu** [comment]
Thanks for the context. Just wondering whether for properties that are not explicitly nullable, only the "getters" can be nullable but setters shouldn't accept nulls?

**Comment by sa-obgit-backend** [comment]
Only to make it clear again:
My problem/bug is not that I cannot set the null value. Even if the null value is set the PATCH will not work because of the ODataError above :)

So yes, I would appreciate if the API is consistent with the objects (nullable or not) but the problem will still exists :)

**Comment by Ndiritu** [comment]
Might you be serializing the objects directly using the `JsonSerializationWriter` as in https://github.com/microsoftgraph/msgraph-sdk-java/issues/1798?

**Comment by sa-obgit-backend** [comment]
Sorry was on holiday :)
It is still an issue in Graph 6.4.0

you should reproduce it via:


EMail draft = new EMail();
draft.setTo(List.of(...));
draft.setCc(List.of(...));
String graphId = graphEmailConnector.createEmailDraft(draft);


EMail update = new EMail();
update.setSubject(SUBJECT_PREFIX + "testEmailDraftWorkflow()");
update.setTextBody("Dies ist der Textkörper der Vorlagen-E-Mail.");
graphEmailConnector.updateEmailDraft(graphId, update, withHack);


graphEmailConnector.sendEmailDraft(graphId)
