### ISSUE TITLE
java.time.format.DateTimeParseException when graphClient.users().count().get()

### ISSUE THREAD

**Issue by denysobukh** [microsoftgraph/msgraph-sdk-java#1813]
### Expected behavior

Perform request graphClient.users().count().get()

### Actual behavior

```
java.time.format.DateTimeParseException: Text '2024-02-14T03:10:53' could not be parsed at index 19
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954) ~[na:na]
	at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:404) ~[na:na]
	at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:389) ~[na:na]
	at com.microsoft.kiota.serialization.JsonParseNode.getOffsetDateTimeValue(JsonParseNode.java:98) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.graph.models.odataerrors.InnerError.lambda$getFieldDeserializers$1(InnerError.java:83) ~[microsoft-graph-6.1.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:247) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:198) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.graph.models.odataerrors.MainError.lambda$getFieldDeserializers$2(MainError.java:83) ~[microsoft-graph-6.1.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:247) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:198) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.graph.models.odataerrors.ODataError.lambda$getFieldDeserializers$0(ODataError.java:74) ~[microsoft-graph-6.1.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:247) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:198) ~[microsoft-kiota-serialization-json-1.0.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672) ~[microsoft-kiota-http-okHttp-1.0.0.jar:na]
	at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26) ~[microsoft-kiota-abstractions-1.0.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671) ~[microsoft-kiota-http-okHttp-1.0.0.jar:na]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.sendPrimitive(OkHttpRequestAdapter.java:341) ~[microsoft-kiota-http-okHttp-1.0.0.jar:na]
	at com.microsoft.graph.users.count.CountRequestBuilder.get(CountRequestBuilder.java:57) ~[microsoft-graph-6.1.0.jar:na]
	at com.microsoft.graph.users.count.CountRequestBuilder.get(CountRequestBuilder.java:44) ~[microsoft-graph-6.1.0.jar:na]
```

### Steps to reproduce the behavior

```
void m() {
GraphServiceClient client = new GraphServiceClient(tokenCredential(credentials), "https://graph.microsoft.com/.default");

final var users = client.users()
				.count()
				.get();
}

private TokenCredential tokenCredential(OneDriveSecretCredentials credentials) {
		return new com.azure.identity.ClientCertificateCredentialBuilder()
				.clientId(credentials.getClientId())
				.tenantId(credentials.getTenant())
				.pemCertificate(new ByteArrayInputStream(
				(DecryptionServiceWrapper.decryptStatic(credentials.getSecretKey()) + "\n" + credentials.getPublicKey())
								.getBytes(StandardCharsets.UTF_8)))
				.build();
	}
```

### Dependencies 

```
        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>6.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-abstractions</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-authentication-azure</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-http-okHttp</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-json</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-text</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-form</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-multipart</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.11.1</version>
        </dependency>
```

**Comment by davidmoten** [comment]
The value '2024-02-14T03:10:53' doesn't have a time zone specified so it's incomplete

**Comment by kekolab** [comment]
See #1815

**Comment by Ndiritu** [comment]
Closing this as it's related to https://github.com/microsoftgraph/msgraph-sdk-java/issues/1785

Fix has been merged and should be released later today.
