### ISSUE TITLE
List Sessions call using expand segments failing with java.lang.UnsupportedOperationException: text does not support structured data  

### ISSUE THREAD

**Issue by priya2395** [microsoftgraph/msgraph-sdk-java#1819]
### Expected behavior
List Sessions call using expand segments should return list of sessions including segments

### Actual behavior

List Sessions call using expand segments failing with java.lang.UnsupportedOperationException: text does not support structured data  

### Steps to reproduce the behavior

       final SessionCollectionResponse sessions = graphClient
                .communications()
                .callRecords()
                .byCallRecordId("e523d2ed-2966-4b6b-925b-754a88034cc5")
                .sessions()
                .get(requestConfiguration -> {
                    requestConfiguration.queryParameters.expand = new String []{"segments"};
                });

**Comment by Ndiritu** [comment]
@priya2395 I'm unable to reproduce this behaviour. Would you mind sharing a stacktrace?

**Comment by sudhamadhuri** [comment]
Hi, is this issue fixed, can I get advice on this as I seem to have similar issue

**Comment by stherkildsen** [comment]
I have seen the same issue when updating a calendar event in a users calendar.
Stack-trace:
`java.lang.UnsupportedOperationException: text does not support structured data
	at deployment.mscalendarsync.war//com.microsoft.kiota.serialization.TextParseNode.getObjectValue(TextParseNode.java:125)
	at deployment.mscalendarsync.war//com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:674)
	at deployment.mscalendarsync.war//com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
	at deployment.mscalendarsync.war//com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:673)
	at deployment.mscalendarsync.war//com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:281)
	at deployment.mscalendarsync.war//com.microsoft.graph.users.item.calendar.events.item.EventItemRequestBuilder.patch(EventItemRequestBuilder.java:203)
	at deployment.mscalendarsync.war//com.microsoft.graph.users.item.calendar.events.item.EventItemRequestBuilder.patch(EventItemRequestBuilder.java:187)`

**Comment by Ndiritu** [comment]
Thanks for reporting this @stherkildsen.

This seems like an issue during deserialization of some error payloads.

Would you mind sharing the response status code, headers & OData type of the body (please redact sensitive information) and sharing this with us?

**Comment by stherkildsen** [comment]
Is there a way to enable debug logging, that could expose the data you need. It only happens in our production environment, so I have only logging to go by.
  

  

  

  
  
  
  
  
>

**Comment by Ndiritu** [comment]
Hi @stherkildsen 
You can enable [OpenTelemetry](https://github.com/MicrosoftDocs/openapi-docs/issues/12#issuecomment-2082607536) using the snippet or use OkHttp's logging interceptor:

```java

HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor(System.out::println);
loggingInterceptor.level(HttpLoggingInterceptor.Level.BODY);
OkHttpClient.Builder builder = GraphClientFactory.create();
builder.addInterceptor(loggingInterceptor);
OkHttpClient okHttpClient = builder.build();
GraphServiceClient client = new GraphServiceClient(authProvider, okHttpClient);

```

**Comment by stherkildsen** [comment]
Finally got some time on my project to try and implement the logging described above. Unfortunately there seems to be an issue in the logging intercepter. When I turn on body logging I get an error.

Looks like the body is logged (maybe from an outputstream) and then it is empty shortly after `--> END POST (-1-byte body)`

I am using version 4.12.0 of the okhttp3 libraries and 6.5.0 of microsoft-graph.

Do you have a suggestion for a workaround?

Log output:
```
2025-01-10 10:54:34.578 DEBUG --> POST https://graph.microsoft.com/v1.0/users/amin%40myapp.onmicrosoft.com/calendar/events
2025-01-10 10:54:34.578 DEBUG Content-Length: 728
2025-01-10 10:54:34.578 DEBUG authorization: ██
2025-01-10 10:54:34.578 DEBUG accept: application/json
2025-01-10 10:54:34.578 DEBUG content-type: application/json
2025-01-10 10:54:34.578 DEBUG SdkVersion: graph-java, graph-java-core/3.1.6 (featureUsage=1203; runtimeEnvironment=JRE/11.0.18)
2025-01-10 10:54:34.578 DEBUG client-request-id: 3572925e-a37b-4d37-a35c-065c78b08b6c
2025-01-10 10:54:34.578 DEBUG User-Agent: kiota-java/1.1.1
2025-01-10 10:54:34.578 DEBUG 
2025-01-10 10:54:34.578 DEBUG {"@odata.type":"#microsoft.graph.event","categories":["MyApp"],"attendees":[{"emailAddress":{"address":"amin@myapp.onmicrosoft.com"},"@odata.type":"#microsoft.graph.attendee","type":"required"}],"body":{"content":"Denne aftale er oprettet automatisk og afspejler en aftale, du har i din kalender i myapp, hvor du kan finde yderligere informationer. Tilføj venligst ikke yderligere informationer til denne aftale, da du risikerer, at de overskrives.","contentType":"html"},"end":{"dateTime":"2025-01-10T19:34:00.000","timeZone":"Europe/Copenhagen"},"sensitivity":"normal","showAs":"busy","start":{"dateTime":"2025-01-10T19:04:00.000","timeZone":"Europe/Copenhagen"},"subject":"Aftale med borger(MyApp)","type":"singleInstance"}
2025-01-10 10:54:34.578 DEBUG --> END POST (-1-byte body)
2025-01-10 10:54:34.598 DEBUG <-- 400 https://graph.microsoft.com/v1.0/users/amin%40curagraph.onmicrosoft.com/calendar/events (20ms)
2025-01-10 10:54:34.598 DEBUG content-type: application/json
2025-01-10 10:54:34.598 DEBUG vary: Accept-Encoding
2025-01-10 10:54:34.598 DEBUG strict-transport-security: max-age=31536000
2025-01-10 10:54:34.598 DEBUG request-id: 0dc40db2-3914-4c63-bec4-1f27a43c5923
2025-01-10 10:54:34.598 DEBUG client-request-id: 3572925e-a37b-4d37-a35c-065c78b08b6c
2025-01-10 10:54:34.598 DEBUG x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"008","RoleInstance":"AM2PEPF0001BE6B"}}
2025-01-10 10:54:34.598 DEBUG date: Fri, 10 Jan 2025 09:54:33 GMT
2025-01-10 10:54:34.599 DEBUG 
2025-01-10 10:54:34.599 DEBUG {"error":{"code":"BadRequest","message":"Empty Payload. JSON content expected.","innerError":{"date":"2025-01-10T09:54:34","request-id":"0dc40db2-3914-4c63-bec4-1f27a43c5923","client-request-id":"3572925e-a37b-4d37-a35c-065c78b08b6c"}}}
2025-01-10 10:54:34.599 DEBUG <-- END HTTP (236-byte body)
2025-01-10 10:54:34.601 ERROR message="Creating Microsoft Calendar event failed. Empty Payload. JSON content expected."exceptionMessage="Empty Payload. JSON content expected.", body=***OMITTED***, headers=***OMITTED***, stacktrace="com.microsoft.graph.models.odataerrors.ODataError: Empty Payload. JSON content expected.

**Comment by Ndiritu** [comment]
@stherkildsen this bug was fixed in a later release. Upgrading to the latest SDK version would be ideal.
