### ISSUE TITLE
Socket timeout exception using Microsoft Graph API email account

### ISSUE THREAD

**Issue by Sudheermp18** [microsoftgraph/msgraph-sdk-java#1829]
Pega application connects to Azure using Microsoft Graph API . We are getting Socket timeout exception when connecting to Azure using Microsoft Graph API. Tested using Postman.
[8:42](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096347762189)
Getting this error in Postman
[8:42](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096351108299)
"error": {
        "code": "ErrorAccessDenied",
        "message": "Access to OData is disabled."
[8:43](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096382485239)
Checked if there an application restriction policy. No application restrictions on the Mailbox account
[8:43](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096400817169)
So we would like to check if there is a Java SDK issue
[8:43](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096430067099)
Pega version :  8.7.5
[8:46](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096567259179)
Java SDK version : 8
[8:47](https://moodys-mco-mit.slack.com/archives/D06J4A1CVKM/p1708096628426599)
Caused by: java.net.SocketException: Connection reset
   at [java.net](http://java.net/).SocketInputStream.read(SocketInputStream.java:221) ~[?:1.8.0]
   at [java.net](http://java.net/).SocketInputStream.read(SocketInputStream.java:152) ~[?:1.8.0]
   at com.ibm.jsse2.b.a(b.java:123) ~[?:8.0 build_20200226--97]
   at com.ibm.jsse2.b.a(b.java:269) ~[?:8.0 build_20200226--97]
   at com.ibm.jsse2.av.a(av.java:12) ~[?:8.0 build_20200226--97]
   at com.ibm.jsse2.av.i(av.java:647) ~[?:8.0 build_20200226--97]
   at com.ibm.jsse2.av.a(av.java:231) ~[?:8.0 build_20200226--97]
   at com.ibm.jsse2.av.startHandshake(av.java:175) ~[?:8.0 build_20200226--97]
   at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:?]
   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar:?]
   at com.pega.platform.integrationcore.client.email.internal.msgraph.MSGraphEmailClient.getAttachmentsJSon(MSGraphEmailClient.java:1123) ~[integration-core.jar:?]
   at com.pega.platform.integrationcore.client.email.internal.msgraph.MSGraphEmailClient.getAttachments(MSGraphEmailClient.java:1099) ~[integration-core.jar:?]
![image (99)](https://github.com/microsoftgraph/msgraph-sdk-java/assets/94528226/776e43ce-71e0-43fc-981f-30c25243a708)

**Comment by Ndiritu** [comment]
Hi @Sudheermp18 would you mind sharing what request you're making using the SDK so that we can try to reproduce this?
Could you also try making the same request using [Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and share if it works there?

**Comment by Sudheermp18** [comment]
It's a POST request.
We are getting 403 error below
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access to OData is disabled."
    }
}

**POST Request:**
{
  "message": {
    "subject": "Test email?",
    "body": {
      "contentType": "Text",
      "content": "This is a test email."
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": "emailid1"
        }
      }
    ],
    "ccRecipients": [
      {
        "emailAddress": {
          "address": "Emailid2"
        }
      }
    ]
  },
  "saveToSentItems": "false"
}

**Comment by baywet** [comment]
Thanks for the additional information, this is most likely caused by a configuration on the service side that your admin can update.
[see the following answer](https://learn.microsoft.com/en-us/answers/questions/820426/microsoft-graph-me-messages-api-return-message-acc)

**Comment by Sudheermp18** [comment]
Thank you for your reply. we already checked the application access policy, there are no restrictions.
we would want to know if there is an SDK issue

**Comment by baywet** [comment]
No, the error leads to an issue with the service configuration. Additionally, none of the stack trace points to components of the Microsoft Graph Java SDK. And the Microsoft Graph Java SDK uses OkHttp client under the covers, this stack trace refers to apache http client. It really seems this issue is unrelated to the msgraph Java SDK.

**Comment by baywet** [comment]
You might want to look at the details in #510 as well

**Comment by Sudheermp18** [comment]
We have gone through the link provided.
 Our SDK version is also java1.8.0

upgrading to java 2.0.0 would help resolve the issue. please confirm?

since there are no restrictions with application access policy

**Comment by baywet** [comment]
Again, nothing in the information you've provided to this point indicates the Microsoft Graph Java SDK (`com.microsoft.graph`) is being used by the application.
I'd encourage you to get in touch with Pega's support and validate with them how their Microsoft Graph API client is built.

**Comment by Sudheermp18** [comment]
Java SDK- 1.8.0 is related to Pega not the Microsoft Graph Java SDK
should I upgrade the Pega related Java SDK version to 2.0.0

**Comment by Sudheermp18** [comment]
https://graph.microsoft.com/v1.0/

this is the version we are using
 in the POST request url

should we upgrade it to 2.0.0 or higher version ?

**Comment by baywet** [comment]
Let me try to be clear here, there are multiple products:
- Microsoft Graph: an HTTP REST API that can be queried with any http client.
- Microsoft Graph Java SDK: a Java wrapper around the REST API. This is the focus of this repository.
- Java SDK: the development ecosystem to build any java based application, whether they make use or the first two products or not.

**I'm asserting that your application is not leveraging the Microsoft Graph Java SDK**, hence why you won't find an answer here. The latest version is 6.2.0.

For the REST API, there's no v2.

For the Java SDK, the latest LTS version is 21 (depends on the vendor, OS, etc...) but it's unlikely that this is going to have any impact on the kind of error you're getting.
