### ISSUE TITLE
Java 8 question

### ISSUE THREAD

**Issue by szlnnn** [microsoftgraph/msgraph-sdk-java#1831]
Hello! 
I just want to point out that in the documentation specifically from version 6.1 onward, it says that the sdk works with java 8 however with the kiota dependencies it s not the case anymore as I experienced. Could you confirm this and maybe modify the documentation to java 11? 

Here is just an example:

Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.isBlank()Z
	at com.microsoft.kiota.http.middleware.ParametersNameDecodingHandler.decodeQueryParameters(ParametersNameDecodingHandler.java:110)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.startSpan(OkHttpRequestAdapter.java:249)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:272)
	at com.microsoft.graph.subscribedskus.SubscribedSkusRequestBuilder.get(SubscribedSkusRequestBuilder.java:75)
	at com.microsoft.graph.subscribedskus.SubscribedSkusRequestBuilder.get(SubscribedSkusRequestBuilder.java:61)

**Comment by ccea-dev-team** [comment]
Yes I had same issue -seems  6.1+ now requires Java 11 as some dependency is using isBlank() method on a String.

**Comment by vladimir-filipchanka** [comment]
Same issue. What is the latest version working with Java 8?

**Comment by szlnnn** [comment]
I believe it's 5.80.0, the kiota dependencies came with 6.1+

**Comment by baywet** [comment]
Hi everyone,
Thanks for using the SDK and for reporting this.

Yes, kiota dependencies were added with version 6.0+

However, this dependency on an API higher than 1.8 is an oversight on our end.

@szlnnn since you're the OP on this thread, would you be willing to submit a pull request to fix this issue?
[this call](https://github.com/microsoft/kiota-java/blob/082b0697e806823711f23abe6faa956ac10d91f4/components/http/okHttp/src/main/java/com/microsoft/kiota/http/middleware/ParametersNameDecodingHandler.java#L155) and [that one](https://github.com/microsoft/kiota-java/blob/082b0697e806823711f23abe6faa956ac10d91f4/components/http/okHttp/src/main/java/com/microsoft/kiota/http/middleware/ParametersNameDecodingHandler.java#L110] need to be replaced by calls to [this method instead](https://github.com/microsoft/kiota-java/blob/082b0697e806823711f23abe6faa956ac10d91f4/components/abstractions/src/main/java/com/microsoft/kiota/Compatibility.java#L40]

**Comment by szlnnn** [comment]
Hi, @baywet sure I`ll take a look.

**Comment by baywet** [comment]
Thanks for putting this together, already left a review over there.

**Comment by vladimir-filipchanka** [comment]
After bumping kiota deps to `1.0.3` with the latest release `6.2.1` at the day of writing, I was able to get a bit further. 
But the next hump is 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:41)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:709)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
	at com.microsoft.graph.serviceprincipals.item.ServicePrincipalItemRequestBuilder.patch(ServicePrincipalItemRequestBuilder.java:358)
	at com.microsoft.graph.serviceprincipals.item.ServicePrincipalItemRequestBuilder.patch(ServicePrincipalItemRequestBuilder.java:343)
```

Github's [stduritemplate lib](https://github.com/std-uritemplate/std-uritemplate) is not compatible with java 8. It is transitive dep through `com.microsoft.kiota:microsoft-kiota-abstractions`. 
The thing is stduritemplate doesn't seem to ever had a compatibility with Java 8, as 0.0.1 [version](https://github.com/std-uritemplate/std-uritemplate/blob/0.0.1/java/pom.xml#L37) had `maven.compiler.source = 11`

**Comment by baywet** [comment]
@vladimir-filipchanka can you create an issue [here](https://github.com/std-uritemplate/std-uritemplate/issues) with that stack trace please?
