### ISSUE TITLE
Incompatibility with Java 8

### ISSUE THREAD

**Issue by vladimir-filipchanka** [microsoftgraph/msgraph-sdk-java#1852]
[Bumping this as a separate issue]

After bumping kiota deps to `1.0.3` (see https://github.com/microsoftgraph/msgraph-sdk-java/issues/1831
for more context) with the latest release `6.2.1` at the day of writing, I was able to get a bit further. 
But the next hump is 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:41)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:709)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
	at com.microsoft.graph.serviceprincipals.item.ServicePrincipalItemRequestBuilder.patch(ServicePrincipalItemRequestBuilder.java:358)
	at com.microsoft.graph.serviceprincipals.item.ServicePrincipalItemRequestBuilder.patch(ServicePrincipalItemRequestBuilder.java:343)
```

Github's [stduritemplate lib](https://github.com/std-uritemplate/std-uritemplate) is not compatible with java 8. It is transitive dep through `com.microsoft.kiota:microsoft-kiota-abstractions`. 

I asked this question [here](https://github.com/std-uritemplate/std-uritemplate/issues/132), but I think it makes more sense to address the issue on the msgraph-sdk-java's side as stduritemplate doesn't seem to ever had a compatibility with Java 8, as 0.0.1 [version](https://github.com/std-uritemplate/std-uritemplate/blob/0.0.1/java/pom.xml#L37) had `maven.compiler.source = 11` right away.

**Comment by baywet** [comment]
For everyone reading: https://github.com/std-uritemplate/std-uritemplate/issues/132 was re-opened, we'll wait for a resolution there before we do anything with this issue.

**Comment by baywet** [comment]
update: this has been fixed in the dependency: can you upgrade it and confirm you can now run with java 8 @vladimir-filipchanka  please?

**Comment by baywet** [comment]
@vladimir-filipchanka thanks for confirming! this weeks release will have the dependencies aligned (6.5.0)
Closing
