### ISSUE TITLE
Adding query parameters not working on Android with SDK 6.x

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#1861]
I am trying to add a select parameter to a request following the documentation at https://learn.microsoft.com/en-us/graph/sdks/create-requests?tabs=java#use-select-to-control-the-properties-returned

`final User user = graphClient.me().get( requestConfiguration -> {
	requestConfiguration.queryParameters.select = new String[] {"id"};
});`

### Expected behavior

I get a user object with an id

### Actual behavior

I get an exception:

 Caused by: java.lang.NoSuchMethodError: No static method encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Ljava/net/URLEncoder; or its super classes (declaration of 'java.net.URLEncoder' appears in /apex/com.android.runtime/javalib/core-oj.jar)
                                                                                                    	at io.github.stduritemplate.StdUriTemplate.addExpandedValue(StdUriTemplate.java:296)
                                                                                                    	at io.github.stduritemplate.StdUriTemplate.addValue(StdUriTemplate.java:239)
                                                                                                    	at io.github.stduritemplate.StdUriTemplate.addStringValue(StdUriTemplate.java:457)
                                                                                                    	at io.github.stduritemplate.StdUriTemplate.expandToken(StdUriTemplate.java:443)
                                                                                                    	at io.github.stduritemplate.StdUriTemplate.expandImpl(StdUriTemplate.java:113)
                                                                                                    	at io.github.stduritemplate.StdUriTemplate.expand(StdUriTemplate.java:19)
                                                                                                    	at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
                                                                                                    	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:41)
                                                                                                    	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:709)
                                                                                                    	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
                                                                                                    	at com.microsoft.graph.users.item.UserItemRequestBuilder.get(UserItemRequestBuilder.java:743)

### Steps to reproduce the behavior

Try to add a select statement to a request on Android.
I am able to reproduce this behavior with other request methods as well.

**Comment by baywet** [comment]
Thanks for using the SDK and for reaching out.
Can you double check which version of std uri template is in use?
The method referred to [is only available for API level 33 and above](https://developer.android.com/reference/java/net/URLEncoder#encode(java.lang.String,%20java.nio.charset.Charset)) but it was replaced by its alternative available since level 1 [a couple of days ago](https://github.com/std-uritemplate/std-uritemplate/pull/133)

**Comment by slowcar** [comment]
Difficult to say, i cannot step into the code in my project, but i think it could be it. If i run the project on an Android 14 device (api level 34) it works (or rather, i get a different error, will create an issue for that as well). I used an Android 10 (api 29) emulator before.
I updated the dependency to 6.4.0 beforehand (as my other issue was resolved with it), the changelog was not very verbose, 
My guess would be that the change you mention was not part of that version yet.
Because as a workaround i can add implementation 'io.github.std-uritemplate:std-uritemplate:0.0.54' as a dependency and run it on api 29 as well.

**Comment by baywet** [comment]
Thanks for the additional information. Did I understand correctly that when you "force the project" to use std uri template version 54, it works on api level 19?

**Comment by slowcar** [comment]
Yes, it works on api levels below 33 when i add the patched std-uritemplate library directly.
("works" insofar that i get a different error, which i reported in another issue)

**Comment by slowcar** [comment]
6.5.0 should fix the issue.
Until then the workaround is to add
implementation 'io.github.std-uritemplate:std-uritemplate:0.0.54'
