### ISSUE TITLE
TokenToReplace does not exist error when running select query with sdk 6.4.0

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#1862]
As in https://github.com/microsoftgraph/msgraph-sdk-java/issues/1861 i am trying to retrieve a user with a select statement.

`final User user = graphClient.me().get( requestConfiguration -> { requestConfiguration.queryParameters.select = new String[] {"id"}; });`

### Expected behavior
I get an user object with an id

### Actual behavior
An ODataError is thrown:
com.microsoft.graph.models.odataerrors.ODataError: Resource 'TokenToReplace' does not exist or one of its queried reference-property objects are not present.
at com.microsoft.graph.admin.AdminRequestBuilder$$ExternalSyntheticLambda0.create(Unknown Source:0)
at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:210)
at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672)
at com.microsoft.kiota.http.OkHttpRequestAdapter$$ExternalSyntheticLambda1.get(Unknown Source:4)
at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671)
at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:279)

### Steps to reproduce the behavior
try to retrieve an user object with a selection on Android

**Comment by baywet** [comment]
Thanks for reporting this.
Do you get the same behaviour when you don't provide a select statement? or just with the select statement?

**Comment by slowcar** [comment]
I get the same error when i use graphClient.me().get() without any select statement.

Another statement that does not work is graphClient.me().calendars().byCalendarId(folderId).get()
which reports  com.microsoft.graph.models.odataerrors.ODataError: The requested user 'TokenToReplace' is invalid.

**Comment by baywet** [comment]
I know we've been talking about Android applications in the other threads, so I'm assuming this is running an android application?
Are you able to reproduce the issue with a java application?

My theory is that the token to replace `/users/TokenToReplace`  contains a slash that somehow gets evaluated by the regex engine differently on android than on java.
https://github.com/microsoft/kiota-java/blob/d2103b331ee3aca1bc0d441d30041649aa428035/components/http/okHttp/src/main/java/com/microsoft/kiota/http/middleware/UrlReplaceHandler.java#L110

should be 

```java
replacedUrl = replacedUrl.replace(Pattern.quote(entry.getKey()), Matcher.quoteReplacement(entry.getValue()));
```

**Comment by slowcar** [comment]
Yes, it is an android app.
I do not have a java app to compare.

**Comment by baywet** [comment]
I was able to quickly put together a console application with the following:


```java
GraphServiceClient graphClient = 
            new GraphServiceClient(
                deviceCodeCredential,
                graphUserScopes);
        
        User me = graphClient.me().get();
        System.out.println("V1: " + me.getDisplayName());
```

(using 6.4.0)
And have it execute successfully. Which leads me to think my theory about the replacement not happening properly on Android because of a difference in the regex engine would make sense.

Are you able to clone the kiota-java, msgraph-sdk-java-core, msgraph-sdk-java repository, link the dependencies locally, apply the change I've suggested, and test that it resolves the android issue locally?

**Comment by baywet** [comment]
> Don't you have some kind of automated testing that also covers android?

Not today. We do have static analysis in place that validates we're using java 8 and API level 21, but that's about it. There are lots of historical reasons for that but it basically boils down to a status quo: we have long terms wishes to maybe provide a kotlin and swift SDK so the mobile story is much better. But we currently have no funding for it. As an intermediate stage we provide android support through the Java SDK, but investments are limited (and we have no iOS story today). We acknowledge this is less than ideal, but it's better than nothing. Thank you for your patience on the matter.

> but i can't access the exact values as my breakpoints in that class are not called

Simply duplicate the whole "UrlReplaceHandler" class in your project for now, and inject it via something like this

```java
UrlReplaceHandlerDebug handler = new UrlReplaceHandlerDebug();// pass it the option with the token replacement values 
// https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/294f1e5f1b02c7c2b55216642c111cc33610c01a/src/main/java/com/microsoft/graph/core/CoreConstants.java#L139
// https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/294f1e5f1b02c7c2b55216642c111cc33610c01a/src/main/java/com/microsoft/graph/core/requests/GraphClientFactory.java#L85
OkHttpClient.Builder builder = GraphClientFactory,create(handler); // your client will be missing the other ones, but it's fine for testing purposes
OkHttpClient okHttpClient = builder.build();
GraphServiceClient graphClient = new GraphServiceClient(authenticationProvider, okHttpClient);
// request
```

This way you should be able to step through the code.

**Comment by slowcar** [comment]
I tried your approach, the UrlReplaceHandlerDebug is not called.
However,  when i use GraphClientFactory.create() instead of new OkHttpClient.Builder() the replacement works.
Going through the code i see that the create() method calls createDefaultGraphInterceptors. It looks to me that these interceptors are not added if i use a custom okhttpclient instance which causes the issue - as the UrlReplaceHandler is never added and thus never called.

I have doublechecked the upgrade guide and did not find any mention of GraphClientFactory. I would suggest that the guide explains the need of using the factory to create a builder.

In any case, my issue is resolved

**Comment by baywet** [comment]
Thanks for the additional information here.
So the issue was caused because you were using a custom ok http client, but not adding the middleware handlers to it?

**Comment by slowcar** [comment]
yes. I was not aware of any middleware handlers that had to be added.
