### ISSUE TITLE
PlannerAssignment class does not exist

### ISSUE THREAD

**Issue by HermanShpryhau** [microsoftgraph/msgraph-sdk-java#1873]
In the docs for [creating a task](https://learn.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=java#request) the `PlannerAssignment` is mentioned in the code example, but this class is not present in the library.

**Comment by Ndiritu** [comment]
Thanks for reporting this @HermanShpryhau. 

While this is being investigated, you can try using a HashMap to hold the `plannerAssignment` properties and values as follows. Lmk if this unblocks you:

```java
HashMap<String, Object> additionalData = new HashMap<String, Object>();
HashMap<String, Object> plannerAssignment = new HashMap<String, Object>();
plannerAssignment.put("@odata.type", "#microsoft.graph.plannerAssignment");
plannerAssignment.put("orderHint", " !");
additionalData.put("fbab97d0-4932-4511-b675-204639209557", plannerAssignment);
assignments.setAdditionalData(additionalData);
plannerTask.setAssignments(assignments);
```

**Comment by Ndiritu** [comment]
(Triage notes)
[`PlannerAssignments`](https://learn.microsoft.com/en-us/graph/api/resources/plannerassignments?view=graph-rest-1.0) is an [open type](https://learn.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/use-open-types-in-odata-v4). [ `PlannerAssignment`(no 's')](https://learn.microsoft.com/en-us/graph/api/resources/plannerassignment?view=graph-rest-1.0) is declared as a component in the OpenAPI spec but not generated by Kiota. Could this be because it's not references as an optional property of `plannerAssignments`?

**Comment by HermanShpryhau** [comment]
Unfortunately putting a map there results in following exception:
```
java.lang.IllegalStateException: Dangling name: 27a1c9e1-8745-43b6-b8e1-bd2493ed5ac8
	at com.google.gson.stream.JsonWriter.close(JsonWriter.java:346) ~[gson-2.10.1.jar:na]
	at com.google.gson.stream.JsonWriter.endObject(JsonWriter.java:321) ~[gson-2.10.1.jar:na]
	at com.microsoft.kiota.serialization.JsonSerializationWriter.writeObjectValue(JsonSerializationWriter.java:307) ~[microsoft-kiota-serialization-json-1.0.4.jar:na]
	at com.microsoft.graph.models.PlannerTask.serialize(PlannerTask.java:273) ~[microsoft-graph-6.4.0.jar:na]
	at com.microsoft.kiota.serialization.JsonSerializationWriter.writeObjectValue(JsonSerializationWriter.java:292) ~[microsoft-kiota-serialization-json-1.0.4.jar:na]
	at com.microsoft.kiota.RequestInformation.setContentFromParsable(RequestInformation.java:358) ~[microsoft-kiota-abstractions-1.0.4.jar:na]
	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.toPostRequestInformation(TasksRequestBuilder.java:154) ~[microsoft-graph-6.4.0.jar:na]
	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.post(TasksRequestBuilder.java:108) ~[microsoft-graph-6.4.0.jar:na]
	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.post(TasksRequestBuilder.java:95) ~[microsoft-graph-6.4.0.jar:na]
```
I also tried creating a GSON json object and putting it there. Didn't help either.

**Comment by Ndiritu** [comment]
My apologies @HermanShpryhau. I meant to pass the JSON string value. Updated the sample.

**Comment by HermanShpryhau** [comment]
The string approach didn't work for me either. I don't have logs at hand currently unfortunately.

**Comment by Eleirbag89** [comment]
The string approach didn't work.
This is the error log:
```
Exception in thread "main" com.microsoft.graph.models.odataerrors.ODataError: An open type property has an invalid type.
	at com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36)
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:210)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672)
	at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:279)
	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.post(TasksRequestBuilder.java:111)
	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.post(TasksRequestBuilder.java:95)
	at org.example.Main.main(Main.java:39)
```

**Comment by Ndiritu** [comment]
> (Triage notes) [`PlannerAssignments`](https://learn.microsoft.com/en-us/graph/api/resources/plannerassignments?view=graph-rest-1.0) is an [open type](https://learn.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/use-open-types-in-odata-v4). [ `PlannerAssignment`(no 's')](https://learn.microsoft.com/en-us/graph/api/resources/plannerassignment?view=graph-rest-1.0) is declared as a component in the OpenAPI spec but not generated by Kiota. Could this be because it's not references as an optional property of `plannerAssignments`?

@baywet when you have some time, might you be able to share more on this?

**Comment by Ndiritu** [comment]
> The string approach didn't work. This is the error log:
> 
> ```
> Exception in thread "main" com.microsoft.graph.models.odataerrors.ODataError: An open type property has an invalid type.
> 	at com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36)
> 	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:210)
> 	at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672)
> 	at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
> 	at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671)
> 	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:279)
> 	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.post(TasksRequestBuilder.java:111)
> 	at com.microsoft.graph.planner.tasks.TasksRequestBuilder.post(TasksRequestBuilder.java:95)
> 	at org.example.Main.main(Main.java:39)
> ```

Apologies @Eleirbag89 @HermanShpryhau . Realised this doesn't work because the `assignments` property is sent as a JSON string instead of an object. Will investigate the root cause further

**Comment by freelancer1845** [comment]
Is there an alternative to assign users to planner tasks? I'm having the same problem...

**Comment by HermanShpryhau** [comment]
As a temporary solution, I just constructed a json string according to the format in the docs, and sent a request with it via `WebClient`. Mind that you will need to do some kind of authentication yourself with this approach.

**Comment by felipecrp** [comment]
Hi, 

I was trying to retrieve the users assigned to a task and I got a similar problem. 

In the following:

https://github.com/microsoftgraph/msgraph-sdk-java/blob/c1aba5294c36df0d4372e5ee0ae177a3a15db177/src/main/java/com/microsoft/graph/generated/models/PlannerAssignments.java#L42C32-L42C49

We can observe that the `getAdditionalData()` uses an `Object` instead of `PlannerAssignment` .

How can I handle  the `getAdditionalData()`  to get the user information?

Regards,
Felipe

**Comment by baywet** [comment]
> As a temporary solution, I just constructed a json string according to the format in the docs, and sent a request with it via `WebClient`. Mind that you will need to do some kind of authentication yourself with this approach.

There's a better "alternative" to this. [see this documentation](https://github.com/microsoftgraph/msgraph-sdk-java-core?tab=readme-ov-file#2-getting-started) to make arbitrary requests (not using the fluent API surface) but still maintain part of the SDK infrastructure (authentication, retry, redirect, etc...) that you get when using the fluent API surface.

**Comment by baywet** [comment]
Also for clarity the full SDK support (in the service/fluent library) depends on this item https://github.com/microsoft/kiota/issues/62
