### ISSUE TITLE
Configuring GraphServiceClient with no scope throws UnsupportedOperationException during runtime

### ISSUE THREAD

**Issue by joakibj** [microsoftgraph/msgraph-sdk-java#1882]
### Expected behavior

Initializing `GraphServiceClient` with no scope argument should default to scope `https://graph.microsoft.com/.default` when using `azure-identity` `TokenCredential` and fetch the token

### Actual behavior

Attempt to fetch Azure token fails with `UnsupportedOperationException` during runtime

### Steps to reproduce the behavior

Java version:
```
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
```
Include on classpath:
```
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph</artifactId>
	<version>6.4.0</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-identity</artifactId>
	<version>1.11.3</version>
</dependency>
```

Implement the following code:
```
public class MsGraphConsumer {
	private final GraphServiceClient graphClient;

	public MsGraphConsumer(AzureProperties azureProperties) {
		ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				.tenantId(azureProperties.appTenantId())
				.clientId(azureProperties.appClientId())
				.clientSecret(azureProperties.appClientSecret())
				.build();
		this.graphClient = new GraphServiceClient(clientSecretCredential);
	}

	public Optional<User> getUser(String orgInternalId) {
		try {
			List<User> res = graphClient
					.users()
					.get(requestConfiguration -> {
						requestConfiguration.headers.add("ConsistencyLevel", "eventual");
						requestConfiguration.queryParameters.filter = "onPremisesSamAccountName eq '" + orgInternalId + "'";
						requestConfiguration.queryParameters.count = true;
						requestConfiguration.queryParameters.select = new String[]{"id"};
					}).getValue();
			if (res.isEmpty()) {
				return Optional.empty();
			}
			return Optional.of(res.get(0));
		} catch (ApiException e) {
			throw e;
		}
	}
}
```

Execute the method `msGraphConsumer.getUser("hello")`. Observe the following stacktrace:

```
java.lang.UnsupportedOperationException: null
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at com.microsoft.kiota.authentication.AzureIdentityAccessTokenProvider.getAuthorizationToken(AzureIdentityAccessTokenProvider.java:133)
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:46)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:709)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
	at com.microsoft.graph.users.UsersRequestBuilder.get(UsersRequestBuilder.java:120)
	at com.github.example.MsGraphConsumer.getUser(MsGraphConsumer.java:53)
```

### Workaround

Set the scope directly or initialise `scopes` as null:
```
new GraphServiceClient(clientSecretCredential, "https://graph.microsoft.com/.default");
new GraphServiceClient(clientSecretCredential,  null);
```

### Authors remarks

Looks like this is due to `com.microsoft.kiota.authentication.AzureIdentityAccessTokenProvider:66` assigns scopes using the `Arrays.ArrayList` type that does not implement `add`

**Comment by baywet** [comment]
Hi @joakibj 
Thanks for reporting this and using the java SDK.
This is an implementation drift of the java implementation.
When comparing [java](https://github.com/microsoft/kiota-java/blob/6adfe09e71c91cb3c7fe5489d05928e737547389/components/authentication/azure/src/main/java/com/microsoft/kiota/authentication/AzureIdentityAccessTokenProvider.java#L132) with [dotnet](https://github.com/microsoft/kiota-authentication-azure-dotnet/blob/c93b68028d607dcccfc58e9e6750a65b26be2e09/src/AzureIdentityAccessTokenProvider.cs#L87) we can see that dotnet makes a copy of the array to avoid impacting the user-provided value.
The java implementation should be updated to match this implementation.
Is this something you'd be willing to submit a pull request for?

**Comment by joakibj** [comment]
Hello @baywet
Sure, please see the linked pull request
