### ISSUE TITLE
Upgrade from 1.9.0 to 5.80.0

### ISSUE THREAD

**Issue by andreastheodosiou** [microsoftgraph/msgraph-sdk-java#1884]
### Expected behavior
Am trying to upgrade from Microsoft Graph 1.9.0 to 5.80.0. I copied pasted the exact code from https://learn.microsoft.com/en-us/graph/sdks/create-client?tabs=java and tried to test. 

### Actual behavior
The last line in the code below gives me an error in Eclipse with the only solution to remove the parameters from the constructor. When removing them it gives me another error that the constructor is not visible. 

### Steps to reproduce the behavior
First error (before removing parameters from constructor).
**The constructor GraphServiceClient(ClientSecretCredential, String[]) is undefined**

When removing the parameters I get 
The constructor GraphServiceClient() is not visible

Dependancies
<dependency>
	    <groupId>com.microsoft.azure</groupId>
	    <artifactId>msal4j</artifactId>
	    <version>1.14.3</version>
	</dependency>
	<dependency>
	    <groupId>com.microsoft.graph</groupId>
	    <artifactId>microsoft-graph</artifactId>
	    <version>5.80.0</version>
	</dependency>
	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-identity</artifactId>
	    <version>1.3.0</version>
	</dependency>		
	<dependency>
	    <groupId>com.microsoft.graph</groupId>
	    <artifactId>microsoft-graph-auth</artifactId>
	    <version>0.3.0</version>
	</dependency>

Code
......
import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.microsoft.graph.requests.GraphServiceClient;
....
public void testEmail() {
	final String clientId = "YOUR_CLIENT_ID";
	final String tenantId = "YOUR_TENANT_ID";
	final String clientSecret = "YOUR_CLIENT_SECRET";
	// The client credentials flow requires that you request the
	// /.default scope, and pre-configure your permissions on the
	// app registration in Azure. An administrator must grant consent
	// to those permissions beforehand.
	final String[] scopes = new String[] { "https://graph.microsoft.com/.default" };
	final ClientSecretCredential credential = new ClientSecretCredentialBuilder()
	    .clientId(clientId).tenantId(tenantId).clientSecret(clientSecret).build();
	if (null == scopes || null == credential) {
	    throw new Exception("Unexpected error");
	}
	final GraphServiceClient graphClient = new GraphServiceClient(credential, scopes);
}

**Comment by andreastheodosiou** [comment]
Philip thanks
A lot has changed from 5 to 6 as well. I re-implemented the parts of our code affected.
I get the below now can you please guide as to the issue?

15:47:28.618 [Thread-7] INFO  inspireObjectsCommonQueueManagerClasses.JMSConsumer - On error: java.lang.RuntimeException: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [io.github.stduritemplate.StdUriTemplate])
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119)
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:73)
       at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390)
       at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
       at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
       at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
       at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
       at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
       at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
       at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
       at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
       at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedClassVersionError: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [io.github.stduritemplate.StdUriTemplate])
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2377)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:846)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1313)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1172)
       at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.getRequestFromRequestInformation(OkHttpRequestAdapter.java:873)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:713)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
       at com.microsoft.graph.users.item.mailfolders.item.messages.MessagesRequestBuilder.get(MessagesRequestBuilder.java:93)
       at inspire.graph.service.NA_Graph.readEmail_on_unique_id(NA_Graph.java:704)
       at inspire.graph.service.NA_Graph.parseMsg(NA_Graph.java:1334)
       at crmCoreClasses.AlfrescoMgnt.multiEmailsTask(AlfrescoMgnt.java:2538)
       at crmCoreClasses.AlfrescoMgnt.processData(AlfrescoMgnt.java:5204)
       at inspireObjectsCoreClasses.Dispatcher.onMessage(Dispatcher.java:1319)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:71)
       ... 18 more
Graph dependencies
              <dependency>
                  <groupId>com.microsoft.azure</groupId>
                  <artifactId>msal4j</artifactId>
                  <version>1.14.3</version>
              </dependency>
              <dependency>
                  <groupId>com.azure</groupId>
                  <artifactId>azure-identity</artifactId>
                  <version>1.11.2</version>
              </dependency>
              <dependency>
                  <groupId>com.microsoft.graph</groupId>
                  <artifactId>microsoft-graph</artifactId>
                  <version>6.4.0</version>
              </dependency>
              <dependency>
                  <groupId>com.microsoft.graph</groupId>
                  <artifactId>microsoft-graph-auth</artifactId>
                  <version>0.3.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-core</artifactId>
                  <version>2.17.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
                  <version>2.17.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-annotations</artifactId>
                  <version>2.17.0</version>
              </dependency>

**Comment by andreastheodosiou** [comment]
To support; the call raising the exception from our code is
MessageCollectionResponse messageResponse = graphClient.users().byUserId(from)
                                                       .mailFolders().byMailFolderId(folder)
                                                       .messages().get( requestConfiguration -> {
                                                                                requestConfiguration.queryParameters.filter = "internetMessageId eq '" + unique_message_id + "'";
                                                      });

From: Andreas Theodosiou
Sent: Sunday, March 17, 2024 3:53 PM
To: microsoftgraph/msgraph-sdk-java ***@***.***>; microsoftgraph/msgraph-sdk-java ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoftgraph/msgraph-sdk-java] Upgrade from 1.9.0 to 5.80.0 (Issue #1884)

Philip thanks
A lot has changed from 5 to 6 as well. I re-implemented the parts of our code affected.
I get the below now can you please guide as to the issue?

15:47:28.618 [Thread-7] INFO  inspireObjectsCommonQueueManagerClasses.JMSConsumer - On error: java.lang.RuntimeException: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [io.github.stduritemplate.StdUriTemplate])
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119)
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:73)
       at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390)
       at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
       at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
       at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
       at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
       at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
       at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
       at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
       at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
       at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedClassVersionError: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [io.github.stduritemplate.StdUriTemplate])
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2377)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:846)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1313)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1172)
       at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.getRequestFromRequestInformation(OkHttpRequestAdapter.java:873)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:713)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
       at com.microsoft.graph.users.item.mailfolders.item.messages.MessagesRequestBuilder.get(MessagesRequestBuilder.java:93)
       at inspire.graph.service.NA_Graph.readEmail_on_unique_id(NA_Graph.java:704)
       at inspire.graph.service.NA_Graph.parseMsg(NA_Graph.java:1334)
       at crmCoreClasses.AlfrescoMgnt.multiEmailsTask(AlfrescoMgnt.java:2538)
       at crmCoreClasses.AlfrescoMgnt.processData(AlfrescoMgnt.java:5204)
       at inspireObjectsCoreClasses.Dispatcher.onMessage(Dispatcher.java:1319)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:71)
       ... 18 more
Graph dependencies
              <dependency>
                  <groupId>com.microsoft.azure</groupId>
                  <artifactId>msal4j</artifactId>
                  <version>1.14.3</version>
              </dependency>
              <dependency>
                  <groupId>com.azure</groupId>
                  <artifactId>azure-identity</artifactId>
                  <version>1.11.2</version>
              </dependency>
              <dependency>
                  <groupId>com.microsoft.graph</groupId>
                  <artifactId>microsoft-graph</artifactId>
                  <version>6.4.0</version>
              </dependency>
              <dependency>
                  <groupId>com.microsoft.graph</groupId>
                  <artifactId>microsoft-graph-auth</artifactId>
                  <version>0.3.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-core</artifactId>
                  <version>2.17.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
                  <version>2.17.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-annotations</artifactId>
                  <version>2.17.0</version>
              </dependency>

**Comment by andreastheodosiou** [comment]
Dear Philip as a kind reminder

From: Andreas Theodosiou
Sent: Monday, March 18, 2024 6:31 PM
To: 'microsoftgraph/msgraph-sdk-java' ***@***.***>; 'microsoftgraph/msgraph-sdk-java' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [microsoftgraph/msgraph-sdk-java] Upgrade from 1.9.0 to 5.80.0 (Issue #1884)

To support; the call raising the exception from our code is
MessageCollectionResponse messageResponse = graphClient.users().byUserId(from)
                                                       .mailFolders().byMailFolderId(folder)
                                                       .messages().get( requestConfiguration -> {
                                                                                requestConfiguration.queryParameters.filter = "internetMessageId eq '" + unique_message_id + "'";
                                                      });

From: Andreas Theodosiou
Sent: Sunday, March 17, 2024 3:53 PM
To: microsoftgraph/msgraph-sdk-java ***@***.******@***.***>>; microsoftgraph/msgraph-sdk-java ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [microsoftgraph/msgraph-sdk-java] Upgrade from 1.9.0 to 5.80.0 (Issue #1884)

Philip thanks
A lot has changed from 5 to 6 as well. I re-implemented the parts of our code affected.
I get the below now can you please guide as to the issue?

15:47:28.618 [Thread-7] INFO  inspireObjectsCommonQueueManagerClasses.JMSConsumer - On error: java.lang.RuntimeException: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [io.github.stduritemplate.StdUriTemplate])
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119)
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:73)
       at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390)
       at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
       at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
       at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
       at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
       at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
       at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
       at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
       at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
       at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedClassVersionError: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [io.github.stduritemplate.StdUriTemplate])
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2377)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:846)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1313)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1172)
       at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.getRequestFromRequestInformation(OkHttpRequestAdapter.java:873)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:713)
       at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
       at com.microsoft.graph.users.item.mailfolders.item.messages.MessagesRequestBuilder.get(MessagesRequestBuilder.java:93)
       at inspire.graph.service.NA_Graph.readEmail_on_unique_id(NA_Graph.java:704)
       at inspire.graph.service.NA_Graph.parseMsg(NA_Graph.java:1334)
       at crmCoreClasses.AlfrescoMgnt.multiEmailsTask(AlfrescoMgnt.java:2538)
       at crmCoreClasses.AlfrescoMgnt.processData(AlfrescoMgnt.java:5204)
       at inspireObjectsCoreClasses.Dispatcher.onMessage(Dispatcher.java:1319)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.apache.tomcat.websocket.pojo.PojoMessageHandlerPartialBase.onMessage(PojoMessageHandlerPartialBase.java:71)
       ... 18 more
Graph dependencies
              <dependency>
                  <groupId>com.microsoft.azure</groupId>
                  <artifactId>msal4j</artifactId>
                  <version>1.14.3</version>
              </dependency>
              <dependency>
                  <groupId>com.azure</groupId>
                  <artifactId>azure-identity</artifactId>
                  <version>1.11.2</version>
              </dependency>
              <dependency>
                  <groupId>com.microsoft.graph</groupId>
                  <artifactId>microsoft-graph</artifactId>
                  <version>6.4.0</version>
              </dependency>
              <dependency>
                  <groupId>com.microsoft.graph</groupId>
                  <artifactId>microsoft-graph-auth</artifactId>
                  <version>0.3.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-core</artifactId>
                  <version>2.17.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-databind</artifactId>
                  <version>2.17.0</version>
              </dependency>
              <dependency>
                  <groupId>com.fasterxml.jackson.core</groupId>
                  <artifactId>jackson-annotations</artifactId>
                  <version>2.17.0</version>
              </dependency>

**Comment by Ndiritu** [comment]
@andreastheodosiou sorry for the delayed update here.
The issue with the compiled Java version of the StdUriTemplate library was fixed.
Kindly upgrade to our latest release and feel free to re-open if you face the same issue.
