### ISSUE TITLE
Possible regression for Entra ID group requests in 6.5.1

### ISSUE THREAD

**Issue by etcoyvindf** [microsoftgraph/msgraph-sdk-java#1913]
There seems to be a regression in either the graph core java library or in msgraph-sdk-java after updating the library versions. My apologies if this bug belongs  in the core-project.

### Expected behavior

When calling a graphClient method to get a specific group with members:
`graphClient.groups().byGroupId("<groupUUID>").get(rc -> rc.queryParameters.expand = new String[] {"members"})`

This returns a Group object with members populated.

### Actual behavior
Running the same code with core 3.1.7 and graph 6.5.1 produces the following exception:

```
java.lang.IllegalStateException: Not a JSON Array: { <actual response JSON snipped out>}
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:117) ~[gson-2.10.1.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:167) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.getUntypedValue(JsonParseNode.java:245) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.tryGetAnything(JsonParseNode.java:317) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:299) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213) ~[microsoft-kiota-serialization-json-1.1.2.jar:?]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:296) ~[microsoft-kiota-http-okHttp-1.1.2.jar:?]
	at com.microsoft.graph.groups.item.GroupItemRequestBuilder.get(GroupItemRequestBuilder.java:468) ~[microsoft-graph-6.5.1.jar:?]
... the rest of the stacktrace is project internal from calling `graphClient.groups().byGroupId("<groupUUID>").get(rc -> rc.queryParameters.expand = new String[] {"members"})`
```

### Steps to reproduce the behavior

Update Graph Core from 3.1.6 to 3.1.7 and Graph SDK from 6.4.0 to 6.5.1

**Comment by andrueastman** [comment]
Thanks for raising this @etcoyvindf 

This is tracked via https://github.com/microsoft/kiota-java/issues/1147 and will be resolved via https://github.com/microsoft/kiota-java/pull/1148

**Comment by etcoyvindf** [comment]
Thank you for the quick reply @andrueastman  if it's alright with you, this bug can be closed from this repo.
