### ISSUE TITLE
Groups delta call can not be deserialized with 6.x

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#1916]
I am trying to make a call to the groups endpoint with delta functionality.
Platform is Android, graph sdk 6.5.1

`com.microsoft.graph.groups.delta.DeltaGetResponse groupDeltaResponse = graphClient.groups().delta().get();`

### Expected behavior

I get a GroupDeltaResponse object.

### Actual behavior
(i have replaced ids etc with x)
java.lang.IllegalStateException: Not a JSON Array: {"createdDateTime":"2019-10-11T10:07:54Z","displayName":"x","mailEnabled":false,"mailNickname":"x","renewedDateTime":"2019-10-11T10:07:54Z","securityEnabled":true,"securityIdentifier":"x","visibility":null,"id":"x","members@delta":[{"@odata.type":"#microsoft.graph.user","id":"x"}]}
at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:117)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:167)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.getUntypedValue(JsonParseNode.java:245)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.tryGetAnything(JsonParseNode.java:317)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:299)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.lambda$getCollectionOfObjectValues$1(JsonParseNode.java:195)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode$$ExternalSyntheticLambda1.apply(D8$$SyntheticClass:0)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:175)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.getCollectionOfObjectValues(JsonParseNode.java:195)
                                                 	at com.microsoft.graph.groups.delta.DeltaGetResponse.lambda$getFieldDeserializers$0$com-microsoft-graph-groups-delta-DeltaGetResponse(DeltaGetResponse.java:36)
                                                 	at com.microsoft.graph.groups.delta.DeltaGetResponse$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass:0)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:297)
                                                 	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213)
                                                 	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:296)

### Steps to reproduce the behavior

Make a delta call to the groups service with the java graph sdk

If i use graph explorer i get valid json as a response. Maybe there is an error in the kiota mapping for this response?
the group that throws the error is the second in the result set and has a members@delta object while the first did not have that, maybe this is the culprit?

**Comment by andrueastman** [comment]
Thanks for raising this @slowcar 

This should be resolved with https://github.com/microsoft/kiota-java/releases/tag/v1.1.3 which should be part of the next SDK release. You can also add a reference to it directly to the project in the meantime.
