### ISSUE TITLE
Add application and service principal owner with msgraph-sdk-java

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-java#1918]
_[This question was originally posted on [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/1618545/add-application-and-service-principal-owner-with-m)]_

Following the documentation, I tried to add an owner for an application and a service principal as follows:

```java
val referenceCreate= ReferenceCreate()
referenceCreate.odataId = "https://graph.microsoft.com/v1.0/directoryObjects/$owner"

graphClient.applications().byApplicationId(application.id.toString()).owners().ref().post(referenceCreate)
graphClient.servicePrincipals().byServicePrincipalId(servicePrincipal.id.toString()).owners().ref().post(referenceCreate)
```

This code leads to an Exception like:

```java
com.microsoft.graph.models.odataerrors.ODataError: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.

	at com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36)
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:210)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672)
	at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.sendPrimitive(OkHttpRequestAdapter.java:341)
	at com.microsoft.graph.serviceprincipals.item.owners.ref.RefRequestBuilder.post(RefRequestBuilder.java:105)
	at com.microsoft.graph.serviceprincipals.item.owners.ref.RefRequestBuilder.post(RefRequestBuilder.java:91)
	at xx.xxx.xxx.xxxxx.service.TestAppRegistrationService.create(TestAppRegistrationService.kt:52)
...
```

I can avoid this problem by creating two instances of ReferenceCreate:

```java
val applicationOwnerReference = ReferenceCreate()
val servicePrincipalOwnerReference = ReferenceCreate()

applicationOwnerReference.odataId = "https://graph.microsoft.com/v1.0/directoryObjects/$owner"
servicePrincipalOwnerReference.odataId = "https://graph.microsoft.com/v1.0/directoryObjects/$owner"

graphClient.applications().byApplicationId(application.id.toString()).owners().ref().post(applicationOwnerReference)
graphClient.servicePrincipals().byServicePrincipalId(servicePrincipal.id.toString()).owners().ref().post(applicationOwnerReference)
```

Can someone explain why this is happening? Is this behavior intended?

Regards, Michael

**Comment by ramsessanchez** [comment]
This behavior is due to the backing store. Basically, after the object is sent the first time the backing store kicks in and tracks whether any values have been changed, since the value for OdataID remains the same, the value is not parsed for the second request and we get a JSON value of `{}`. The behavior is partially explained [here](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v6.md#backing-store).  In order to avoid this, as we see above is to create two reference objects, an alternative is to add the following between the two post requests: 
``` java
        appOwnerRef.getBackingStore().setReturnOnlyChangedValues(false);
        appOwnerRef.getBackingStore().setIsInitializationCompleted(false);
```
