### ISSUE TITLE
Version 6.5.1: Retrieve an online meeting by joinWebUrl throw an exception

### ISSUE THREAD

**Issue by haotsang** [microsoftgraph/msgraph-sdk-java#1921]
situation: SDK upgraded from v5.80.0 to v6.5.1

1. I follow this document to write the code  [https://learn.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&amp;tabs=java#request-2](https://learn.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=java#request-2)

```kotlin
    fun getOnlineMeetings(joinWebUrl: String?): OnlineMeeting? {
        return try {
            val result = mClient.me().onlineMeetings().get { requestConfiguration ->
                requestConfiguration.queryParameters?.filter = "JoinWebUrl eq '$joinWebUrl'"
            }
            result?.value?.firstOrNull()
        } catch (e: Exception) {
            Log.e("GraphHelper", e.stackTraceToString())
            null
        }
    }
```

2. But a json exception was thrown

```
java.lang.IllegalStateException: Not a JSON Array: {"id":"xx","creationDateTime":"xxx"}
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:117)
	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:167)
	at com.microsoft.kiota.serialization.JsonParseNode.getUntypedValue(JsonParseNode.java:245)
	at com.microsoft.kiota.serialization.JsonParseNode.tryGetAnything(JsonParseNode.java:317)
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:299)
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213)
	at com.microsoft.kiota.serialization.JsonParseNode.lambda$getCollectionOfObjectValues$1(JsonParseNode.java:195)
	at com.microsoft.kiota.serialization.JsonParseNode$$ExternalSyntheticLambda1.apply(Unknown Source:4)
	at com.microsoft.kiota.serialization.JsonParseNode.iterateOnArray(JsonParseNode.java:175)
	at com.microsoft.kiota.serialization.JsonParseNode.getCollectionOfObjectValues(JsonParseNode.java:195)
	at com.microsoft.graph.models.OnlineMeetingCollectionResponse.lambda$getFieldDeserializers$0$com-microsoft-graph-models-OnlineMeetingCollectionResponse(OnlineMeetingCollectionResponse.java:34)
	at com.microsoft.graph.models.OnlineMeetingCollectionResponse$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:297)
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:213)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:296)
	at com.microsoft.graph.users.item.onlinemeetings.OnlineMeetingsRequestBuilder.get(OnlineMeetingsRequestBuilder.java:93)
	at com.azure.samples.communication.calling.graph.GraphHelper$getOnlineMeetings$2.invokeSuspend(GraphHelper.kt:101)
...
```

I don't know how to solve this error. Please help analyze the reason.

**Comment by haotsang** [comment]
same issue #1916 #1913
