### ISSUE TITLE
Azure Identity => ERROR in getToken() call for scopes [https://database.windows.net//.default]

### ISSUE THREAD

**Issue by CAP4168** [microsoftgraph/msgraph-sdk-java#1982]
Hello ,

I have my java spring boot application running on azure aks and i want to connect the azure sql bd to application via user assigned managed identity for achieving that i have enabled WordkloadIdentity on aks cluster and i added the below pom maven dependencies :
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.3.3</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>12.6.0.jre11</version>
			 <scope>runtime</scope>
		</dependency>
		
and i am getting the below error :

INFO [-,,,] 7 --- [ost-startStop-1] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@17772efd
2024-05-06T17:15:30.886680097Z 2024-05-06 13:15:30.885  INFO [-,,,] 7 --- [ost-startStop-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-05-06T17:15:32.550691266Z 2024-05-06 13:15:32.543 ERROR [-,,,] 7 --- [ost-startStop-1] c.a.i.implementation.IdentityClient      : ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
2024-05-06T17:15:32.564517243Z 2024-05-06 13:15:32.564 ERROR [-,,,] 7 --- [ost-startStop-1] c.a.identity.ManagedIdentityCredential   : Azure Identity => ERROR in getToken() call for scopes [https://database.windows.net//.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
2024-05-06T17:15:33.575927570Z 2024-05-06 13:15:33.574 ERROR [-,,,] 7 --- [ost-startStop-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
2024-05-06T17:15:33.575961571Z 
2024-05-06T17:15:33.575968871Z com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
2024-05-06T17:15:33.575975571Z 	at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$48(IdentityClient.java:1145)
2024-05-06T17:15:33.575982071Z 	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:57)
2024-05-06T17:15:33.575987671Z 	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:56)
2024-05-06T17:15:33.575993971Z 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
2024-05-06T17:15:33.575999871Z 	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopeP
assingSpanSubscriber.java:81)
2024-05-06T17:15:33.576007271Z 	at org.springframework.cloud.sleuth.instrument.reactor.LazySpanSubscriber.onNext(LazySpanSubscriber.java:52)
2024-05-06T17:15:33.576013971Z 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
2024-05-06T17:15:33.576019571Z 	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:62)
2024-05-06T17:15:33.576025272Z 	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:56)
2024-05-06T17:15:33.576030972Z 	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
2024-05-06T17:15:33.576036672Z 	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:56)
2024-05-06T17:15:33.576042872Z 	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
2024-05-06T17:15:33.576048772Z 	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:56)
2024-05-06T17:15:33.576054472Z 	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
2024-05-06T17:15:33.576060972Z 	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:56)
2024-05-06T17:15:33.576067172Z 	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
2024-05-06T17:15:33.576072772Z 	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:56)
2024-05-06T17:15:33.576078372Z 	at reactor.core.publisher.Mono.blockOptional(Mono.java:1219)
2024-05-06T17:15:33.576084772Z 	at com.microsoft.sqlserver.jdbc.SQLServerSecurityUtility.getManagedIdentityCredAuthToken(SQLServerSecurityUtility.java:353)
2024-05-06T17:15:33.576090372Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:6014)
2024-05-06T17:15:33.576095972Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5963)
2024-05-06T17:15:33.576101973Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5797)
2024-05-06T17:15:33.576122873
Z 	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:322)
2024-05-06T17:15:33.576129173Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:130)
2024-05-06T17:15:33.576134773Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)
2024-05-06T17:15:33.576140573Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6855)
2024-05-06T17:15:33.576145973Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5402)
2024-05-06T17:15:33.576155073Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5334)
2024-05-06T17:15:33.576161373Z 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
2024-05-06T17:15:33.576167773Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
2024-05-06T17:15:33.576173673Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3823)
2024-05-06T17:15:33.576179374Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3348)
2024-05-06T17:15:33.576185274Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3179)
2024-05-06T17:15:33.576190974Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1953)
2024-05-06T17:15:33.576197174Z 	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)
2024-05-06T17:15:33.576203074Z 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
2024-05-06T17:15:33.576208474Z 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
2024-05-06T17:15:33.576213974Z 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
2024-05-06T17:15:33.576219674Z 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
2024-05-06T17:15:33.576225574Z 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
202
4-05-06T17:15:33.576230974Z 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
2024-05-06T17:15:33.576236274Z 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
2024-05-06T17:15:33.576241674Z 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
2024-05-06T17:15:33.576263675Z 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
2024-05-06T17:15:33.576270775Z 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:319)
2024-05-06T17:15:33.576283175Z 	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:356)
2024-05-06T17:15:33.576289275Z 	at org.springframework.boot.autoconfigure.orm.jpa.DatabaseLookup.getDatabase(DatabaseLookup.java:72)
2024-05-06T17:15:33.576295175Z 	at org.springframework.boot.autoconfigure.orm.jpa.JpaProperties.determineDatabase(JpaProperties.java:166)
2024-05-06T17:15:33.576301175Z 	at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.jpaVendorAdapter(JpaBaseConfiguration.java:111)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration$$EnhancerBySpringCGLIB$$c175d457.CGLIB$jpaVendorAdapter$10(<generated>)
2024-05-06T17:15:33.576314175Z 	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration$$EnhancerBySpringCGLIB$$c175d457$$FastClassBySpringCGLIB$$2b786e2d.invoke(<generated>)
2024-05-06T17:15:33.576320075Z 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
2024-05-06T17:15:33.576333876Z 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
2024-05-06T17:15:33.576341476Z 	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration$$EnhancerBySpringCGLIB$$c175d457.jpaVendorAdapter(<generated>)
2024-05-06T17:15:33.576349476Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-05-06T17:15:33.576355376Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-05-06T17:15:33.576361376Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-05-06T17:15:33.576367176Z 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-05-06T17:15:33.576372876Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2024-05-06T17:15:33.576381276Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
2024-05-06T17:15:33.576387076Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
2024-05-06T17:15:33.576392876Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
2024-05-06T17:15:33.576399076Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBea

Need help on this.

**Comment by baywet** [comment]
Hi @CAP4168 
From looking at your stack trace, it doesn't seem you're using the Microsoft Graph SDK, but only the Azure SDK through Azure Identity.
The correct repository for this dependency is [this one](https://github.com/Azure/azure-sdk-for-java), please re-open an issue there.
Closing
