### ISSUE TITLE
Download file with size more than INT)MAX_VALUE failed - Using Graph 6.10.0

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#2009]
Hi,
I am trying to download file with 5GB
I am getting this exception:
2024-05-21 09:57:32,587 DEBUG [Thread-11205] (SPOWrapper:828) - Error in SPOWrapper::retrieveFileStream for path /PSR_BITRATE/5GB : For input string: "5368709120"
java.lang.NumberFormatException: For input string: "5368709120"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:721) ~[microsoft-kiota-http-okHttp-1.1.11.jar!/:?]
	at com.microsoft.kiota.http.OkHttpRequestAdapter.sendPrimitive(OkHttpRequestAdapter.java:338) ~[microsoft-kiota-http-okHttp-1.1.11.jar!/:?]
	at com.microsoft.graph.drives.item.items.item.content.ContentRequestBuilder.get(ContentRequestBuilder.java:78) ~[microsoft-graph-6.10.0.jar!/:?]
	at com.microsoft.graph.drives.item.items.item.content.ContentRequestBuilder.get(ContentRequestBuilder.java:65) ~[microsoft-graph-6.10.0.jar!/:?]
	at com.bmc.cm.aft.client.wrapper.SPOWrapper.retrieveFileStream(SPOWrapper.java:822) [classes!/:?]
	at com.bmc.cm.aft.client.wrapper.SPOWrapper.downloadFileToLocalFileSystem(SPOWrapper.java:873) [classes!/:?]
	at com.bmc.cm.aft.client.SPODownloadToLocalFileCopy.downloadFileToLocalFileSystem(SPODownloadToLocalFileCopy.java:69) [classes!/:?]
	at com.bmc.cm.aft.client.CloudFileCopy.copyFile(CloudFileCopy.java:144) [classes!/:?]
	at com.bmc.cm.aft.client.FileCopy.transfer(FileCopy.java:1669) [classes!/:?]
	at com.bmc.cm.aft.client.FileCopy.run(FileCopy.java:1500) [classes!/:?]
	at com.bmc.cm.aft.client.FTCTransfer.copySingleFile(FTCTransfer.java:925) [classes!/:?]
	at com.bmc.cm.aft.client.FTCTransfer.copy(FTCTransfer.java:802) [classes!/:?]
	at com.bmc.cm.aft.client.FTCTransfer.runCopy(FTCTransfer.java:383) [classes!/:?]
	at com.bmc.cm.aft.client.FTCTransfer.run(FTCTransfer.java:312) [classes!/:?]
	at com.bmc.cm.aft.client.SubtaskRunner.run(SubtaskRunner.java:628) [classes!/:?]
	at com.bmc.cm.aft.client.FTCHandler.runSubTasks(FTCHandler.java:388) [classes!/:?]
	at com.bmc.cm.aft.client.FTCHandler.runJob(FTCHandler.java:219) [classes!/:?]
	at com.bmc.cm.aft.jobmanagement.JobObjectImpl$JobRunnerThread.run(JobObjectImpl.java:401) [classes!/:?]

I can see that in file OkHttpRequestAdapter::getHttpResponseMessage
in line 719
  if (contentLengthHeaderValue != null && !contentLengthHeaderValue.isEmpty()) {
                final int contentLengthHeaderValueAsInt =
                        **Integer.parseInt(contentLengthHeaderValue);**
                spanForAttributes.setAttribute(
                        EXPERIMENTAL_HTTP_RESPONSE_BODY_SIZE, contentLengthHeaderValueAsInt);
            }

and it failed because the size is long and not int

Thanks,
Itay

**Comment by baywet** [comment]
Hi @ihudedi 
Thanks for using the SDK and for reporting this issue.
I authored https://github.com/microsoft/kiota-java/pull/1318 to address it.

**Comment by ihudedi** [comment]
Hi @baywet 
Do you know when the new version of kiota will be released?
Thanks,
Itay

**Comment by baywet** [comment]
of the dependencies, today. Of the generator itself on June 7th, but that's not a dependency for this issue.
