### ISSUE TITLE
API call is hanging

### ISSUE THREAD

**Issue by bibhas2** [microsoftgraph/msgraph-sdk-java#2140]
### Describe the bug

API call to get a list of recordings for an online meeting is hanging. Note:

1. The same Java code used to work fine until a few weeks ago. Nothing has changed in the Java code. Except now it hangs.
2. I can make the call successfully from Postman. 

```java
GraphServiceClient cli = makeClient();
String userId = ...;
String meetingId = ...;

//This is hanging
var response = cli
    .users()
    .byUserId(userId)
    .onlineMeetings()
    .byOnlineMeetingId(meetingId)
    .recordings()
    .get();
```

A thread dump shows a potential infinite loop.

```
java.lang.Thread.State: RUNNABLE
        at com.microsoft.kiota.store.InMemoryBackingStore.touchNestedProperties(InMemoryBackingStore.java:244)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:234)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:63)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
        at com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
        at com.microsoft.kiota.store.InMemoryBackingStore$$Lambda/0x0000022581e76478.accept(Unknown Source)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
        at com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
        at com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
        at com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
        at com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
```

My dependency as follows:

```
dependencies {
    // Use JUnit test framework.
    testImplementation libs.junit

    providedCompile 'javax:javaee-web-api:8.0'
    implementation 'com.azure:azure-identity:1.+'
    implementation 'com.microsoft.graph:microsoft-graph:6.6.0'
}
```

### Expected behavior

I should receive a list of recordings. This used to work before. Now the code hangs.

### How to reproduce

Use the [recording list API ](https://learn.microsoft.com/en-us/graph/api/onlinemeeting-list-recordings?view=graph-rest-1.0&tabs=http) from Java. Example code shown above.

I can make the API call fine from Postman.

![image](https://github.com/user-attachments/assets/88654435-6f65-40b8-8453-3353da8a711d)

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
Hi @bibhas2, do you still face this issue if you upgrade to version `6.14.0`?

**Comment by bibhas2** [comment]
Updating ``microsoft-graph`` to 6.14.0 has fixed the issue.
