### ISSUE TITLE
Unable to message: createForward Returning Null Pointer Exception

### ISSUE THREAD

**Issue by raghucha** [microsoftgraph/msgraph-sdk-java#2179]
### Describe the bug

As described in documentation [createForward](https://learn.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&tabs=java). The code functionality is broken 

It throws a Null Pointer exception

### Expected behavior

the below code is expected to create a Draft message 
`var result = graphClient.me().messages().byMessageId("{message-id}").createForward().post(null);
`

### How to reproduce

    graphServiceClient
            .users()
            .byUserId("replace@userid.com")
            .messages()
            .byMessageId("{replace-message-id}")
            .createForward().post(null);

### SDK Version

6.16.0

### Debug output

<details><summary>Click to expand log</summary>

`Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.microsoft.graph.users.item.messages.item.createforward.CreateForwardRequestBuilder.post(CreateForwardRequestBuilder.java:59)
	at com.microsoft.graph.users.item.messages.item.createforward.CreateForwardRequestBuilder.post(CreateForwardRequestBuilder.java:47)
	at org.example.Main.main(Main.java:97)`
</details>

**Comment by Ndiritu** [comment]
@raghucha thank you for creating this issue.

This is an issue with the code snippet. Passing a new "empty" body object should work:
```java
var result = graphClient.me().messages().byMessageId("{message-id}").createForward().post(new CreateForwardPostRequestBody()); 
```
Lmk if this helps.
