### ISSUE TITLE
null batchResponse when POSTing a batch request.

### ISSUE THREAD

**Issue by temt91** [microsoftgraph/msgraph-sdk-java#2255]
### Describe the bug

```
Caused by: java.lang.NullPointerException: The following parameter cannot be null: batchResponse
	at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
	at com.microsoft.graph.core.content.BatchResponseContent.<init>(BatchResponseContent.java:42) ~[microsoft-graph-core-3.2.1.jar:?]
	at com.microsoft.graph.core.requests.BatchRequestBuilder.post(BatchRequestBuilder.java:53) ~[microsoft-graph-core-3.2.1.jar:?]
	at com.microsoft.graph.serviceclient.CustomBatchRequestBuilder.post(CustomBatchRequestBuilder.java:41) ~[microsoft-graph-6.16.0.jar:?]
	at com.microsoft.graph.core.requests.BatchRequestBuilder.post(BatchRequestBuilder.java:67) ~[microsoft-graph-core-3.2.1.jar:?]
	at com.microsoft.graph.serviceclient.CustomBatchRequestBuilder.post(CustomBatchRequestBuilder.java:53) ~[microsoft-graph-6.16.0.jar:?]
```

```
2024-11-21T16:05:58 WARNING [TOMCAT] okhttp3.internal.platform.Platform log okhttp3.OkHttpClient - A connection to https://graph.microsoft.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

Our code started throwing a null pointer exception as shown in the logs. The code and requests normally run fine, however this error seems to have randomly occurred. Once we saw this error all subsequent requests to Azure also failed until the process was restarted.

Under what circumstances could this happen?

### Expected behavior

Requests complete successfully. Failed requests should throw an ApiException?

### How to reproduce

This does not occur under normal circumstances - the following code usually works fine.

We have seen the same error on two different underlying requests, wrapped in batch requests. 
`mGraphClient.users().byUserId(x).memberOf().graphGroup()` and `mGraphClient.groups().getByIds()`

An example:
```
ClientSecretCredential vCredential = new ClientSecretCredentialBuilder().clientId(mClientId).tenantId(mTenantId).clientSecret(mClientSecret).build();
mGraphClient = new GraphServiceClient(vCredential, "https://graph.microsoft.com/.default");

-----
BatchRequestContentCollection vBatchRequest = new BatchRequestContentCollection(mGraphClient);
for (String vId : pIds) {
  RequestInformation vRequestInfo = mGraphClient.users().byUserId(vId).memberOf().graphGroup().toGetRequestInformation(requestConfiguration -> {
	  requestConfiguration.queryParameters.select = new String[] { ID };
	  requestConfiguration.queryParameters.top = MAX_PAGE_SIZE;
  });
  vBatchRequest.addBatchRequestStep(vRequestInfo);
}

BatchResponseContentCollection vBatchResponse = mGraphClient.getBatchRequestBuilder().post(vBatchRequest, null);
```

### SDK Version

6.16.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by temt91** [comment]
Bumping - we haven't seen this reoccur but are being asked about it. Suggestions of a workaround if this was to happen again are welcome!

**Comment by temt91** [comment]
This has occurred in a few different environments but is rare. I've not been able to reproduce it, and had a look through the request code and couldn't see anything obvious as to what would cause this.

As a workaround I'm looking into wrapping the client in a manager and recreating it on a NullPointerException during a batch request. It's a bit awkward in a multithreaded environment compared to just having a single client to use.
