### ISSUE TITLE
Error when trying to download .JSON files from OneDrive

### ISSUE THREAD

**Issue by morganpobr** [microsoftgraph/msgraph-sdk-java#275]
I am trying to download a .json file from OneDrive. The following request patterns get the intended behavior (the file is downloaded) for other file types but none work for .json files.
InputStream driveItemInputStream = getGraphServiceClient().drives(driveId).items(driveItemId).content().buildRequest().get();
InputStream driveItemInputStream = getGraphServiceClient().drives().byId(driveId).items().byId(driveItemId).content().buildRequest().get();
InputStream driveItemInputStream = getGraphServiceClient().customRequest(("/drives/"+driveId+"/items/"+driveItemId+"/content"), InputStream.class).buildRequest().get();

Expected behavior
For the file to be downloaded.
Actual behavior
Error response:
com.microsoft.graph.core.ClientException: Error during http request
at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:368)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:204)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:184)
	at com.microsoft.graph.http.BaseStreamRequest.send(BaseStreamRequest.java:81)
	at com.microsoft.graph.requests.extensions.DriveItemStreamRequest.get(DriveItemStreamRequest.java:55)
...
Caused by: java.lang.RuntimeException: Failed to invoke public java.io.InputStream() with no args
	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:78)
	at com.microsoft.graph.http.DefaultHttpProvider.handleJsonResponse(DefaultHttpProvider.java:417)
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:342)
	... 46 more

Steps to reproduce the behavior
Use the SDK to make a GET request on a .json file in a user or group OneDrive using any of the request patterns above.
[AB#6032](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6032)

**Comment by bilalgce** [comment]
Thanks for reporting this issue. We're looking into it.

**Comment by bilalgce** [comment]
I'm able to reproduce this issue. I also confirm that this issue is happening only for .json files and not for other files.

**Comment by mthakare-onshape** [comment]
Any updates?

**Comment by Golg013** [comment]
It can be easily fixed by changing line #394 in CoreHttpProvider.java to

**Comment by baywet** [comment]
Hi everyone,
Thanks for the feedback, the fixes suggestions and the patience on the matter.
I just authored #470 which fixes that issue and will close it once merged.
