### ISSUE TITLE
Leaking connections when downloading content from OneDrive

### ISSUE THREAD

**Issue by PaulWoods4422** [microsoftgraph/msgraph-sdk-java#284]
Downloading content from OneDrive:
```
 try (InputStream req = graphClient.drives(driveId).items(docId).content().buildRequest().get()) {
            try (ByteArrayOutputStream result = new ByteArrayOutputStream()) {
//Get the content and use it - all OK
           }
}
The input and output streams are in try-with-resource blocks and so are closed at the end of the call.

In the log I then get the message:
OkHttpClient A connection to https://graph.microsoft.com/ was leaked. Did you forget to close a response body?
```

### Expected behavior

Calling close on the input stream should release the connection? Or there should be some other way to close it.

**Comment by heyalistair** [comment]
Also getting this.

FWIW, I think this is the relevant stack trace:

```
WARNING: A connection to https://graph.microsoft.com/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
        at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:148)
        at okhttp3.RealCall.captureCallStackTrace(RealCall.java:115)
        at okhttp3.RealCall.execute(RealCall.java:87)
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:355)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
        at com.microsoft.graph.http.BaseStreamRequest.send(BaseStreamRequest.java:85)
        at com.microsoft.graph.requests.extensions.DriveItemStreamRequest.get(DriveItemStreamRequest.java:55)
        at co.ohalo.msgraph.OneDriveConnector.downloadDataObject(OneDriveConnector.java:415)
        ...
```

**Comment by rocketraman** [comment]
Also getting this with 1.6.0.

**Comment by kozuch** [comment]
I am also getting this with 1.6.0.

```
Oct 29, 2019 2:30:18 ODP. okhttp3.internal.platform.Platform log
WARNING: A connection to https://xxx.sharepoint.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

**Comment by rocketraman** [comment]
Just updated to 1.7.1, and I'm still getting this error.

**Comment by rocketraman** [comment]
I suspect this is also, at least partially, causing other types of issues, like the connection resets reported in https://github.com/microsoftgraph/msgraph-sdk-java/issues/313 -- if the graph sdk server is getting overloaded with connections its gonna start dropping a few.

Come on guys, get your act together and fix this s*t.

**Comment by jdimeo** [comment]
I'm still getting this with 6.30.0 released yesterday
```
WARNING: A connection to https://graph.microsoft.com/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.kt:143)
	at okhttp3.internal.connection.Transmitter.callStart(Transmitter.kt:111)
	at okhttp3.RealCall.execute(RealCall.kt:63)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:747)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.sendPrimitive(OkHttpRequestAdapter.java:364)
	at com.microsoft.graph.drives.item.items.item.versions.item.DriveItemVersionItemRequestBuilder.delete(DriveItemVersionItemRequestBuilder.java:73)
	at com.microsoft.graph.drives.item.items.item.versions.item.DriveItemVersionItemRequestBuilder.delete(DriveItemVersionItemRequestBuilder.java:62)
```
