### ISSUE TITLE
Error deserializing singleValueExtendedProperties for Event

### ISSUE THREAD

**Issue by kmichae1** [microsoftgraph/msgraph-sdk-java#475]
Expected behavior
Tried to read the singleValueExtendedProperties for an Event like displayed here https://docs.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-get?view=graph-rest-1.0&tabs=java
This resulted in an error.
Actual behavior
The error was:
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2330 path $.value[0].singleValueExtendedProperties
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar:na]
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:83) ~[microsoft-graph-2.1.0.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:521) ~[microsoft-graph-2.1.0.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:397) ~[microsoft-graph-2.1.0.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204) ~[microsoft-graph-2.1.0.jar:na]
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184) ~[microsoft-graph-2.1.0.jar:na]
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:89) ~[microsoft-graph-2.1.0.jar:na]
	at com.microsoft.graph.requests.extensions.EventCollectionRequest.get(EventCollectionRequest.java:59) ~[microsoft-graph-2.1.0.jar:na]

The json in the response was as follows:
...
 "organizer":{
            "emailAddress":{
               "name":"asd asd",
               "address":"asd@asd.onmicrosoft.com"
            }
         },
         "singleValueExtendedProperties@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users('e100%40xxx.onmicrosoft.com')/calendarView('AAMkADU0OTVkZerI1LWIwZDEtNDU4Yi1hNmNiLTEwZDVmOGI4ZDU4NwBGAAAAAABPfoVdfLmdSoUd7XwV_6hTBwDGWVN6hvp7Q5YRPwG1kLELAAAAAAENAADGWVN6hvp7Q5YRPwG1kLELAAC4mkuPAAA%3D')/singleValueExtendedProperties",
         "singleValueExtendedProperties":[
            {
               "id":"String {9b799505-246e-4d9e-b047-75c58e61bb8c} Name TestId",
               "value":"1219774"
            }
         ]

Steps to reproduce the behavior
Made a query expanding the singleValueExtendedProperties.
[AB#6065](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6065)

**Comment by baywet** [comment]
Hey @kmichae1 
Thanks for the feedback.
The situation improved a little bit through fixes implemented in 2.2.0 as you can see in #495
However I still found issues with the current implementation which I addressed in #497.
Merging the PR will close this issue.
