### ISSUE TITLE
Assign manager

### ISSUE THREAD

**Issue by bender9978** [microsoftgraph/msgraph-sdk-java#575]
### Expected behavior
update user manager

### Actual behavior
return Bad Request

stacktrace:
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220Graph service exception Error code: Request_BadRequest
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220Error message: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220PUT https://graph.microsoft.com/v1.0/users/50cd9014-211b-4c65-9131-c5d2499f9d18/manager/$ref
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220SdkVersion : graph-java/v2.4.0
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220Authorization : [PII_REDACTED]
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220400 : Bad Request
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220[...]
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: CoreHttpProvider[send] - 220[Some information was truncated for brevity, enable debug logging for more details]
nov 27, 2020 12:54:46 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.

PUT https://graph.microsoft.com/v1.0/users/50cd9014-211b-4c65-9131-c5d2499f9d18/manager/$ref
SdkVersion : graph-java/v2.4.0
Authorization : [PII_REDACTED]
{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
nov 27, 2020 12:54:46 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [jsp] in context with path [/Intranet] threw exception [An exception occurred processing JSP page /test.jsp at line 47

44: 	DirectoryObject directoryObject = new DirectoryObject();
45: 	directoryObject.id = "a75c270f-1668-42e5-b36e-848ae7d20d5b";
46: 	
47: 	graphClient.users("50cd9014-211b-4c65-9131-c5d2499f9d18").manager().reference().buildRequest().put(directoryObject);
48: 	
49: %>

Stacktrace:] with root cause
com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.

PUT https://graph.microsoft.com/v1.0/users/50cd9014-211b-4c65-9131-c5d2499f9d18/manager/$ref
SdkVersion : graph-java/v2.4.0
Authorization : [PII_REDACTED]
{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:501)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
	at com.microsoft.graph.requests.extensions.DirectoryObjectReferenceRequest.put(DirectoryObjectReferenceRequest.java:85)
	at org.apache.jsp.test_jsp._jspService(test_jsp.java:117)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)

#### create client:

MsGraphAccessTokenProvider accessTokenProvider = MsGraphAccessTokenProvider //
			.tenantName(tenant) //
			.clientId(clientId) //
			.clientSecret(clientSecret) //
			.refreshBeforeExpiry(5, TimeUnit.MINUTES) //
			.build();

	MsGraphAuthenticationProvider authProvider = MsGraphAuthenticationProvider.from(accessTokenProvider);

	IGraphServiceClient graphClient = GraphServiceClient.builder() //
			.authenticationProvider(authProvider) //
			.buildClient();

#### update user manager:

DirectoryObject directoryObject = new DirectoryObject();
directoryObject.id = "50cd9014-211b-4c65-9131-c5d2499f9d18";
	
graphClient.users("a75c270f-1668-42e5-b36e-848ae7d20d5b").manager().reference().buildRequest().put(directoryObject);

**Comment by baywet** [comment]
Hi @bender9978 
Thanks for reaching out and thanks for all these details. Quick questions:
- is it something that used to work and stopped working on your side or is it net new development?
- can you provide a request id please?

**Comment by bender9978** [comment]
Hi @baywet ,
is new development, I don't have a request id, where can i find it?

**Comment by baywet** [comment]
thanks for the additional information
actually I think the request id is in your stacktrace
```json
{"id":"a75c270f-1668-42e5-b36e-848ae7d20d5b"}
```

**Comment by bender9978** [comment]
no, it is the user id

graphClient.users("a75c270f-1668-42e5-b36e-848ae7d20d5b").manager().reference().buildRequest().put(directoryObject);

**Comment by baywet** [comment]
It should be in the response headers as "client-request-id"

**Comment by bender9978** [comment]
I had enabled debug loggin.

{
  "error": {
    "code": "Request_BadRequest",
    "message": "An unexpected \u0027EndOfInput\u0027 node was found when reading from the JSON reader. A \u0027StartObject\u0027 node was expected.",
    "innerError": {
      "date": "2020-11-27T14:45:32",
      "request-id": "58c6f5f5-efeb-4ecb-8b41-028c6931bb06",
      "client-request-id": "203045e7-5398-46da-91f8-85c5bd219723"
    }
  }
}

**Comment by baywet** [comment]
Thanks, actually looking at the logs you provided, the payload looks wrong
`@odata.` is missing before the id for the field name.

**Comment by bender9978** [comment]
ok, I use the java sdk, I followed this example on url:
https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=java

```
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

DirectoryObject directoryObject = new DirectoryObject();
directoryObject.id = "{id}";

graphClient.users("{id}").manager().reference()
	.buildRequest()
	.put(directoryObject);
```

there is a problem on sdk?

I can't put `@odata` prefix on id filed name.

**Comment by baywet** [comment]
I was double checking before providing a definitive answer. Yes I can confirm it's a bug in the SDK, the SDK should understand that the $ref endpoint is a special case, abstract the id and format the payload properly, but it doesn't today.
I'm working on a fix

**Comment by baywet** [comment]
I just authored #576 . This fix is not perfect as it doesn't cover all the references cases, but it improves the situation for trivial cases (mostly users, groups, applications...).
Merging the PR will close this issue.

**Comment by baywet** [comment]
Update, as we made progress reviewing the PR, it appears the fix would introduce breaking change, so the release for the fix has been moved to version 3.
