### ISSUE TITLE
use api to download onedrive file failed.

### ISSUE THREAD

**Issue by yuanlincong** [microsoftgraph/msgraph-sdk-java#670]
this my code:
  SimpleAuthProvider authProvider = new SimpleAuthProvider("token");
        IGraphServiceClient buildClient = GraphServiceClient.builder().authenticationProvider(authProvider)
                .buildClient();
        IDriveItemCollectionPage iDriveItemCollectionPage = buildClient.me()
                .drives("driveId").items("itemId").children().buildRequest().get();

        List<DriveItem> currentPage = iDriveItemCollectionPage.getCurrentPage();
        for (DriveItem driveItem : currentPage) {
            System.out.println(driveItem.id + " ===== " + driveItem.name + " ===== " + driveItem.file);
            if (null != driveItem.file) {
                // get file inputstream,this step throw exception
                InputStream inputStream = buildClient.drives("driveId").items(driveItem.id).content().buildRequest()
                        .get();
                System.out.println(inputStream);
                inputStream.close(); 
            }
        }
### Expected behavior
success return file inputstream

### Actual behavior
throw exception,exception detail.
SEVERE: CoreHttpProvider[send] - 204Error during http request
Feb 19, 2021 6:01:42 AM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
com.microsoft.graph.core.ClientException: Error during http request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:422)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306)
        at com.microsoft.graph.http.CustomRequest.get(CustomRequest.java:43)
        at com.canto.dmc.repository.manager.Migrate202010Caption.process(Migrate202010Caption.java:52)
        at com.canto.dmc.repository.util.ContextProcessorHelper.initializer(ContextProcessorHelper.java:65)
        at com.canto.dmc.repository.manager.Migrate202010Caption.main(Migrate202010Caption.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Check failed.
        at okhttp3.internal.connection.Transmitter.prepareToConnect(Transmitter.kt:124)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:123)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:140)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:31)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:356)
        ... 15 more

### Steps to reproduce the behavior

how to resolve it?

 
[AB#8212](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8212)

**Comment by baywet** [comment]
Hi @yuanlincong 
Thanks for reaching out.
What version of the SDK and of the core library are you using? If not on latest (2.8.1 and 1.0.8) can you upgrade and see if you still run into the issue please?

**Comment by yuanlincong** [comment]
ok,i upgrade sdk version to 2.8.1,this problem has resolved,
thanks

**Comment by prashantguleria** [comment]
@baywet Hi, I was able to resolve the issue for now by updating the SDK version , but our productin servers stopped working due o this. 

So I would like to know how often the changes are done on service level. Are there any notifications before the service changes are done on MS graph? Ho can we make sure our code doen't break again on production and stop our process?

**Comment by baywet** [comment]
This is a really good question with a complex answer.
We have a set of rules and guidelines internally that document what would be a breaking change on the APIs, and what's the process to follow before doing so (giving 1 year of headway to the customers, making announcements...)
Of course sometimes mistakes happens (as rarely as possible) and guidelines might not anticipate every possible usage of the API. But we're working hard to make sure this happens as rarely as possible.

In terms of knowing about such changes, they are published on the [Microsoft Graph Blog](https://developer.microsoft.com/en-us/graph/blogs/) as well as an announcements in the Office 365 admin center.

Staying current on SDK versions goes a long way as we try to anticipate such changes in the SDK so it's transparent for developers.

**Comment by prashantguleria** [comment]
> This is a really good question with a complex answer.
> We have a set of rules and guidelines internally that document what would be a breaking change on the APIs, and what's the process to follow before doing so (giving 1 year of headway to the customers, making announcements...)
> Of course sometimes mistakes happens (as rarely as possible) and guidelines might not anticipate every possible usage of the API. But we're working hard to make sure this happens as rarely as possible.
> 
> In terms of knowing about such changes, they are published on the [Microsoft Graph Blog](https://developer.microsoft.com/en-us/graph/blogs/) as well as an announcements in the Office 365 admin center.
> 
> Staying current on SDK versions goes a long way as we try to anticipate such changes in the SDK so it's transparent for developers.

Thanks for quick revert.  
The frequent pathces of SDK will be difficult to apply on production without proper testing for atleast a month or so.
If my understanding is correct, SDK bugs/changes would be done frequently as compared to core service endpoint behavioural changes.
So, I think it's better to write own piece of code to do stuff using graph RESR API's instead of SDK dependency.

**Comment by baywet** [comment]
> So, I think it's better to write own piece of code to do stuff using graph REST API's instead of SDK dependency.

This is jumping to conclusions. Most of the core logic of the SDK is held in the -core library, which is handwritten and which the service library (this repo) depends on, this is where you have the most potential for bugs and such. And it's only as rarely as possible.
The service library being generated and not handwritten, has less potential for bugs so long as the metadata on the service is correct. And the metadata also impacts the service behaviour. If the metadata is wrong, or changed wrongfully it's likely that handwritten calls would be impacted as well. And again we have many failsafe measures and safeguards to try to avoid such regressions. The service library is generated weekly because the metadata is updated weekly. But 99% of the changes are additions (new endpoints made available) more than anything else. And the team validates the generation result via ~1000 unit tests before it gets published.

So, if your application is already using the SDK for a set of specific things (let's say OneDrive files management), and update on the service library is highly unlikely to break what your application is already using.
And the SDK altogether already handles many more scenarios you'd have to reimplement (retry handling, authN&authZ, serialization/deserialization, error handling...), you get a lot of value under the covers.
