### ISSUE TITLE
List service principal receives null pointer exception with a 302 code returned

### ISSUE THREAD

**Issue by paulojohnj** [microsoftgraph/msgraph-sdk-java#674]
### Expected behavior
GET https://graph.microsoft.com/v1.0/servicePrincipals

Expect to receive (A list of service principal objects):

`HTTP/1.1 200 OK
Content-type: application/json

{
  "value": [
    {
      "accountEnabled":true,
      "displayName":"amasf",
      "publisherName":"Contoso",
      "servicePrincipalType":"Application",
      "signInAudience":"AzureADMyOrg"
    }
  ]
}`

### Actual behavior

```
2021-02-22 15:06:25.433 EST defaultContext [main                   ] [user= project=] INFO  c.c.f.v.a.a.AzureCloudProviderTests - 1
2021-02-22 15:06:26.203 EST defaultContext [main                   ] [user= project=] INFO   - --> GET https://graph.microsoft.com/v1.0/servicePrincipals
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - Accept: */*
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - Accept-Encoding: gzip
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - Authorization: Bearer [REDACTED]
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - Connection: Keep-Alive
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - Host: graph.microsoft.com
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - SdkVersion: graph-java/v2.8.1
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - User-Agent: okhttp/3.12.1
2021-02-22 15:06:26.207 EST defaultContext [main                   ] [user= project=] INFO   - x-ms-client-request-id: [REDACTED]
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - <-- 302 Found https://graph.microsoft.com/v1.0/servicePrincipals (64 ms, 0-byte body)
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - Cache-Control: private
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - client-request-id: [REDACTED]
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - Content-Length: 0
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - Content-Type: text/plain
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - Date: Mon, 22 Feb 2021 20:06:25 GMT
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - request-id: [REDACTED]
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - Strict-Transport-Security: max-age=31536000
2021-02-22 15:06:26.272 EST defaultContext [main                   ] [user= project=] INFO   - x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"004","RoleInstance":"AGSFE_IN_14"}}
2021-02-22 15:06:26.273 EST defaultContext [main                   ] [user= project=] INFO   - 0-byte body:

2021-02-22 15:06:26.273 EST defaultContext [main                   ] [user= project=] INFO   - <-- END HTTP
2021-02-22 15:06:26.274 EST defaultContext [main                   ] [user= project=] WARN  c.c.f.v.a.a.AzureCloudProviderTests - caught exception NullPointerException with message: null
java.lang.NullPointerException
	at com.microsoft.graph.requests.extensions.ServicePrincipalCollectionRequest.buildFromResponse(ServicePrincipalCollectionRequest.java:156)
	at com.microsoft.graph.requests.extensions.ServicePrincipalCollectionRequest.get(ServicePrincipalCollectionRequest.java:61)
```

### Steps to reproduce the behavior

```
String clientId = this.credentials.clientId();
List<String> scopes = new ArrayList<>();
scopes.add("https://graph.microsoft.com/.default");
            
String clientSecret = this.credentials.clientSecret();
String tenant = this.credentials.domain();
            
final NationalCloud nationalCloud = NationalCloud.UsGovernment;
final ClientCredentialProvider authenticationProvider = new ClientCredentialProvider(clientId, scopes, clientSecret, tenant, nationalCloud)

this.graphClient = GraphServiceClient
                    .builder()
                    .authenticationProvider(authenticationProvider)
                    .buildClient();

IServicePrincipalCollectionPage servicePrincipalPage = this.graphClient.servicePrincipals().buildRequest().get()
```

This call and others surrounding service principals worked for me about 2 months ago, however the version of the SDK has advanced since then and I updated to match. Since then no call related to service principals has worked for me via the sdk. And after upping the logging, I noticed the calls are all receiving 302 found http codes, with no bodies or location header.

Any information on how to move forward and leverage the graph api for interacting with service principals would be greatly appreciated. I was pointed to this api after submitting a ticket with the general azure sdk for java, as it has a bug when updating service principals: <https://github.com/Azure/azure-libraries-for-java/issues/1290> 
[AB#8246](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8246)

**Comment by baywet** [comment]
Hi @paulojohnj 
Thanks for reaching out.
Are you working on the [Government cloud](https://docs.microsoft.com/en-us/graph/deployments) ? If not, can you please try again replacing `NationalCloud.UsGovernment` by `NationalCloud.Global` please?

Also, can you share with us which version of the microsoft-graph-core library you are using? You can get that information by typing `gradle dependencies` (if you're using gradle). And if you're not on 1.0.8 can you upgrade core and try again please?

Lastly, can you make sure you're on version 0.3.0-SNAPSHOT of the microsoft-graph-auth library please?

Thanks!

**Comment by paulojohnj** [comment]
I am working on both the global and government cloud. 

Core: com.microsoft.graph:microsoft-graph-core:jar:1.0.8:compile

Lastly I am on 0.3.0 of the microsoft-graph-auth library: com.microsoft.graph:microsoft-graph-auth:jar:0.3.0:compile
however that is not a snapshot dependency to my knowledge:

<dependency>
        <groupId>com.microsoft.graph</groupId>
        <artifactId>microsoft-graph-auth</artifactId>
        <version>0.3.0</version>
    </dependency>

I would like to  avoid having to use any snapshots to make this work as it is destined for a production system, however can do so to debug.

**Comment by baywet** [comment]
Thanks for sharing these details with us. You are on the latest versions of the different libraries at this moment.
My next question on which you're already working: are you seeing that behavior only for the Gov cloud of for the public one?
We (the SDK team) do not have access to government environments for security reasons, so it'll be hard for us to investigate/debug/solve any issue which would be related to this cloud.

However when looking at your logs I noticed something: the request is going to the public cloud `https://graph.microsoft.com/v1.0/servicePrincipals` instead of the government instance of the service `https://graph.microsoft.us/v1.0/servicePrincipals`. (note the TLD in .us instead of .com).

You can correct that behavior by calling

```Java
graphClient.setServiceRoot("https://graph.microsoft.us/v1.0");
```
When initializing your client.
Can you please also try the following and see whether it resolves your issue?

**Comment by paulojohnj** [comment]
Thank you! I assumed setting the national cloud would set the required fields. After changing the service root to the gov address and similarly updating the scope to be the `.us` extension, the call worked.

**Comment by baywet** [comment]
perfect! Thanks for sharing the result with the broader community. Closing.
