### ISSUE TITLE
IDriveItemCollectionPage is not retrievable with shared IGraphServiceClient in multi threaded environment

### ISSUE THREAD

**Issue by Noushed** [microsoftgraph/msgraph-sdk-java#719]
### Expected behavior
IDriveItemCollectionPage is retrievable with shared IGraphServiceClient in multi threaded environment

### Actual behavior
java.io.InterruptedIOException is thrown

`SEVERE: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
Exception in thread "Aqua L&F File Loading Thread" com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:92)
	at com.microsoft.graph.requests.extensions.DriveItemCollectionRequest.get(DriveItemCollectionRequest.java:65)
	........
        ........
	at java.desktop/com.apple.laf.AquaFileSystemModel$FilesLoader.run(AquaFileSystemModel.java:404)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.java:146)
	at okio.Okio$1.write(Okio.java:76)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)`

In windows: It works after several retries
In macOS: If we increase max retry value to a higher constant, it hardly works

### Steps to reproduce the behavior

microsoft-graph version: 2.10.0 or 2.9.0
microsoft-graph-auth version: 0.3.0

IDriveItemCollectionPage page = client
			.drives(rootFile.getDriveId())
			.root()
			.children()
			.buildRequest()
			.get();

 
[AB#8880](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8880)

**Comment by baywet** [comment]
Hi @Noushed,
Thanks for reaching out. Can you upgrade to the latest v3 of the SDK and see if you're still experiencing the same issues please?
Additionally, the v3 [provides a CompletableFuture API surface](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v3.md#futures-vs-callbacks) which aims to make multithreaded work much easier than the previous callback API surface.

**Comment by Noushed** [comment]
> Hi @Noushed,
> Thanks for reaching out. Can you upgrade to the latest v3 of the SDK and see if you're still experiencing the same issues please?
> Additionally, the v3 [provides a CompletableFuture API surface](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v3.md#futures-vs-callbacks) which aims to make multithreaded work much easier than the previous callback API surface.

Hi @baywet,

Thanks for the advice. I updated to v3 (3.2.0) but still getting similar error for retrieving DriveItemCollectionPage,

`14:49:21.650 [ForkJoinPool.commonPool-worker-19] INFO  c.a.i.AuthorizationCodeCredential - Azure Identity => getToken() result for scopes [Files.ReadWrite.All, offline_access, User.Read]: SUCCESS
Exception in thread "Aqua L&F File Loading Thread" com.microsoft.graph.core.ClientException: Error executing the request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:388)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:214)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:191)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:102)
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
	........
        ........
	at java.desktop/com.apple.laf.AquaFileSystemModel$FilesLoader.run(AquaFileSystemModel.java:404)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: java.lang.InterruptedException
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:385)
	... 8 more
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:55)`



14:48:41.388 [ForkJoinPool.commonPool-worker-19] INFO  c.a.i.AuthorizationCodeCredential - Azure Identity => getToken() result for scopes [Files.ReadWrite.All, offline_access, User.Read]: SUCCESS
Exception in thread "Aqua L&F File Loading Thread" com.microsoft.graph.core.ClientException: Error executing the request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:388)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:214)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:191)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:102)
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
	.........
        .........
	at java.desktop/com.apple.laf.AquaFileSystemModel$FilesLoader.run(AquaFileSystemModel.java:404)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.kt:98)
	at okio.OutputStreamSink.write(JvmOkio.kt:50)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
	at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.kt:155)

**Comment by baywet** [comment]
are you using the async API or the synchronous one? Can you share more code on how you setup the client?

**Comment by Noushed** [comment]
> are you using the async API or the synchronous one? Can you share more code on how you setup the client?

@baywet 

The shared client:

```
private static volatile TokenCredentialAuthProvider authProvider;
public static synchronized GraphServiceClient getClient() {
		try {
			return createClient();
		} catch (IOException e) {
			LOG.error("Unable to create the OneDrive client.", e);
			throw new IllegalStateException("Unable to create the OneDrive client.", e);
		}
	}

	private static GraphServiceClient createClient() throws IOException {
		if (authProvider == null) {
			synchronized (CLIENT) {
				if (authProvider == null) {
					OneDriveAuthServer server = new OneDriveAuthServer(OneDriveConstants.PORT);
					String authorizeUrl = AUTHORIZATION_SERVER_URL + "?client_id=" + OneDriveConstants.CLIENT_ID
							+ "&scope=Files.ReadWrite.All+User.Read+offline_access+User.Read" + "&response_type=code"
							+ "&response_mode=query" + "&redirect_uri=" + OneDriveConstants.REDIRECT_URI;
					BrowserLauncher.openURL(authorizeUrl);

					OneDriveAuthServer.AUTHLOCK.acquireUninterruptibly();
					String code = server.close();
					OneDriveAuthServer.AUTHLOCK.release();
					if (code == null) {
						throw new IOException("Code was null: for lock: " + OneDriveAuthServer.AUTHLOCK);
					}

					AuthorizationCodeCredential authCodeCredential = new AuthorizationCodeCredentialBuilder()
						    .clientId(OneDriveConstants.CLIENT_ID)
						    .authorizationCode(code)
						    .redirectUrl(OneDriveConstants.REDIRECT_URI)
						    .build();
					authProvider = new TokenCredentialAuthProvider(List.of("Files.ReadWrite.All", "offline_access", "User.Read"), authCodeCredential);
				}
			}
		}
		
		return GraphServiceClient
			.builder()
			.authenticationProvider(authProvider)
			.buildClient();
	}

```

The problematic call:

```
public static synchronized OneDriveFile[] getAllFilesForRoot(OneDriveRootFile rootFile) {
		List<DriveItem> items = new ArrayList<>();
		GraphServiceClient client = getClient();

                // causes java.lang.InterruptedException 
		DriveItemCollectionPage page = client
			.drives(rootFile.getDriveId())
			.root()
			.children()
			.buildRequest()
			.get();
		while (page != null && !page.getCurrentPage().isEmpty()) {
			for (DriveItem item : page.getCurrentPage()) {
				items.add(item);
			}
			if (page.getNextPage() != null) {
				page = page.getNextPage().buildRequest().get();
			} else {
				page = null;
			}
		}

		OneDriveFile[] files = new OneDriveFile[items.size()];
		int i = 0;
		for (DriveItem item : items) {
			files[i] = new OneDriveFile(item);
			i++;
		}
		return files;
	}
```

**Comment by baywet** [comment]
thanks for sharing this additional information.
First, is there any specific reason you are using the AuthCode credential and calling the browser manually instead of relying on the browser interactive credential? https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#InteractiveProvider

Could you try removing the synchronized keywords? Both the authentication process and the request execution rely on background threads and I'm guessing the way this code is designed might be impacting it.

**Comment by Noushed** [comment]
> thanks for sharing this additional information.
> First, is there any specific reason you are using the AuthCode credential and calling the browser manually instead of relying on the browser interactive credential? https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#InteractiveProvider
> 
> Could you try removing the synchronized keywords? Both the authentication process and the request execution rely on background threads and I'm guessing the way this code is designed might be impacting it.

@baywet 

InteractiveBrowserCredential usage was throwing Caused by: com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server

```
	private static GraphServiceClient createClient() throws IOException {
		if (authProvider == null) {
			final InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
					.clientId(OneDriveConstants.CLIENT_ID).redirectUrl(OneDriveConstants.REDIRECT_URI).build();
			authProvider = new TokenCredentialAuthProvider(
					List.of("Files.ReadWrite.All", "offline_access", "User.Read"), interactiveBrowserCredential);

		}
		
		return GraphServiceClient
			.builder()
			.authenticationProvider(authProvider)
			.buildClient();
	}
```


```
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:385)
	... 69 more
Caused by: java.util.concurrent.ExecutionException: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:55)
	... 75 more
Caused by: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithBrowserInteraction$28(IdentityClient.java:697)
	at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3325)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:80)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:140)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
```

Thats why I used authCode credentials. 

I will check without synchronised

**Comment by baywet** [comment]
@Noushed can you open up a separate issue for the browser credential [here](https://github.com/Azure/azure-sdk-for-java/issues/new) please?

**Comment by Noushed** [comment]
By modifying the synchronised design solved the issue
