### ISSUE TITLE
[graph sdk] java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void io.netty.channel.SingleThreadEventLoop.<init>(io.netty.channel.EventLoopGroup, java.util.concurrent.Executor, boolean, java.util.Queue, java.util.Queue, io.netty.util.concurrent.RejectedExecutionHandler)'

### ISSUE THREAD

**Issue by coolface88** [microsoftgraph/msgraph-sdk-java#790]
I have a problem with dependency issues of the java sdk 3.x.x

I have been trying to run 
```
final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(appId)
                .clientSecret(secret)
                .tenantId(tenantId)
                .build();

        List<String> scopes = Arrays.asList("https://graph.microsoft.com/.default");

        final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes, clientSecretCredential);

        GraphServiceClient graphClient = GraphServiceClient.builder()
                .authenticationProvider(tokenCredentialAuthProvider)
                .buildClient();

        ChatMessageCollectionPage messages = graphClient.teams("xxx.xxxx.xx")
                .channels("xxxxx.xxx")
                .messages()
                .buildRequest()
                .get();
```
I got this error

```
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void io.netty.channel.SingleThreadEventLoop.<init>(io.netty.channel.EventLoopGroup, java.util.concurrent.Executor, boolean, java.util.Queue, java.util.Queue, io.netty.util.concurrent.RejectedExecutionHandler)'
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:397)
	... 17 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void io.netty.channel.SingleThreadEventLoop.<init>(io.netty.channel.EventLoopGroup, java.util.concurrent.Executor, boolean, java.util.Queue, java.util.Queue, io.netty.util.concurrent.RejectedExecutionHandler)'
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:55)
	... 23 more
Caused by: java.lang.NoSuchMethodError: 'void io.netty.channel.SingleThreadEventLoop.<init>(io.netty.channel.EventLoopGroup, java.util.concurrent.Executor, boolean, java.util.Queue, java.util.Queue, io.netty.util.concurrent.RejectedExecutionHandler)'
	at io.netty.channel.kqueue.KQueueEventLoop.<init>(KQueueEventLoop.java:77)
	at io.netty.channel.kqueue.KQueueEventLoopGroup.newChild(KQueueEventLoopGroup.java:151)
	at io.netty.channel.kqueue.KQueueEventLoopGroup.newChild(KQueueEventLoopGroup.java:32)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.kqueue.KQueueEventLoopGroup.<init>(KQueueEventLoopGroup.java:110)
	at io.netty.channel.kqueue.KQueueEventLoopGroup.<init>(KQueueEventLoopGroup.java:97)
	at io.netty.channel.kqueue.KQueueEventLoopGroup.<init>(KQueueEventLoopGroup.java:73)
	at reactor.netty.resources.DefaultLoopKQueue.newEventLoopGroup(DefaultLoopKQueue.java:77)
	at reactor.netty.resources.DefaultLoopResources.cacheNativeServerLoops(DefaultLoopResources.java:255)
	at reactor.netty.resources.DefaultLoopResources.cacheNativeClientLoops(DefaultLoopResources.java:270)
	at reactor.netty.resources.DefaultLoopResources.onClient(DefaultLoopResources.java:202)
	at reactor.netty.tcp.TcpResources.onClient(TcpResources.java:234)
	at reactor.netty.http.client.HttpClientConnect$HttpTcpClient.connect(HttpClientConnect.java:139)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClientOperator.connect(TcpClientOperator.java:43)
	at reactor.netty.tcp.TcpClient.connect(TcpClient.java:218)
	at reactor.netty.http.client.HttpClientFinalizer.connect(HttpClientFinalizer.java:80)
	at reactor.netty.http.client.HttpClientFinalizer.responseConnection(HttpClientFinalizer.java:97)
	at com.azure.core.http.netty.NettyAsyncHttpClient.send(NettyAsyncHttpClient.java:84)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:44)
	at com.azure.core.http.policy.HttpLoggingPolicy.process(HttpLoggingPolicy.java:83)

```
This is part of my pom file

```
<dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>3.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.3</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.12.3</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.5.20-M1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.12.3</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>0.9.20.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.6</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.65.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-bom</artifactId>
            <version>4.1.37.Final</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.9.2</version>
        </dependency>

```

**Comment by baywet** [comment]
Hi @coolface88 
Thanks for reaching out.
Can you check whether you get the same result when calling the getToken method on tokenCredential directly please?

```Java
final TokenRequestContext context = new TokenRequestContext();
context.setScopes(Arrays.asList("https://graph.microsoft.com/.default"));
clientSecretCredential.getToken(context).toFuture().get();
```

After performing that test. Try aligning your dependencies with what azure identity requires. Given your error message, I believe reactor-netty is the faulty one.

azure-identity:1.3.0
netty-bom:4.1.63
netty-all 4.1.63
reactor-netty:1.0.6

**Comment by baywet** [comment]
Closing due to inactivity.
