### ISSUE TITLE
Getting 401 : Unauthorized error while creating new event using Graph SDK

### ISSUE THREAD

**Issue by Amrita-k1640** [microsoftgraph/msgraph-sdk-java#830]
Hi Team,

We are using Graph SDK 3.2.0 and it's dependent jars to POST an event.
We have CLIENT SECRET.
Please find below code snippet and error for the same.

			String CLIENT_ID = "###";
			final List<String> SCOPES = Arrays.asList(new String[]{"https://graph.microsoft.com/.default"});
			String CLIENT_SECRET = "####";
			String TENANT_GUID = "###";			
			String proxyHost = "host";
			int proxyPort = port;

			ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
					new InetSocketAddress(proxyHost, proxyPort));
			final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
					.clientId(CLIENT_ID).clientSecret(CLIENT_SECRET).tenantId(TENANT_GUID).proxyOptions(proxyOptions)
					.build();
			final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES,
					clientSecretCredential);

			String graphUrl="https://graph.microsoft.com/v1.0/users/{usersEmailId}/contacts";
			
			String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL(graphUrl)).get();

			System.out.println("Token : "+token);

			final OkHttpClient httpClient = com.microsoft.graph.httpcore.HttpClients
					.createDefault(tokenCredAuthProvider).newBuilder()
					.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort))).build();

			final GraphServiceClient graphClient = GraphServiceClient.builder().httpClient(httpClient).buildClient();
			
			List<Option> options = new LinkedList<Option>();
			options.add(new HeaderOption("Authorization", "Bearer " + token));
			options.add(new HeaderOption("Content-Type", "application/json"));
			
			Event newEvent = new Event();

			newEvent.subject = subject;

			newEvent.start = new DateTimeTimeZone();
			newEvent.start.dateTime = start.toString();
			newEvent.start.timeZone = timeZone;

			newEvent.end = new DateTimeTimeZone();
			newEvent.end.dateTime = end.toString();
			newEvent.end.timeZone = timeZone;

			if (attendees != null && !attendees.isEmpty()) {
				newEvent.attendees = new LinkedList<Attendee>();

				attendees.forEach((email) -> {
					Attendee attendee = new Attendee();
					// Set each attendee as required
					attendee.type = AttendeeType.REQUIRED;
					attendee.emailAddress = new EmailAddress();
					attendee.emailAddress.address = email;
					newEvent.attendees.add(attendee);
				});
			}

			if (body != null) {
				newEvent.body = new ItemBody();
				newEvent.body.content = body;
				// Treat body as plain text
				newEvent.body.contentType = BodyType.TEXT;
			}
			
			// POST /me/events
			graphClient.me().events().buildRequest(options).post(newEvent);`

Error which we are getting is 

```
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: CompactToken parsing failed with error code: 80049217

POST https://graph.microsoft.com/v1.0/me/events
Authorization : [PII_REDACTED]
Content-Type : application/json
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

401 : Unauthorized
[...]

[Some information was truncated for brevity, enable debug logging for more details]
com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: CompactToken parsing failed with error code: 80049217

POST https://graph.microsoft.com/v1.0/me/events
Authorization : [PII_REDACTED]
Content-Type : application/json
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

401 : Unauthorized
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:491)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:420)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:386)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:214)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:191)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:332)
	at com.microsoft.graph.requests.EventRequest.post(EventRequest.java:135)
	at com.microsoft.graph.requests.EventCollectionRequest.post(EventCollectionRequest.java:67)
	at com.ms.eandc.etool.REST.client.RESTWebServicesClient.createEvent(RESTWebServicesClient.java:127)
	at com.ms.eandc.etool.REST.client.AddRemoveOffice365EventCalendar.addCalendar(AddRemoveOffice365EventCalendar.java:112)
	at com.ms.eandc.etool.common.email.Office365Thread.run(Office365Thread.java:29)

```

And we have tried below for that  we are getting forbidder error.

```
//User me = graphClient.me().buildRequest().select("displayName,mailboxSettings").get();
			
			//User usme = graphClient.users("userEmailId").buildRequest().get();
			
			//User usser = graphClient.users("userEmailId").buildRequest().select("displayName,mailboxSettings").get(); 
```

Could you please assist on the same.
Please let us know if any other details are required.

Thank you 
[AB#10318](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10318)

**Comment by ramsessanchez** [comment]
Hi, apologies for the delayed response. 
We currently offer version 4.0.0, which is the latest version of the SDK. I would suggest upgrading to the latest version if possible and definitely follow up if the error persists. Thanks!

**Comment by Amrita-k1640** [comment]
We can't update from 3.2.0 to 4.0.0 .
Now please assist on above issue .

**Comment by baywet** [comment]
Hi @Amrita-k1640 ,
Can you provide more details on why the content type and authorization headers are set manually in your application?
Can you try removing that part and see if this solves the issue?
Can you expand on why you can't upgrade to v4?
What's the version of the core library in use right now?

**Comment by Amrita-k1640** [comment]
> We can't update from 3.2.0 to 4.0.0 .
> Now please assist on above issue .

Could you please provide me more details how to upgrade SDK to 4.0.0 ? If you have any code snippets regarding this upgrade or steps for upgrade, can you please provide me, so that I can proceed further.

**Comment by baywet** [comment]
are you using gradle or maven as a dependency manager?

**Comment by josephswaroopa** [comment]
Hi All,

For the above issue,we got a comment like need upgradation of graph SDK version  from 3.0 version to 4.0 version.We are trying to get GRAPH SDK 4.0 version and try, but one confirmation needed like,is this graph SDK 4.0 version is really solve the issue.Please confirm

**Comment by josephswaroopa** [comment]
Hi All,

This issue is prolonging for 3 months, we are running into tight schedule for now. Please suggest us how to resolve this issue .

**Comment by baywet** [comment]
@Amrita-k1640 simply updating the references in your pom.xml should be enough. See [the documentation](https://github.com/microsoftgraph/msgraph-sdk-java#12-install-via-maven)

@josephswaroopa this issue was opened only 2 weeks ago, not 3 months ago. We're sorry you're experiencing issues at this moment. We don't have enough information to reproduce the issue at this moment. As I was mentioning earlier can you please:
- Share a code snippet that reproduces the issue?
- Try to upgrade to 4.1.0 and see if you're still facing the issue?
Thanks!

**Comment by josephswaroopa** [comment]
@baywet 
Please find below code snippet,


			String CLIENT_ID = "###";
			final List<String> SCOPES = Arrays.asList(new String[]{"https://graph.microsoft.com/.default"});
			String CLIENT_SECRET = "###";
			String TENANT_GUID = "###";
			String proxyHost = "###";			
			int proxyPort = 8080;			
			ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
					new InetSocketAddress(proxyHost, proxyPort));
			final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
					.clientId(CLIENT_ID).clientSecret(CLIENT_SECRET).tenantId(TENANT_GUID).proxyOptions(proxyOptions)
					.build();
			final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES,
					clientSecretCredential);

			String graphUrl="https://graph.microsoft.com/v1.0/users/{UserEmailId}/calendar/events";
			
			String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL(graphUrl)).get();

						final OkHttpClient httpClient = com.microsoft.graph.httpcore.HttpClients
					.createDefault(tokenCredAuthProvider).newBuilder()
					.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort))).build();

			final GraphServiceClient graphClient = GraphServiceClient.builder().httpClient(httpClient).buildClient();
						
			List<Option> options = new LinkedList<Option>();
			options.add(new HeaderOption("Authorization", "Bearer " + token));
			options.add(new HeaderOption("Content-Type", "application/json"));			
			Event newEvent = new Event();
			newEvent.subject = "My Etool Event";
			ItemBody itemBody = new ItemBody();
			itemBody.contentType=BodyType.HTML;
			itemBody.content="###";
			newEvent.body=itemBody;
			DateTimeTimeZone startTime = new DateTimeTimeZone();
			startTime.dateTime="2020-11-11T12:00:00";
			startTime.timeZone="####";
			newEvent.start=startTime;
			DateTimeTimeZone endTime = new DateTimeTimeZone();
			endTime.dateTime="2020-11-11T14:00:00";
			endTime.timeZone="#####";
			newEvent.end=endTime;
			Location location = new Location();
			location.displayName = "###";
		newEvent.location=location;
					
			LinkedList<Attendee> attendeesList = new LinkedList<Attendee>();
			Attendee attendee = new Attendee();
			EmailAddress emailAddress = new EmailAddress();
			emailAddress.address = "###";
			emailAddress.name = "###";
			attendee.emailAddress = emailAddress;
			attendee.type = AttendeeType.REQUIRED;
			attendeesList.add(attendee);
			newEvent.attendees=attendeesList;
			newEvent.isOnlineMeeting=true;
			newEvent.onlineMeetingProvider=OnlineMeetingProviderType.TEAMS_FOR_BUSINESS;
			
			// POST /me/events
			newEvent.responseStatus=graphClient.me().events().buildRequest(options).post(newEvent).responseStatus;
			
		still same issue as below
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: CompactToken parsing failed with error code: 80049217

POST https://graph.microsoft.com/v1.0/me/events
Authorization : [PII_REDACTED]
Content-Type : application/json
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

401 : Unauthorized
[...]

[Some information was truncated for brevity, enable debug logging for more details]
com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: CompactToken parsing failed with error code: 80049217

POST https://graph.microsoft.com/v1.0/me/events
Authorization : [PII_REDACTED]
Content-Type : application/json
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

401 : Unauthorized
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:491)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:420)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:386)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:214)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:191)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:332)
	at com.microsoft.graph.requests.EventRequest.post(EventRequest.java:135)
	at com.microsoft.graph.requests.EventCollectionRequest.post(EventCollectionRequest.java:67)
	at com.ms.eandc.etool.REST.client.RESTWebServicesClient.createEvent(RESTWebServicesClient.java:153)
	at com.ms.eandc.etool.REST.client.AddRemoveOffice365EventCalendar.addCalendar(AddRemoveOffice365EventCalendar.java:121)
	at com.ms.eandc.etool.common.email.Office365Thread.run(Office365Thread.java:29)

**Comment by baywet** [comment]
thanks for the additional details, can you try again removing `options.add(new HeaderOption("Authorization", "Bearer " + token));` please? the middleware and authentication provider already automatically attach the bearer token for you.
(you don't need `options.add(new HeaderOption("Content-Type", "application/json"));` either)

**Comment by josephswaroopa** [comment]
@baywet  Many Thanks for the above comments.

 We tried removing options code,got below error, is that because of the UserMailId not having access to add event in calendar?

SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: ErrorAccessDenied
Error message: Access is denied. Check credentials and try again.

POST https://graph.microsoft.com/v1.0/me/events
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

403 : Forbidden
[...]

[Some information was truncated for brevity, enable debug logging for more details]
com.microsoft.graph.http.GraphServiceException: Error code: ErrorAccessDenied
Error message: Access is denied. Check credentials and try again.

POST https://graph.microsoft.com/v1.0/me/events
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

403 : Forbidden
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:491)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:420)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:386)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:214)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:191)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:332)
	at com.microsoft.graph.requests.EventRequest.post(EventRequest.java:135)
	at com.microsoft.graph.requests.EventCollectionRequest.post(EventCollectionRequest.java:67)
	at com.ms.eandc.etool.REST.client.RESTWebServicesClient.createEvent(RESTWebServicesClient.java:152)
	at com.ms.eandc.etool.REST.client.AddRemoveOffice365EventCalendar.addCalendar(AddRemoveOffice365EventCalendar.java:121)
	at com.ms.eandc.etool.common.email.Office365Thread.run(Office365Thread.java:29)

**Comment by baywet** [comment]
Thanks for the additional information. Now the service is not complaining about not being properly authenticated anymore, but simply about not having the right permissions for what you're trying to do.

Can you add this
```Java
final String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL("https://microsoft.graph.com/v1.0/me")).get();
```
and log the token.

Once you have the token, paste it to [jwt.ms](https://jwt.ms) (do not paste it here or share it with anyone) and copy the decoded token here please?

**Comment by josephswaroopa** [comment]
@baywet 
Thanks for the response.
Tried logging the token as you mentioned below but getting null value for that token variable.

final String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL("https://microsoft.graph.com/v1.0/me")).get();

**Comment by baywet** [comment]
Sorry I had inverted graph and Microsoft in the url in my previous reply. Please switch them up and try again

**Comment by josephswaroopa** [comment]
@baywet 
Sorry for late response,

Tried as suggested above, getting token successfully. When we trying to access the jwt.ms, it was blocked from our client network. So i couldn't share you the decoded token.

**Comment by baywet** [comment]
Does jwt.io work instead then?

**Comment by josephswaroopa** [comment]
@baywet 
jwt.io also blocked.

**Comment by baywet** [comment]
ok, I'm not sure how we can help you further at this point without cracking open the token.
I believe you're running in a permission issue where permissions are either missing, the wrong ones for the flow ([delegated vs app only](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#permission-types)), or [haven't been consented to by the admin](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent).
The call you're making requires at least [Calendars.ReadWrite](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#permissions)

**Comment by baywet** [comment]
Closing due to inactivity.
