### ISSUE TITLE
Got exception but email was actually sent

### ISSUE THREAD

**Issue by Kianhit** [microsoftgraph/msgraph-sdk-java#841]
### Expected behavior
Exception occurs and email not sent

### Actual behavior
Exception occurs but email sent(checked my sent email box).

### Steps to reproduce the behavior
not able to reproduce.

### exception log
com.microsoft.graph.core.ClientException: Error executing the request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:400) ~[microsoft-graph-core-2.0.1.jar:na]
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220) ~[microsoft-graph-core-2.0.1.jar:na]
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:197) ~[microsoft-graph-core-2.0.1.jar:na]
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:332) ~[microsoft-graph-core-2.0.1.jar:na]
        **at com.microsoft.graph.requests.UserSendMailRequest.post(UserSendMailRequest.java:54) ~[microsoft-graph-3.3.0.jar:na]**
        at com.awsi.sx.ss.estatement.service.GraphEmailService.sendEmailUsingGraph(GraphEmailService.java:123) ~[oracle-oc-sx-app-1.0.0.jar:1.0.0]
        at com.awsi.sx.dunningletter.service.DunningMailFaxService.processEmailAndFax(DunningMailFaxService.java:159) ~[oracle-oc-sx-app-1.0.0.jar:1.0.0]
        at com.awsi.sx.dunningletter.service.DunningLetterAsyncService.lambda$sendReports$3(DunningLetterAsyncService.java:228) ~[oracle-oc-sx-app-1.0.0.jar:1.0.0]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[na:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[na:1.8.0_241]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316) ~[na:1.8.0_241]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_241]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_241]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_241]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_241]

**Caused by: java.net.SocketTimeoutException: timeout**
        at okio.Okio$4.newTimeoutException(Okio.java:232) ~[okio-1.17.2.jar:na]
        at okio.AsyncTimeout.exit(AsyncTimeout.java:286) ~[okio-1.17.2.jar:na]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[okio-1.17.2.jar:na]
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358) ~[okio-1.17.2.jar:na]
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230) ~[okio-1.17.2.jar:na]
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:137) ~[microsoft-graph-core-2.0.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:176) ~[microsoft-graph-core-2.0.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:59) ~[microsoft-graph-core-2.0.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69) ~[microsoft-graph-core-2.0.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:na]
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:397) ~[microsoft-graph-core-2.0.1.jar:na]
        ... 19 common frames omitted

**Caused by: java.net.SocketException: Socket closed**
        at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[na:1.8.0_241]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_241]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_241]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_241]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[na:1.8.0_241]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[na:1.8.0_241]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_241]
        at okio.Okio$2.read(Okio.java:140) ~[okio-1.17.2.jar:na]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.17.2.jar:na]
        ... 52 common frames omitted

### code to use sdk
_graphClient.users(principleName)
                .sendMail(UserSendMailParameterSet
                        .newBuilder()
                        .withMessage(message)
                        .withSaveToSentItems(null)
                        .build())
                .buildRequest()
                .post(); -- line 123_

 
[AB#10547](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10547)

**Comment by baywet** [comment]
Hey @Kianhit 
Thanks for reaching out.
Can you please update to graph core 2.0.8 and this library 4.2.0 and let us know if you're still facing the issue?
Thanks!

**Comment by baywet** [comment]
Closing due to inactivity.
