### ISSUE TITLE
IDriveItemDeltaCollectionPage.getNextPage() not working correctly

### ISSUE THREAD

**Issue by J0s3f** [microsoftgraph/msgraph-sdk-java#86]
The following code fails:
```java
    public class MinimalExample {
        public static void main(String... args) {
            CrawlerAuthenticator authenticator = new CrawlerAuthenticator("...", "...", "...");
            IGraphServiceClient graphClient =
                    GraphServiceClient
                            .builder()
                            .authenticationProvider(authenticator)
                            .buildClient();
            graphClient.getLogger().setLoggingLevel(LoggerLevel.DEBUG);
            Drive start = graphClient
                    .drive()
                    .buildRequest().get();
            String driveId = start.id;
            IDriveItemDeltaCollectionPage deltaPage = graphClient.drives(driveId).root().delta().buildRequest().get();
            while (deltaPage.deltaLink() == null) {
                handleItems(deltaPage.getCurrentPage());
                deltaPage = deltaPage.getNextPage().buildRequest().get();
            }
        }
    
        private static void handleItems(List<DriveItem> currentPage) {
            //no-op
        }
    }
```

The call `deltaPage = deltaPage.getNextPage().buildRequest().get();` fails as follows:

    SCHWERWIEGEND: Throwable detail: com.microsoft.graph.http.GraphServiceException: GET https://graph.microsoft.com/v1.0/drives('b!REDACTEDcjVl7e0aGT66lzi2gV2v-')/root/microsoft.graph.delta(token='REDACTEDJTIzOyUyMzQ')(token=null)
    SdkVersion : graph-java-v0.2.0
    Authorization : bearer VALID_AUTH_TOKEN

    400 : Bad Request
    HTTP/1.1 400 Bad Request
    Transfer-Encoding : chunked
    Strict-Transport-Security : max-age=31536000
    Cache-Control : private
    x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceA","Ring":"2","ScaleUnit":"000","Host":"AGSFE_IN_3","ADSiteName":"DUB"}}
    client-request-id : bc9233de-1884-4503-89de-838101c78ac5
    Duration : 3.7717
    request-id : bc9233de-1884-4503-89de-838101c78ac5
    Date : Mon, 23 Apr 2018 15:49:21 GMT
    Content-Type : application/json
    {
    "error": {
        "code": "BadRequest",
        "message": "Syntax error at position 160 in \u0027token\u003d\u0027REDACTEDJTIzOyUyMzQ\u0027)(token\u003dnull\u0027.",
        "innerError": {
        "request-id": "bc9233de-1884-4503-89de-838101c78ac5",
        "date": "2018-04-23T15:49:22"
        }
    }
    }

Changing the while-loop to:
```java
            while (deltaPage.deltaLink() == null) {
                handleItems(deltaPage.getCurrentPage());
                String url = deltaPage.getNextPage().getRequestUrl().replaceFirst(graphClient.getServiceRoot(), "");
                deltaPage = graphClient.customRequest(url, DriveItemDeltaCollectionPage.class).buildRequest().get();
            }
```

I can see in the debugger that the request is successful, but it is not possible to convert the resulting JSON to an DriveItemDeltaCollectionPage
```
SCHWERWIEGEND: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
Exception in thread "main" com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:345)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:191)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:171)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:277)
	at com.microsoft.graph.http.CustomRequest.get(CustomRequest.java:43)
	at at.knowcenter.crawler.sharepoint_online.MinimalExample.main(MinimalExample.java:63)
Caused by: java.lang.NullPointerException
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:99)
	at com.microsoft.graph.http.DefaultHttpProvider.handleJsonResponse(DefaultHttpProvider.java:394)
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:324)
	... 5 more
```

Changing the loop to
```java
            Gson gson = new Gson();
            while (deltaPage.deltaLink() == null) {
                handleItems(deltaPage.getCurrentPage());
                String url = deltaPage.getNextPage().getRequestUrl().replaceFirst(graphClient.getServiceRoot(), "");
                JsonObject res = graphClient.customRequest(url).buildRequest().get();
                System.out.println(gson.toJson(res));
            }
```

prints the correct server response to stdout.

**Comment by J0s3f** [comment]
I was a bit in a hurry when I created this issue yesterday evening and missed that it is already reported as #81 
The mentioned pull request #82 fixes it
