### ISSUE TITLE
Getting PKIX path validation failed

### ISSUE THREAD

**Issue by josephswaroopa** [microsoftgraph/msgraph-sdk-java#877]
We are using below code to connect to Office 365 server to add events to outlook calendar using graph SDK version 3.0.0 version jar,

```Java
String CLIENT_ID = "*********";
			final List<String> SCOPES = Arrays.asList(new String[]{"https://graph.microsoft.com/.default"});
			
			String CLIENT_SECRET = "*****************";
			String TENANT_GUID = "*******************";
			String proxyHost = "***************";
			
			int proxyPort = 8080;
			ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
					new InetSocketAddress(proxyHost, proxyPort));
			final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
					.clientId(CLIENT_ID).clientSecret(CLIENT_SECRET).tenantId(TENANT_GUID).proxyOptions(proxyOptions)
					.build();
			final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES,
					clientSecretCredential);
			
			
			userMail="********@alpha.morganstanley.com";
			String graphUrl="https://graph.microsoft.com/v1.0/users/"+userMail+"/calendar/events";
			String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL(graphUrl)).get();
			logger.info("Token : "+token);
			final OkHttpClient httpClient = com.microsoft.graph.httpcore.HttpClients
					.createDefault(tokenCredAuthProvider).newBuilder()
					.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort))).build();
			final GraphServiceClient graphClient = GraphServiceClient.builder().httpClient(httpClient).buildClient();
			//final GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider(tokenCredAuthProvider).buildClient();
			Event newEvent = new Event();

			newEvent.subject = subject;
			ItemBody itemBody = new ItemBody();
			itemBody.contentType=BodyType.HTML;
			itemBody.content=body;
			newEvent.body=itemBody;
		
			DateTimeTimeZone startTime = new DateTimeTimeZone();
			startTime.dateTime=startDate.toString();
			
			startTime.timeZone="Eastern Standard Time";
			newEvent.start=startTime;
			DateTimeTimeZone endTime = new DateTimeTimeZone();
			endTime.dateTime=endDate.toString();
			
			endTime.timeZone="Eastern Standard Time";
			newEvent.end=endTime;
			Location location = new Location();
			location.displayName = sessionInfoBean.getLocation();
		newEvent.location=location;
			LinkedList<Attendee> attendeesList = new LinkedList<Attendee>();
			Attendee attendee = new Attendee();
				EmailAddress emailAddress = new EmailAddress();
				emailAddress.address = userMail;
				emailAddress.name = userName;
				attendee.emailAddress = emailAddress;
				attendee.type = AttendeeType.REQUIRED;
			attendeesList.add(attendee);
			newEvent.attendees=attendeesList;
			newEvent.isOnlineMeeting=true;
			newEvent.onlineMeetingProvider=OnlineMeetingProviderType.TEAMS_FOR_BUSINESS;
			logger.info("Event>>"+newEvent.toString());
			
			
			// POST /me/events
			 eventIdResponse=graphClient.users(userMail).events().buildRequest().post(newEvent).id;
			logger.info("response create status>>>"+eventIdResponse);
```

The above code is working properly for more than two weeks and able to add/remove events in outlook calendar.
Suddenly i got below error from yesterday.
Please help me in this .

```
ERROR c.m.a.m.ConfidentialClientApplication - [Correlation ID: 1bf20841-40d3-4d43-8350-33e723e0ab69] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:68)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:157)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:221)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:56)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.microsoft.aad.msal4j.DefaultHttpClient.readResponseFromConnection(DefaultHttpClient.java:107)
	at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpGet(DefaultHttpClient.java:47)
	at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:35)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64)
	... 14 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 32 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357)
	... 38 common frames omitted
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sun Sep 05 12:14:37 IST 2021
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
	at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
```

**Comment by josephswaroopa** [comment]
Kindly check above issue and Help me in this

**Comment by baywet** [comment]
Hi @josephswaroopa 
Thanks for reaching out.
The error seems to be coming from Azure Identity at this top level stack trace would indicate `com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest`. I suggest you reach out on [their repo](https://github.com/Azure/azure-sdk-for-java) as they'll be able to better assist you.

Now, looking at your stacktrace `java.security.cert.CertificateExpiredException: NotAfter: Sun Sep 05 12:14:37 IST 2021` it looks like the certificate for your proxy might have expired, you should double check that aspect.

Closing.
