### ISSUE TITLE
Need help in response view for Delete event using graph SDk 3.0 version

### ISSUE THREAD

**Issue by josephswaroopa** [microsoftgraph/msgraph-sdk-java#900]
Hi Team,

Please help in how to find the response for delete event using graph SDL 3.0 version when connecting to office 365.Below is my code,with that code iam getting empty/null response.Please correct me like by which i can confirm whether the Event/task got deleted or not from outlook.

Please help me in this issue.And one more thing i observed that while generating the tokenCredAuthProvider variable, iam getting error in console, but its not affecting the delete/add events functioanlity.Iam attaching the Error also.Please help me in that as well.

Delete Code : 

String CLIENT_ID = "*******************";
			final List<String> SCOPES = Arrays.asList(new String[]{"https://graph.microsoft.com/.default"});
			
			String CLIENT_SECRET = "**********************";
			String TENANT_GUID =  "**********************";
			String proxyHost = "**********************";
			
			int proxyPort =  **********************;
			String graphUrl="https://graph.microsoft.com/v1.0/users/+userId+/calendar/events"; 

ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
				new InetSocketAddress(proxyHost, proxyPort));
		final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				.clientId(CLIENT_ID).clientSecret(CLIENT_SECRET).tenantId(TENANT_GUID).proxyOptions(proxyOptions)
				.build();
		final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES,
				clientSecretCredential);
		String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL(graphUrl)).get();
		
		final OkHttpClient httpClient = com.microsoft.graph.httpcore.HttpClients
				.createDefault(tokenCredAuthProvider).newBuilder()
				.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort))).build();
		final GraphServiceClient graphClient = GraphServiceClient.builder().httpClient(httpClient).buildClient();
		
		boolean responseDeleteEvent=graphClient.users(userId).events(inputId)
		.buildRequest()
		.delete().responseRequested;

Error while generating token,

 DEBUG c.m.a.m.ConfidentialClientApplication - [Correlation ID: 8ee0adf9-8bb5-4fde-8256-1faaeb9aee09] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:80)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Thanks,
Swaroopa Rani J W

**Comment by baywet** [comment]
Hi @josephswaroopa 
Can you upgrade to the latest version (5.3.0 at the time of writing) and the latest of azure identity (1.3.6) and let us know whether you're still experiencing the same issue please?

**Comment by josephswaroopa** [comment]
@baywet 
Thanks for the reply.

Which jar we need to upgrade to 5.30 version?
as of now, we are using azure-identity to 1.2.3 version, that we will try to upgrade as you suggested 1.3.6 version.

**Comment by baywet** [comment]
com.microsoft.graph:microsoft-graph:5.3.0

**Comment by baywet** [comment]
do you have a direct reference to microsoft graph core as well? or is it only transitively referenced from this other one? if you have a direct reference, can you upgrade it to 2.0.9 please?
