### ISSUE TITLE
can't get items in onedrive, return itemNotFound

### ISSUE THREAD

**Issue by zhouyihaocc** [microsoftgraph/msgraph-sdk-java#980]
**I'am trying to use graph java sdk to get my files in onedrive, get myself information(https://graph.microsoft.com/v1.0/me/) is fine, it can get my name, email. 
but when i try to get onedrive files, it throws itemNotFound.  I have checked my permission in azure, this application has 
Sites.ReadWrite.All,  Files.ReadWrite.All permissions, so the permission should be fine. I'm just wondering is this java sdk error or i miss some configuration. 
the java sdk version is 1.8, microsoft-graph version is 5.9.0, azure-identity is 1.3.1. 
here is my java code** 

> final UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredentialBuilder().clientId(clientId).username(username).password(password).build(); 
final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes,
                usernamePasswordCredential);  
GraphServiceClient graphClient = GraphServiceClient
                        .builder()
                        .authenticationProvider(tokenCredentialAuthProvider)
                        .buildClient(); 
LinkedList<Option> requestOptions = new LinkedList<Option>();
requestOptions.add(new QueryOption("select", "name,id,webUrl"));
graphClient.me().drive().root().children().buildRequest().get();

### Expected behavior

**When use the API "https://graph.microsoft.com/v1.0/me/drive/root/children"  the result should be a json like** 
`
{
    "@odata.context": "",
    "value": [
        {
            "createdDateTime": "2022-01-06T07:49:38Z",
            "eTag": "",
            "id": "",
            "lastModifiedDateTime": "",
            "name": "",
            "webUrl": "",
            "cTag": "",
            "size": 9,
            "createdBy": {
                "user": {
                    "email": "",
                    "id": "",
                    "displayName": ""
                }
            },
            "lastModifiedBy": {},
            "parentReference": {},
            "fileSystemInfo": {},
            "folder": {
                "childCount": 1
            }
        }
    ]
}`

### Actual behavior
**the sdk error output is below**

CoreHttpProvider[sendRequestInternal] - 406GET https://graph.microsoft.com/v1.0/me/drive/root/children
Error message: Item not found

GET https://graph.microsoft.com/v1.0/me/drive/root/children
SdkVersion : graph-java/v5.9.0

404 : Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]
com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound
Error message: Item not found

GET https://graph.microsoft.com/v1.0/me/drive/root/children
SdkVersion : graph-java/v5.9.0

404 : Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:511)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:440)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:406)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:223)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:102)
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
	at TestUpload.main(TestUpload.java:49)

### Steps to reproduce the behavior
when you use the java code above, you can see this error.

**Comment by zhouyihaocc** [comment]
and I can list onedrive items in graph explorer, the java code just not work

**Comment by ramsessanchez** [comment]
Hi @zhouyihaocc , it seems from your example code that you are not adding the request options to the request. 
Right now you have 
``` Java
graphClient.me().drive().root().children().buildRequest().get();
```
You should replace this with 
```Java 
graphClient.me().drive().root().children().buildRequest( requestOptions ).get();
//whole solution would be as follows: 
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

LinkedList<Option> requestOptions = new LinkedList<Option>();
requestOptions.add(new QueryOption("select", "name,id,webUrl"));

DriveItem driveItem = graphClient.me().drive().root()
	.buildRequest( requestOptions )
	.get();
```

**Comment by zhouyihaocc** [comment]
I’ave tried you code, but still get the same error.  Am i using the wrong sdk version? It’s so strange.

**Comment by ramsessanchez** [comment]
Hi @zhouyihaocc , Please make sure that you have the Files.readAll and the Sites.ReadAll delegrated permissions added to your app on the Azure Active Directory portal. 
Please let me know if this helps you. Thanks!

**Comment by zhouyihaocc** [comment]
yes, I have those permissions, and the file do exists.

**Comment by ramsessanchez** [comment]
Hi @zhouyihaocc , could you share a screenshot of your permissions, hide any sensitive information. I was running into the same error as you are running into on a sample app. I was able to solve it by adding the correct permissions, I believe that although you may have the correct permissions they may be set up or configured incorrectly.

**Comment by zhouyihaocc** [comment]
This is the permissions i have.
![permissions](https://user-images.githubusercontent.com/33424944/149055611-e52a1bb1-c7c6-46d7-bfa8-35a07e1d9678.png)

**Comment by ramsessanchez** [comment]
![image](https://user-images.githubusercontent.com/63934382/149061215-75f0726a-7a65-4c07-aee5-8bf647f4b72b.png)

**Comment by ramsessanchez** [comment]
@zhouyihaocc, this is what my permissions look like. 
Can you confirm that on the status column of your permissions they in fact say 'Granted' for either the user or organization that you are using for your application. Thanks!

**Comment by ramsessanchez** [comment]
![image](https://user-images.githubusercontent.com/63934382/149061593-0db5ed90-7768-4215-aa02-31ff90cf4956.png)

**Comment by zhouyihaocc** [comment]
I'm not sure what to look for, in my application there is not text like 'Granted for'. 
Does it necessary? and i thought those delegated permissions don't require admin consent.

**Comment by ramsessanchez** [comment]
Hi @zhouyihaocc , it seems that admin consent is required for those permissions. I can see why you may have been confused. At first, I also thought that the 'no' on the Admin Consent Required column meant that it was not necessary. 
However:
![image](https://user-images.githubusercontent.com/63934382/149128251-4f6bece9-3396-43ae-91dd-d90d49887d49.png)
I have tested it on my end also. When I revoke admin consent, I also receive the same 404 error as you. I would suggest talking to your admin and request that they grant access for these permissions, or change it yourself if you are the admin.

**Comment by ramsessanchez** [comment]
If you are admin you should see this option above your permissions table. 
![image](https://user-images.githubusercontent.com/63934382/149129571-6de9aafc-194b-4466-96ce-258195eb3f4f.png)
